Repository cBioPortal/cbioportal-frontend, pull requests merged in 2018-03, with the labels that each got.

#1008 Adapt some functions to deal with queries with only gene sets
  src/pages/resultsView/ResultsViewPage.tsx
  src/pages/resultsView/ResultsViewPageStore.ts
  src/shared/components/oncoprint/ResultsViewOncoprint.tsx
  src/shared/components/query/GenesetsValidator.tsx
  src/shared/components/query/QueryStore.spec.ts
  src/shared/components/query/QueryStore.ts
  src/shared/lib/oql/oql-parser.d.ts
Labels: enhancement, ready to review

#830 Implement volcano plot popup for GSVA data
  package-lock.json
  src/shared/components/query/GenesetsSelector.tsx
  src/shared/components/query/GenesetsVolcanoSelector.tsx
  src/shared/components/query/QueryStore.ts
  src/shared/components/query/styles/styles.module.scss
Labels: enhancement

#1037 Update README.md
  README.md
  scripts/env_vars.sh
Labels: DO NOT MERGE
