Repository cBioPortal/cbioportal-frontend, pull requests merged in 2018-12, with the labels that each got.

#1752 Custom tabs: invoke callback on unmount event of tab
  src/pages/resultsView/ResultsViewPage.tsx
  src/shared/components/MSKTabs/MSKTabs.tsx
  src/shared/lib/customTabs.ts
Labels: DO NOT MERGE

#1819 Fixed ProgressIndicator related TS errors for the CN Segments tab
  src/pages/resultsView/cnSegments/CNSegments.tsx
Labels: critical

#1854 Fix custom list of genes property
  src/config/config.ts
Labels: bug

#1706 Oncoprinter
  end-to-end-tests/screenshots/reference/oncoprinter_example_data,_dont_color_by_driver_vs_vus_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/oncoprinter_example_data,_dont_color_by_mutation_type_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/oncoprinter_example_data,_hide_vus_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/oncoprinter_example_data,_start_by_set_gene_order,_then_set_sample_order_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/oncoprinter_example_data,_start_by_set_sample_order,_then_set_gene_order_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/oncoprinter_example_data,_then_set_gene_order,_including_all_genes_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/oncoprinter_example_data,_then_set_gene_order,_not_including_all_genes_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/oncoprinter_example_data,_then_set_sample_order,_including_all_samples_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/oncoprinter_example_data,_then_set_sample_order,_not_including_all_samples_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/oncoprinter_example_data_element_chrome_1600x1000.png
  end-to-end-tests/specs/home.spec.js
  end-to-end-tests/specs/screenshot.spec.js
  end-to-end-tests/specs/specUtils.js
  package-lock.json
  package.json
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/mutationCountHelpers.ts
  src/pages/staticPages/tools/oncoprinter/Oncoprinter.tsx
  src/pages/staticPages/tools/oncoprinter/OncoprinterConstants.ts
  src/pages/staticPages/tools/oncoprinter/OncoprinterStore.ts
  src/pages/staticPages/tools/oncoprinter/OncoprinterTool.tsx
  src/pages/staticPages/tools/oncoprinter/OncoprinterUtils.ts
  src/pages/staticPages/visualize/Visualize.tsx
  src/routes.jsx
  src/shared/components/oncoprint/DataUtils.ts
  src/shared/components/oncoprint/DeltaUtils.ts
  src/shared/components/oncoprint/Oncoprint.tsx
  src/shared/components/oncoprint/OncoprintUtils.ts
  src/shared/components/oncoprint/ResultsViewOncoprint.tsx
  src/shared/components/oncoprint/SortUtils.ts
  src/shared/components/oncoprint/TooltipUtils.spec.ts
  src/shared/components/oncoprint/TooltipUtils.ts
  src/shared/components/oncoprint/controls/OncoprintControls.tsx
  src/shared/lib/AnnotationUtils.ts
  src/shared/lib/StoreUtils.ts
  src/shared/lib/oql/accessors.ts
  tsconfig.json
Labels: DO NOT MERGE, needs tests

#1803 Changes for displaying FACETS data
  src/pages/patientView/mutation/PatientViewMutationTable.tsx
  src/pages/patientView/mutation/column/FACETSColumnFormatter.tsx
  src/pages/resultsView/mutation/ResultsViewMutationTable.tsx
  src/shared/components/mutationTable/MutationTable.tsx
  src/shared/components/mutationTable/column/CancerCellFractionColumnFormatter.tsx
  src/shared/components/mutationTable/column/ClonalColumnFormatter.tsx
  src/shared/components/mutationTable/column/DiscreteCNAColumnFormatter.tsx
  src/shared/components/mutationTable/column/MutantCopiesColumnFormatter.tsx
Labels: feature
