Repository cBioPortal/cbioportal-frontend, pull requests merged in 2018-11, with the labels that each got.

#1663 Use new digitalslide archive api and page url for tissues image on pa…
  src/config/IAppConfig.ts
  src/config/serverConfigDefaults.ts
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
  src/shared/api/urls.ts
Labels: DO NOT MERGE

#1682 AWS apiRoot hack: fix session service proxy
  src/AppStore.ts
  src/config/config.ts
  src/pages/resultsView/network/Network.tsx
  src/shared/api/urls.ts
Labels: ready to review

#1702 DataAccessTokens download token details on auth. portals
  src/appShell/App/PortalHeader.tsx
  src/config/IAppConfig.ts
  src/config/serverConfigDefaults.ts
  src/shared/api/generated/CBioPortalAPI.ts
  src/shared/api/urls.ts
  src/shared/components/dataAccessTokens/DataAccessTokens.tsx
Labels: feature

#1710 Study view fixes
  src/pages/studyView/StudyViewConfig.ts
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/StudyViewUtils.spec.ts
  src/pages/studyView/StudyViewUtils.tsx
  src/pages/studyView/chartHeader/ChartHeader.tsx
  src/pages/studyView/chartHeader/styles.module.scss
  src/pages/studyView/charts/ChartContainer.tsx
  src/pages/studyView/charts/barChart/BarChart.tsx
  src/pages/studyView/charts/pieChart/PieChart.tsx
  src/pages/studyView/table/CNAGenesTable.tsx
  src/pages/studyView/table/MutatedGenesTable.tsx
  src/pages/studyView/tabs/SummaryTab.tsx
  src/shared/api/urls.ts
Labels: ready to review

#1719 Optimization: only query for hotspot genes
  package.json
  scripts/get_hotspot_genes.sh
  src/shared/lib/CancerHotspotsUtils.spec.ts
  src/shared/lib/CancerHotspotsUtils.ts
  src/shared/static-data/hotspotGenes.json
Labels: ready to review

#1658 Feature branch for extending Mutation Table to show FACETS data
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
  src/pages/patientView/mutation/PatientViewMutationTable.tsx
  src/pages/resultsView/ResultsViewPage.tsx
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/mutation/Mutations.tsx
  src/pages/resultsView/mutation/ResultsViewMutationMapper.tsx
  src/pages/resultsView/mutation/ResultsViewMutationTable.tsx
  src/pages/staticPages/tools/mutationMapper/StandaloneMutationTable.tsx
  src/shared/api/generated/CBioPortalAPI.ts
  src/shared/components/mutationMapper/MutationMapperStore.ts
  src/shared/components/mutationTable/MutationTable.tsx
  src/shared/components/mutationTable/column/ClonalColumnFormatter.tsx
  src/shared/components/mutationTable/column/DiscreteCNAColumnFormatter.tsx
  src/shared/components/mutationTable/column/MutantCopiesColumnFormatter.tsx
  src/shared/lib/NumberUtils.ts
  src/shared/lib/StoreUtils.ts
  src/test/CivicMockUtils.ts
  src/test/MutationMockUtils.ts
Labels: feature

#1714 Migrate DAT endpoint to internal API
  src/shared/api/generated/CBioPortalAPI-docs.json
  src/shared/api/generated/CBioPortalAPI.ts
  src/shared/api/generated/CBioPortalAPIInternal-docs.json
  src/shared/api/generated/CBioPortalAPIInternal.ts
  src/shared/api/generated/OncoKbAPI-docs.json
  src/shared/api/generated/OncoKbAPI.ts
  src/shared/api/urls.ts
  src/shared/components/dataAccessTokens/DataAccessTokens.tsx
Labels: feature

#1720 Move study view under single page application
  package-lock.json
  package.json
  src/pages/patientView/PatientViewPage.tsx
  src/pages/resultsView/querySummary/QuerySummary.tsx
  src/pages/studyView/StudyViewPage.tsx
  src/pages/studyView/addChartButton/AddChartButton.tsx
  src/pages/studyView/studyPageHeader/studySummary/StudySummary.tsx
  src/pages/studyView/virtualStudy/VirtualStudy.tsx
  src/routes.jsx
  src/shared/api/urls.ts
  src/shared/components/StudyLink/StudyLink.tsx
  src/shared/components/query/QueryStore.ts
  src/shared/components/query/studyList/StudyList.tsx
  src/shared/components/rightbar/RightBar.tsx
  src/shared/lib/redirectHelpers.ts
Labels: ready to review

#1763 Format DAT dates for download token file
  src/appShell/App/PortalHeader.tsx
  src/shared/components/dataAccessTokens/DataAccessTokens.tsx
Labels: bug
