Repository cBioPortal/cbioportal-frontend, pull requests merged in 2018-05, with the labels that each got.

#1099 Parse ‘merged track’ syntax in OQL queries
  src/pages/resultsView/ResultsViewPage.tsx
  src/shared/components/query/QueryStore.ts
  src/shared/lib/oql/README.md
  src/shared/lib/oql/README.txt
  src/shared/lib/oql/generateParser.py
  src/shared/lib/oql/oql-parser.d.ts
  src/shared/lib/oql/oql-parser.js
  src/shared/lib/oql/oql_basic.pegjs
  src/shared/lib/oql/oqlfilter.d.ts
  src/shared/lib/oql/oqlfilter.js
  src/shared/lib/oql/test-oql-parser.js
Labels: enhancement, hyve

#1144 Use correct field for OncoKB tumor type
  src/shared/lib/OncoKbUtils.ts
Labels: ready to review

#1170 Replace 'Enter Gene Set' by 'Enter Genes' to avoid confusion in the query page
  src/shared/components/query/GeneSetSelector.tsx
Labels: bug, ready to review

#1143 Render merged track queries as single Oncoprint tracks
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/ResultsViewPageStoreUtils.ts
  src/pages/resultsView/download/DownloadUtils.spec.ts
  src/pages/resultsView/download/DownloadUtils.ts
  src/shared/components/oncoprint/DataUtils.spec.ts
  src/shared/components/oncoprint/DataUtils.ts
  src/shared/components/oncoprint/Oncoprint.tsx
  src/shared/components/oncoprint/OncoprintUtils.spec.ts
  src/shared/components/oncoprint/OncoprintUtils.ts
  src/shared/components/oncoprint/tabularDownload.ts
  src/shared/lib/oql/oqlfilter.d.ts
  src/shared/lib/oql/oqlfilter.js
  src/shared/lib/oql/oqlfilter.spec.ts
Labels: enhancement, hyve, results.oncoprint

#1199 Enable expansion for ‘merged gene’ tracks
  package-lock.json
  package.json
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/ResultsViewPageStoreUtils.spec.ts
  src/pages/resultsView/ResultsViewPageStoreUtils.ts
  src/pages/resultsView/download/DownloadUtils.ts
  src/shared/components/oncoprint/DeltaUtils.spec.ts
  src/shared/components/oncoprint/DeltaUtils.ts
  src/shared/components/oncoprint/Oncoprint.tsx
  src/shared/components/oncoprint/OncoprintUtils.spec.ts
  src/shared/components/oncoprint/OncoprintUtils.ts
  src/shared/components/oncoprint/ResultsViewOncoprint.tsx
Labels: enhancement, hyve, results.oncoprint

#1165 Ignoring invalid allele count values
  src/shared/components/mutationTable/column/AlleleCountColumnFormatter.spec.tsx
  src/shared/components/mutationTable/column/AlleleCountColumnFormatter.tsx
Labels: refactoring

#1209 Enrichments style fixes
  end-to-end-tests/specs/home.spec.js
  src/pages/resultsView/enrichments/AlterationEnrichmentsTable.tsx
  src/pages/resultsView/enrichments/MiniBarChart.tsx
  src/pages/resultsView/enrichments/MiniBoxPlot.tsx
  src/pages/resultsView/enrichments/MiniScatterChart.tsx
  src/pages/resultsView/enrichments/styles.module.scss
  src/pages/resultsView/survival/styles.module.scss
Labels: results.enrichments
