Repository cBioPortal/cbioportal-frontend, pull requests merged in 2018-10, with the labels that each got.

#1432 Implement gene set option in plots tab
  package-lock.json
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/plots/PlotsTab.tsx
  src/pages/resultsView/plots/PlotsTabUtils.tsx
  src/shared/cache/GenesetCache.ts
Labels: hyve, refactoring

#1429 Add Mutation Mapper Tool Dropdown
  Procfile
  end-to-end-tests/screenshots/reference/no_session_mutation_tab_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/session_mutation_tab_element_chrome_1600x1000.png
  end-to-end-tests/specs/data/hla_a_test_mutation_mapper_tool.txt
  end-to-end-tests/specs/mutationMapperTool.spec.js
  end-to-end-tests/wdio/webdriver-manager.conf.js
  package.json
  src/pages/tools/mutationMapper/MutationMapperTool.tsx
  src/pages/tools/mutationMapper/MutationMapperToolStore.ts
  src/pages/tools/mutationMapper/resources/standaloneMutationDataExample.txt
  src/pages/tools/mutationMapper/resources/standaloneMutationDataExampleWithGenomicCoordinatesOnly.txt
  src/shared/components/lollipopMutationPlot/LollipopMutationPlot.tsx
  src/shared/components/mutationMapper/MutationMapper.tsx
  src/shared/components/mutationMapper/MutationMapperStore.ts
  src/shared/components/mutationMapper/ensembl_icon.png
  src/shared/components/mutationMapper/styles.scss
  src/shared/components/mutationTable/column/FunctionalImpactColumnFormatter.tsx
  src/shared/lib/MutationAnnotator.spec.ts
  src/shared/lib/MutationAnnotator.ts
  src/shared/lib/MutationUtils.ts
  src/shared/lib/StoreUtils.ts
Labels: ready to review

#1587 E2E tests remove redundant viewport size
  end-to-end-tests/specs/home.spec.js
  end-to-end-tests/specs/screenshot.spec.js
Labels: ready to review

#1660 Fixed incorrect import of onMobxPromise in Download Tab
  src/pages/resultsView/download/DownloadTab.tsx
Labels: critical
