Repository cBioPortal/cbioportal-frontend, pull requests merged in 2019-11, with the labels that each got.

#2698 Indicate non-profiled mutations for samples in Patient View
  end-to-end-test/local/docker/setup_docker_containers.sh
  end-to-end-test/local/specs/core/patientview.spec.js
  end-to-end-test/local/studies/genepanel_test_study/case_lists/cases_cna.txt
  end-to-end-test/local/studies/genepanel_test_study/case_lists/cases_sequenced.txt
  end-to-end-test/local/studies/genepanel_test_study/data_cancer_type.txt
  end-to-end-test/local/studies/genepanel_test_study/data_clinical_patients.txt
  end-to-end-test/local/studies/genepanel_test_study/data_clinical_samples.txt
  end-to-end-test/local/studies/genepanel_test_study/data_cna_discrete.txt
  end-to-end-test/local/studies/genepanel_test_study/data_cna_hg19.seg
  end-to-end-test/local/studies/genepanel_test_study/data_gene_panel_matrix.txt
  end-to-end-test/local/studies/genepanel_test_study/data_gene_panel_testpanel1.txt
  end-to-end-test/local/studies/genepanel_test_study/data_gene_panel_testpanel2.txt
  end-to-end-test/local/studies/genepanel_test_study/data_mutations_extended.maf
  end-to-end-test/local/studies/genepanel_test_study/meta_cancer_type.txt
  end-to-end-test/local/studies/genepanel_test_study/meta_clinical_patients.txt
  end-to-end-test/local/studies/genepanel_test_study/meta_clinical_samples.txt
  end-to-end-test/local/studies/genepanel_test_study/meta_cna_discrete.txt
  end-to-end-test/local/studies/genepanel_test_study/meta_cna_hg19_seg.txt
  end-to-end-test/local/studies/genepanel_test_study/meta_gene_panel_matrix.txt
  end-to-end-test/local/studies/genepanel_test_study/meta_mutations_extended.txt
  end-to-end-test/local/studies/genepanel_test_study/meta_study.txt
  end-to-end-test/local/studies/minimal_study/data_samples.txt
  end-to-end-test/local/studies/minimal_study/meta_samples.txt
  end-to-end-test/local/studies/minimal_study/meta_study.txt
  end-to-end-test/shared/specUtils.js
  env/custom.sh
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/SampleManager.tsx
  src/pages/patientView/copyNumberAlterations/CopyNumberTableWrapper.spec.tsx
  src/pages/patientView/copyNumberAlterations/CopyNumberTableWrapper.tsx
  src/pages/patientView/genomicOverview/GenomicOverview.spec.tsx
  src/pages/patientView/genomicOverview/GenomicOverview.tsx
  src/pages/patientView/genomicOverview/Tracks.tsx
  src/pages/patientView/mutation/PatientViewMutationTable.spec.tsx
  src/pages/patientView/mutation/PatientViewMutationTable.tsx
  src/pages/patientView/mutation/column/AlleleFreqColumnFormatter.tsx
  src/pages/patientView/mutation/column/TumorColumnFormatter.spec.tsx
  src/pages/patientView/mutation/column/TumorColumnFormatter.tsx
  src/pages/patientView/patientHeader/PatientHeader.tsx
  src/pages/patientView/patientHeader/SampleInline.tsx
  src/pages/patientView/patientHeader/styles.scss
  src/pages/patientView/sampleManager.spec.tsx
  src/pages/patientView/timeline/Timeline.tsx
  src/pages/patientView/trialMatch/TrialMatchTable.tsx
  src/rootImages/circle_question_mark.png
  src/rootImages/question-mark.png
  src/shared/api/generated/CBioPortalAPI-docs.json
  src/shared/api/generated/CBioPortalAPIInternal-docs.json
  src/shared/components/mutationTable/column/GeneColumnFormatter.tsx
  src/shared/components/sampleLabel/SampleLabel.tsx
  src/shared/components/sampleLabel/SampleLabelNotProfiled.tsx
  src/shared/lib/StoreUtils.spec.ts
  src/shared/lib/StoreUtils.ts
Labels: RFC45, feature, hyve

#2820 Adjusted buttons in Oncoprint controls
  end-to-end-test/remote/screenshots/reference/msk_impact_2017_query_stk11:homdel_mut_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/msk_impact_2017_with_alk_and_sos1_-_sos1_should_be_not_sequenced_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/msk_impact_2017_with_sos1_-_sos1_should_be_not_sequenced_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/msk_impact_2017_with_sos1_with_cna_profile_-_sos1_should_not_be_sequenced_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/multiple_tracks_with_same_gene_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/profiled_in_tracks_in_a_combined_study_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/profiled_in_tracks_in_msk_impact_with_3_not_profiled_genes_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/profiled_in_tracks_in_multiple_study_with_sos1_element_chrome_1600x1000.png
  src/shared/components/oncoprint/controls/OncoprintControls.tsx
  src/shared/components/oncoprint/controls/styles.scss
Labels: enhancement, hyve, results.oncoprint

#2811 SV: remember custom bins and log scale in user preference
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/StudyViewUtils.tsx
Labels: DO NOT MERGE

#2717 Gene coverage filter in Patient View mutation and CNA tables
  end-to-end-test/local/specs/core/patientview.spec.js
  end-to-end-test/remote/screenshots/reference/patient_view_with_0_mutations_msk_impact_2017_p-0000053-t01-im3_element_chrome_1600x1000.png
  end-to-end-test/shared/specUtils.js
  src/pages/patientView/PatientViewPage.spec.tsx
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/PatientViewPageUtils.spec.tsx
  src/pages/patientView/PatientViewPageUtils.tsx
  src/pages/patientView/clinicalInformation/PatientViewPageStore.spec.ts
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
  src/pages/patientView/copyNumberAlterations/CopyNumberTableWrapper.spec.tsx
  src/pages/patientView/copyNumberAlterations/CopyNumberTableWrapper.tsx
  src/pages/patientView/mutation/GeneFilterMenu.spec.tsx
  src/pages/patientView/mutation/GeneFilterMenu.tsx
  src/pages/patientView/mutation/HeaderIconMenu.spec.tsx
  src/pages/patientView/mutation/HeaderIconMenu.tsx
  src/pages/patientView/mutation/PatientViewMutationTable.spec.tsx
  src/pages/patientView/mutation/PatientViewMutationTable.tsx
  src/pages/patientView/mutation/style.scss
  src/shared/components/lazyMobXTable/LazyMobXTable.tsx
Labels: RFC45, feature, hyve

#2830 Add drug icon and trial principal investigator
  src/globalStyles/images/drug.png
  src/pages/patientView/trialMatch/TrialMatchTable.tsx
  src/pages/patientView/trialMatch/TrialMatchTableUtils.ts
  src/pages/patientView/trialMatch/style/trialMatch.module.scss
  src/shared/api/MatchMinerAPI.ts
  src/shared/model/MatchMiner.ts
Labels: ready to review

#2745 Filter mutations in genome tracks based on gene coverage filter in Patient View
  end-to-end-test/local/screenshots/reference/filters_mutation_tracks_based_on_gene_filter_setting_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_gene_panel_icons_behind_mutation_and_cna_genomic_tracks_element_chrome_1600x1000.png
  end-to-end-test/local/specs/core/patientview.screenshot.spec.js
  end-to-end-test/local/specs/core/patientview.spec.js
  end-to-end-test/remote/screenshots/reference/patient_view_with_0_mutations_msk_impact_2017_p-0000053-t01-im3_element_chrome_1600x1000.png
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
  src/pages/patientView/genomicOverview/GenomicOverview.tsx
  src/pages/patientView/genomicOverview/GenomicOverviewUtils.spec.tsx
  src/pages/patientView/genomicOverview/GenomicOverviewUtils.ts
  src/pages/patientView/genomicOverview/Tracks.tsx
  src/pages/patientView/genomicOverview/tracksHelper.ts
Labels: RFC45, hyve

#2829 Fix duplicate age issue
  src/pages/patientView/trialMatch/TrialMatchTable.tsx
  src/pages/patientView/trialMatch/TrialMatchTableUtils.spec.ts
  src/pages/patientView/trialMatch/TrialMatchTableUtils.ts
  src/pages/patientView/trialMatch/style/trialMatch.module.scss
  src/shared/model/MatchMiner.ts
Labels: ready to review

#2839 Fix filter menu disappearing on CNA table
  end-to-end-test/local/specs/core/patientview.spec.js
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/copyNumberAlterations/CopyNumberTableWrapper.tsx
Labels: bug, fixed by pending PR, hyve

#2728 validate sample and patient before render the patient view
  end-to-end-test/remote/screenshots/reference/should_show_error_message_for_400_query_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/should_show_error_message_for_wrong_patient_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/should_show_error_message_for_wrong_sample_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/screenshot.spec.js
  src/AppStore.ts
  src/appShell/App/Container.tsx
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/clinicalInformation/PatientViewPageStore.spec.ts
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
  src/shared/components/errorScreen/ErrorScreen.tsx
  src/shared/lib/errorFormatter.spec.ts
  src/shared/lib/errorFormatter.ts
Labels: ready to review

#2747 Change default setting of gene filters in Patient View from portal.properties
  end-to-end-test/local/specs/core/patientview.spec.js
  src/config/IAppConfig.ts
  src/config/serverConfigDefaults.ts
  src/pages/patientView/clinicalInformation/PatientViewPageStore.spec.ts
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
  src/pages/patientView/clinicalInformation/PatientViewPageStoreUtil.ts
  src/pages/patientView/clinicalInformation/PatientViewPageStoreUtils.spec.ts
Labels: DO NOT MERGE, RFC45, hyve

#2746 Integrate gene panel information and gene filtering in VAF plot in Patient View
  end-to-end-test/local/screenshots/reference/filters_mutation_tracks_based_on_gene_filter_setting_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/filters_vaf_plot_based_on_gene_filter_setting_when_switching_to_"all_samples"_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/filters_vaf_plot_based_on_gene_filter_setting_when_switching_to_"any_sample"_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_gene_panel_icons_behind_mutation_and_cna_genomic_tracks_element_chrome_1600x1000.png
  end-to-end-test/local/specs/core/patientview.screenshot.spec.js
  end-to-end-test/local/specs/core/patientview.spec.js
  end-to-end-test/local/studies/genepanel_test_study/data_mutations_extended.maf
  src/pages/patientView/genomicOverview/GenomicOverview.tsx
  src/pages/patientView/vafPlot/ThumbnailExpandVAFPlot.tsx
  src/pages/patientView/vafPlot/VAFPlot.tsx
  src/pages/patientView/vafPlot/legacyVAFCode.js
Labels: RFC45, hyve

#2893 Fix long runtimes for e2e-localdb tests
  end-to-end-test/local/runtime-config/db_content_fingerprint.sh
Labels: devops

#2896 Allow setting BACKEND on CircleCI
  end-to-end-test/local/runtime-config/setup_environment.sh
  end-to-end-test/local/screenshots/reference/shows_treatment_profile_heatmap_track_for_treatment_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/shows_treatment_profile_heatmap_track_for_treatment_element_chrome_1600x1000.png
  env/custom.sh
Labels: test

#2884 Allow user to customize x-axis (months survival) in survival plot
  end-to-end-test/remote/screenshots/reference/filter_study_from_url_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_survival_tab_exclude_overlapping_samples_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_survival_tab_include_overlapping_samples_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_survival_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_survival_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/when_quickly_adding_charts,_each_chart_should_get_proper_data._element_chrome_1600x1000.png
  src/pages/resultsView/survival/SurvivalChart.tsx
  src/pages/resultsView/survival/styles.module.scss
  src/pages/resultsView/survival/styles.scss
  src/pages/studyView/charts/ChartContainer.tsx
Labels: feature

#2907 update internal api spec and client
  src/shared/api/generated/CBioPortalAPIInternal-docs.json
  src/shared/api/generated/CBioPortalAPIInternal.ts
Labels: chore
