Repository cBioPortal/cbioportal-frontend, pull requests merged in 2019-06, with the labels that each got.

#2389 Bar chart title alignment
  src/pages/resultsView/enrichments/GeneBarPlot.tsx
  src/pages/resultsView/enrichments/frequencyPlotStyles.module.scss
Labels: ready to review

#2388 remove survival charts from study view
  end-to-end-tests/screenshots/reference/filter_study_from_url_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/when_quickly_adding_charts,_each_chart_should_get_proper_data._element_chrome_1600x1000.png
  src/pages/studyView/StudyViewPageStore.ts
Labels: ready to review

#2417 Gene bar chart align left 15px to prevent overlap
  end-to-end-tests/screenshots/reference/no_session_enrichments_tab_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/session_enrichments_tab_element_chrome_1600x1000.png
  src/pages/resultsView/enrichments/GeneBarPlot.tsx
Labels: ready to review

#2345 add information in survival tab titles
  end-to-end-tests/screenshots/reference/group_comparison_page_survival_tab_exclude_overlapping_samples_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/group_comparison_page_survival_tab_include_overlapping_samples_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/no_session_survival_tab_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/session_survival_tab_element_chrome_1600x1000.png
  src/pages/groupComparison/GroupComparisonStore.ts
  src/pages/groupComparison/Survival.tsx
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/survival/SurvivalDescriptionTable.tsx
  src/pages/resultsView/survival/SurvivalTab.tsx
Labels: ready to review

#2426 fix download
  src/shared/components/downloadControls/DownloadControls.tsx
Labels: ready to review

#2435 Add study tags in the frontend
  src/shared/components/studyTagsTooltip/StudyTagsTooltip.tsx
Labels: bug, feature

#2438 change mrna/protein table header
  end-to-end-tests/screenshots/reference/group_comparison_page_mrna_enrichments_tab_two_groups_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/group_comparison_page_protein_enrichments_tab_two_groups_element_chrome_1600x1000.png
  src/pages/resultsView/enrichments/ExpressionEnrichmentsTable.tsx
Labels: ready to review

#2315 changing warning message for overlapping studies
  src/shared/components/query/studyList/StudyList.tsx
Labels: ready to review

#2359 New default cancer summary
  end-to-end-tests/screenshots/reference/group_by_detailed_type_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/handles_change_to_absolute_value_yaxis_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/handles_change_to_alteration_threshold_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/handles_change_to_sample_total_threshold_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/handles_change_to_sort_of_xaxis_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/no_session_cancer_type_summary_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/session_cancer_type_summary_element_chrome_1600x1000.png
  src/pages/resultsView/cancerSummary/CancerSummaryContent.tsx
  src/pages/resultsView/cancerSummary/styles.scss
Labels: ready to review

#2442 add tooltip for Co-occurrence Pattern column
  src/pages/resultsView/enrichments/AlterationEnrichmentsContainer.tsx
Labels: ready to review

#2447 show first column header when show table in the tooltip
  src/pages/studyView/charts/pieChart/PieChart.tsx
Labels: ready to review

#2109 Filtering MutatedGenes/CNA Genes tables with cancer gene list
  end-to-end-tests/screenshots/reference/filter_study_from_url_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/non_cancer_gene_should_show_up_when_the_cancer_gene_filter_is_disabled_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/the_cancer_gene_filter_should_remove_non_cancer_gene_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/when_quickly_adding_charts,_each_chart_should_get_proper_data._element_chrome_1600x1000.png
  end-to-end-tests/specs/core/studyview.spec.js
  end-to-end-tests/specs/specUtils.js
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/TableUtils.tsx
  src/pages/studyView/charts/ChartContainer.tsx
  src/pages/studyView/oncokb/OncoKBUtils.tsx
  src/pages/studyView/table/CNAGenesTable.tsx
  src/pages/studyView/table/ClinicalTable.tsx
  src/pages/studyView/table/GeneCell.tsx
  src/pages/studyView/table/MutatedGenesTable.tsx
  src/pages/studyView/table/tables.module.scss
  src/pages/studyView/tabs/SummaryTab.tsx
  src/shared/lib/Colors.ts
Labels: ready to review

#2288 update mutex tab(exclude unprofiled samples)
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/ResultsViewPageStoreUtils.spec.ts
  src/pages/resultsView/ResultsViewPageStoreUtils.ts
  src/pages/resultsView/mutualExclusivity/MutualExclusivityTab.tsx
  src/pages/resultsView/mutualExclusivity/MutualExclusivityUtil.spec.tsx
  src/pages/resultsView/mutualExclusivity/MutualExclusivityUtil.tsx
  src/pages/staticPages/tools/oncoprinter/OncoprinterStore.ts
Labels: ready to review

#2437 Mask out zero areas in the overlap venn diagram
  src/pages/groupComparison/VennSimple.tsx
Labels: DO NOT MERGE, needs tests

#2422 e2e venn diagram
  end-to-end-tests/screenshots/reference/group_comparison_page_overlap_tab_disjoint_venn_diagram_view_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/group_comparison_page_overlap_tab_disjoint_venn_diagram_view_with_a_group_selected_view_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/group_comparison_page_overlap_tab_venn_diagram_view_with_overlap_and_session_selected_view_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/group_comparison_page_overlap_tab_venn_diagram_view_with_overlap_deselect_active_group_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/group_comparison_page_overlap_tab_venn_diagram_with_overlap_view_element_chrome_1600x1000.png
  end-to-end-tests/specs/core/groupComparison.spec.js
  end-to-end-tests/specs/specUtils.js
  src/globalStyles/e2etest.scss
  src/pages/groupComparison/CreateGroupFromOverlap.tsx
  src/pages/groupComparison/VennSimple.tsx
Labels: ready to review

#2495 fix id not found error
  src/shared/components/query/QueryStore.ts
Labels: ready to review

#2497 override Arial with FreeSans when download pdf
  src/shared/lib/svgToPdfDownload.ts
  src/shared/theme/cBioPoralTheme.ts
Labels: ready to review

#2236 Always show virtual study category in query page
  src/shared/components/query/CancerStudyTreeData.ts
  src/shared/components/query/QueryStore.ts
  src/shared/components/query/StudyListLogic.ts
  src/shared/components/query/studyList/StudyList.tsx
  src/shared/components/rightbar/RightBar.tsx
Labels: ready to review
