Repository cBioPortal/cbioportal-frontend, pull requests merged in 2019-04, with the labels that each got.

#2147 fix mutation plot cutoff labels (issue #5844)
  end-to-end-tests/screenshots/reference/filter_study_from_url_using_simple_filter_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/study_view_laml_tcga_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/the_msi_score_should_use_the_custom_bins,_then_the_msi_score_column_should_be_added_in_the_clinical_data_tab_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/when_quickly_adding_charts,_each_chart_should_get_proper_data._element_chrome_1600x1000.png
  src/pages/studyView/charts/barChart/BarChart.tsx
  src/shared/lib/wrapText.ts
Labels: DO NOT MERGE

#2196 combine amp and homdel q value calculation
  src/pages/groupComparison/GroupComparisonStore.ts
Labels: ready to review

#2189 enter key can submit the new group
  src/pages/groupComparison/comparisonGroupManager/ComparisonGroupManager.tsx
Labels: ready to review

#2194 add gene limit:100
  end-to-end-tests/specs/results.spec.js
  src/config/IAppConfig.ts
  src/config/serverConfigDefaults.ts
  src/globalStyles/global.scss
  src/pages/resultsView/ResultsViewPage.tsx
  src/shared/components/query/GeneSymbolValidator.tsx
  src/shared/components/query/QueryStore.ts
Labels: ready to review

#2203 change column title from N to Normal
  src/shared/components/mutationTable/MutationTable.tsx
Labels: ready to review

#2209 redirect /tutorials.jsp
  src/routes.jsx
Labels: ready to review

#2188 Update karma and webpack config to support IDE debugging
  karma.conf.js
  package.json
Labels: feature, hyve, rc

#2219 Add UpSet plot
  src/pages/groupComparison/Overlap.tsx
  src/pages/groupComparison/OverlapUtils.tsx
  src/pages/groupComparison/UpSet.tsx
  src/pages/groupComparison/UpSetUtils.spec.ts
  src/pages/groupComparison/UpSetUtils.tsx
Labels: ready to review

#2217 show query form when URL contains invalid query
  src/pages/resultsView/ResultsViewPage.tsx
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/querySummary/QuerySummary.tsx
Labels: ready to review

#2224 Break the word when no space in the description
  src/pages/studyView/studyPageHeader/styles.module.scss
Labels: ready to review

#2225 Group comparison fixes
  src/pages/groupComparison/ClinicalData.tsx
  src/pages/groupComparison/ClinicalDataEnrichmentsTable.tsx
  src/pages/groupComparison/GroupComparisonPage.tsx
  src/pages/groupComparison/GroupComparisonStore.ts
  src/pages/groupComparison/GroupComparisonUtils.tsx
  src/shared/components/plots/MultipleCategoryBarPlot.tsx
Labels: ready to review

#2228 redirect the login.jsp to the blank page
  src/appBootstrapper.jsx
  src/shared/lib/openSocialAuthWindow.ts
Labels: ready to review

#2244 Split e2e tests genome nexus on circleci
  .circleci/config.yml
  end-to-end-tests/specs/config.spec.js
  end-to-end-tests/specs/core/coexpression.screenshot.spec.js
  end-to-end-tests/specs/core/expressionTab.spec.js
  end-to-end-tests/specs/core/home.spec.js
  end-to-end-tests/specs/core/mutationTable.spec.js
  end-to-end-tests/specs/core/mutationsTab.spec.js
  end-to-end-tests/specs/core/oncoprint.screenshot.spec.js
  end-to-end-tests/specs/core/oncoprint.spec.js
  end-to-end-tests/specs/core/oncoprinter.screenshot.spec.js
  end-to-end-tests/specs/core/patient.logic.spec.js
  end-to-end-tests/specs/core/plots.screenshot.spec.js
  end-to-end-tests/specs/core/results.logic.spec.js
  end-to-end-tests/specs/core/results.spec.js
  end-to-end-tests/specs/core/screenshot.spec.js
  end-to-end-tests/specs/core/studyview.spec.js
  end-to-end-tests/specs/genome-nexus/data/hla_a_test_mutation_mapper_tool.txt
  end-to-end-tests/specs/genome-nexus/mutationMapperTool.spec.js
Labels: ready to review

#2074 Fix the properties to set defaults for Oncoprint mutation annotations
  src/config/IAppConfig.ts
  src/config/serverConfigDefaults.ts
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/ResultsViewPageStoreUtils.spec.ts
  src/pages/resultsView/ResultsViewPageStoreUtils.ts
  src/shared/components/oncoprint/ResultsViewOncoprint.tsx
Labels: bug

#2246 Correctly indicate CNA data samples counts
  end-to-end-tests/screenshots/reference/filter_study_from_url_using_simple_filter_element_chrome_1600x1000.png
  src/pages/studyView/tabs/SummaryTab.tsx
Labels: ready to review

#2253 Sv fixes
  src/pages/studyView/StudyViewPageStore.ts
Labels: ready to review

#2255 SV: cleanup and issue fixes
  src/pages/studyView/StudyViewPage.tsx
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/studyPageHeader/StudyPageHeader.tsx
  src/pages/studyView/studyPageHeader/rightPanel/RightPanel.tsx
Labels: ready to review

#2242 Update annotation sorting method to the following
  end-to-end-tests/screenshots/reference/patient_view_lgg_ucsf_2014_p04_element_chrome_1600x1000.png
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
  src/pages/patientView/copyNumberAlterations/CopyNumberTableWrapper.spec.tsx
  src/pages/patientView/copyNumberAlterations/CopyNumberTableWrapper.tsx
  src/pages/patientView/copyNumberAlterations/column/AnnotationColumnFormatter.tsx
  src/pages/patientView/mutation/PatientViewMutationTable.spec.tsx
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/mutation/ResultsViewMutationMapper.tsx
  src/pages/resultsView/mutation/ResultsViewMutationMapperStore.ts
  src/pages/staticPages/tools/mutationMapper/MutationMapperToolStore.ts
  src/pages/staticPages/tools/mutationMapper/StandaloneMutationMapper.tsx
  src/pages/staticPages/tools/oncoprinter/OncoprinterStore.ts
  src/shared/components/annotation/OncoKbCard.tsx
  src/shared/components/annotation/oncokb/OncoKB.tsx
  src/shared/components/annotation/oncokb/OncoKBSuggestAnnotationLinkout.tsx
  src/shared/components/annotation/oncokb/OncoKbCard.tsx
  src/shared/components/annotation/oncokb/OncoKbTooltip.tsx
  src/shared/components/annotation/styles/oncokb/oncokb.scss
  src/shared/components/mutationMapper/MutationMapperStore.ts
  src/shared/components/mutationTable/MutationTable.tsx
  src/shared/components/mutationTable/column/AnnotationColumnFormatter.tsx
  src/shared/lib/OncoKbUtils.ts
  src/shared/lib/StoreUtils.ts
  src/shared/model/OncoKB.ts
Labels: ready to review

#2254 exclude overlapping samples and patients by default for survival and clinical tab
  src/pages/groupComparison/ClinicalData.tsx
  src/pages/groupComparison/GroupComparisonStore.ts
  src/pages/groupComparison/GroupComparisonUtils.tsx
  src/pages/groupComparison/Survival.tsx
Labels: ready to review

#2179 change routing for study view page
  src/pages/studyView/StudyViewPage.tsx
  src/pages/studyView/StudyViewUtils.spec.ts
  src/pages/studyView/StudyViewUtils.tsx
  src/routes.jsx
Labels: ready to review
