Repository cBioPortal/cbioportal-frontend, pull requests merged in 2019-12, with the labels that each got.

#2908 Update clinical timeline version to v0.0.19
  package.json
  yarn.lock
Labels: style tweak

#2741 Gene panel column data in patient view download
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/copyNumberAlterations/CopyNumberTableWrapper.tsx
  src/pages/patientView/mutation/PatientViewMutationTable.tsx
  src/shared/components/mutationTable/MutationTable.tsx
  src/shared/components/mutationTable/column/PanelColumnFormatter.spec.tsx
  src/shared/components/mutationTable/column/PanelColumnFormatter.tsx
Labels: RFC45, hyve

#2905 plots tab - make quickplots buttons choose same gene for vertical axis
  src/pages/resultsView/plots/PlotsTab.tsx
  src/pages/resultsView/plots/QuickPlots.spec.ts
  src/pages/resultsView/plots/QuickPlots.ts
Labels: bug

#2782 Gene Panel Modal in Patient View
  end-to-end-test/local/specs/core/patientview.spec.js
  src/pages/patientView/PatientViewGenePanelModal/GenesList.spec.tsx
  src/pages/patientView/PatientViewGenePanelModal/GenesList.tsx
  src/pages/patientView/PatientViewGenePanelModal/PatientViewGenePanelModal.tsx
  src/pages/patientView/PatientViewGenePanelModal/styles.module.scss
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/SampleManager.tsx
  src/pages/patientView/clinicalInformation/ClinicalInformationPatientTable.tsx
  src/pages/patientView/copyNumberAlterations/CopyNumberTableWrapper.tsx
  src/pages/patientView/genomicOverview/GenomicOverview.tsx
  src/pages/patientView/genomicOverview/Tracks.tsx
  src/pages/patientView/genomicOverview/tracksHelper.ts
  src/pages/patientView/mutation/PatientViewMutationTable.tsx
  src/pages/patientView/mutation/column/TumorColumnFormatter.tsx
  src/pages/patientView/patientHeader/SampleInline.tsx
  src/pages/studyView/TableUtils.tsx
  src/pages/studyView/table/GenePanelModal.tsx
  src/pages/studyView/table/GeneTable.tsx
  src/pages/studyView/table/StudyViewGenePanelModal.tsx
  src/shared/components/GenePanelModal/GenePanelModal.spec.tsx
  src/shared/components/GenePanelModal/GenePanelModal.tsx
  src/shared/components/copyDownloadControls/CopyDownloadButtons.tsx
  src/shared/components/copyDownloadControls/SimpleCopyDownloadControls.tsx
  src/shared/components/mutationTable/column/PanelColumnFormatter.spec.tsx
  src/shared/components/mutationTable/column/PanelColumnFormatter.tsx
  src/shared/components/sampleLabel/SampleLabelNotProfiled.tsx
Labels: RFC45, feature

#2726 Url wrapper
  .circleci/config.yml
  end-to-end-test/remote/screenshots/reference/acc_tcga_with_clinical_and_heatmap_tracks_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/blca_tcga_with_clinical_and_heatmap_tracks_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/coadread_tcga_pub_with_clinical_and_heatmap_tracks_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/oncoprint.spec.js
  src/appShell/App/Container.tsx
  src/config/serverConfigDefaults.ts
  src/pages/groupComparison/GroupComparisonPage.tsx
  src/pages/groupComparison/GroupComparisonStore.ts
  src/pages/groupComparison/GroupComparisonURLWrapper.ts
  src/pages/groupComparison/Survival.tsx
  src/pages/home/HomePage.tsx
  src/pages/patientView/PatientViewPage.spec.tsx
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/PatientViewUrlWrapper.ts
  src/pages/resultsView/ResultsViewPage.tsx
  src/pages/resultsView/ResultsViewPageHelpers.spec.ts
  src/pages/resultsView/ResultsViewPageHelpers.ts
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/ResultsViewQuery.ts
  src/pages/resultsView/ResultsViewURLWrapper.ts
  src/pages/resultsView/cancerSummary/CancerSummaryChart.tsx
  src/pages/resultsView/download/DownloadTab.tsx
  src/pages/resultsView/enrichments/AddCheckedGenes.tsx
  src/pages/resultsView/querySummary/QuerySummary.tsx
  src/pages/resultsView/querySummary/ShareUI.tsx
  src/pages/resultsView/survival/SurvivalChart.tsx
  src/pages/resultsView/survival/styles.scss
  src/pages/studyView/StudyViewPageStore.ts
  src/routes.jsx
  src/shared/cache/TreatmentCache.ts
  src/shared/components/oncoprint/DeltaUtils.ts
  src/shared/components/oncoprint/Oncoprint.tsx
  src/shared/components/oncoprint/OncoprintUtils.ts
  src/shared/components/oncoprint/ResultsViewOncoprint.spec.tsx
  src/shared/components/oncoprint/ResultsViewOncoprint.tsx
  src/shared/components/query/QueryStore.ts
  src/shared/lib/ExtendedRouterStore.spec.ts
  src/shared/lib/ExtendedRouterStore.ts
  src/shared/lib/URLWrapper.spec.ts
  src/shared/lib/URLWrapper.ts
  src/shared/lib/createQueryStore.ts
  src/shared/lib/redirectHelpers.ts
  src/shared/lib/setWindowVariable.ts
Labels: DO NOT MERGE

#2914 Oncoprint Toolbar Improvements
  end-to-end-test/remote/screenshots/reference/acc_tcga_with_clinical_and_heatmap_tracks_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/blca_tcga_with_clinical_and_heatmap_tracks_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/brca_tcga_pub_with_kras_nras_braf_and_methylation_heatmap_tracks_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/coadread_tcga_pub_with_clinical_and_heatmap_tracks_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/hcc_inserm_fr_2015_with_genes_including_tert_-_it_should_show_orange_promoter_mutations_in_tert_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/msk_impact_2017_query_stk11:homdel_mut_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/msk_impact_2017_with_alk_and_sos1_-_sos1_should_be_not_sequenced_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/msk_impact_2017_with_sos1_-_sos1_should_be_not_sequenced_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/msk_impact_2017_with_sos1_with_cna_profile_-_sos1_should_not_be_sequenced_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/multiple_tracks_with_same_gene_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/profiled_in_tracks_in_a_combined_study_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/profiled_in_tracks_in_msk_impact_with_3_not_profiled_genes_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/profiled_in_tracks_in_multiple_study_with_sos1_element_chrome_1600x1000.png
  src/pages/resultsView/oncoprint/AddClinicalTracks.tsx
  src/pages/resultsView/oncoprint/OncoprintDropdownCount.tsx
  src/pages/resultsView/styles.scss
  src/shared/components/oncoprint/controls/CustomDropdown.tsx
  src/shared/components/oncoprint/controls/OncoprintControls.tsx
Labels: feature

#2920 Display genes in one column on copy/download
  src/pages/patientView/PatientViewGenePanelModal/GenesList.tsx
Labels: enhancement

#2921 Fix handling of data_priority = profileFilter on submission/modificat…
  src/pages/resultsView/ResultsViewURLWrapper.ts
  src/shared/components/query/QueryStore.ts
  src/shared/components/query/QueryStoreUtils.ts
Labels: bug

#2924 Gene query limit supports case sets
  src/shared/components/query/GeneSetSelector.tsx
  src/shared/components/query/GeneSymbolValidator.tsx
  src/shared/components/query/QueryStore.ts
Labels: bug

#2927 Fixed Oncoprint controls button alignment
  end-to-end-test/remote/screenshots/reference/hcc_inserm_fr_2015_with_genes_including_tert_-_it_should_show_orange_promoter_mutations_in_tert_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/msk_impact_2017_query_stk11:homdel_mut_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/msk_impact_2017_with_alk_and_sos1_-_sos1_should_be_not_sequenced_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/msk_impact_2017_with_sos1_-_sos1_should_be_not_sequenced_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/msk_impact_2017_with_sos1_with_cna_profile_-_sos1_should_not_be_sequenced_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/profiled_in_tracks_in_msk_impact_with_3_not_profiled_genes_element_chrome_1600x1000.png
  src/shared/components/oncoprint/controls/OncoprintControls.tsx
Labels: style tweak

#2915 patient view genomic overview tracks - restyle gene panel icon
  end-to-end-test/local/screenshots/reference/filters_mutation_tracks_based_on_gene_filter_setting_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_gene_panel_icons_behind_mutation_and_cna_genomic_tracks_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_lgg_ucsf_2014_p04_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_with_0_mutations_msk_impact_2017_p-0000053-t01-im3_element_chrome_1600x1000.png
  src/pages/patientView/genomicOverview/tracksHelper.ts
Labels: enhancement

#2922 improve typescript checking for URLWrapper
  src/pages/groupComparison/GroupComparisonURLWrapper.ts
  src/pages/patientView/PatientViewUrlWrapper.ts
  src/pages/resultsView/ResultsViewURLWrapper.ts
  src/shared/lib/URLWrapper.ts
Labels: chore

#2931 Upgraded to react-mutation-mapper 0.3.6
  end-to-end-test/remote/screenshots/reference/no_session_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_mutation_tab_element_chrome_1600x1000.png
  package.json
  yarn.lock
Labels: style tweak

#2939 Study view: Fix scatter plot reset selected filter
  src/pages/studyView/tabs/SummaryTab.tsx
Labels: ready to review

#2891 Routing Improvements
  src/pages/groupComparison/GroupComparisonPage.tsx
  src/pages/groupComparison/GroupComparisonStore.ts
  src/pages/groupComparison/GroupComparisonTabs.ts
  src/pages/groupComparison/GroupComparisonURLWrapper.ts
  src/pages/groupComparison/GroupComparisonUtils.tsx
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/PatientViewPageTabs.ts
  src/pages/resultsView/ErrorPage.tsx
  src/pages/studyView/StudyViewPage.tsx
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/StudyViewPageTabs.ts
  src/pages/studyView/StudyViewUtils.spec.ts
  src/pages/studyView/StudyViewUtils.tsx
  src/pages/studyView/addChartButton/AddChartButton.tsx
  src/pages/studyView/tabs/CNSegments.tsx
  src/routes.jsx
  src/shared/components/pageNotFound/PageNotFound.tsx
Labels: enhancement

#2947 In patient view timeline, treatment data should be split three levels…
  end-to-end-test/remote/screenshots/reference/patient_view_lgg_ucsf_2014_p04_element_chrome_1600x1000.png
  src/pages/patientView/timeline/legacy.js
Labels: bug

#2960 Restore loading animation for study summary fetch on results page
  src/pages/resultsView/ResultsViewPage.tsx
Labels: style tweak

#2936 Give option to list unselected cases in the Custom Selection component
  src/pages/studyView/addChartButton/customCaseSelection/CustomCaseSelection.tsx
  src/pages/studyView/addChartButton/customCaseSelection/styles.module.scss
Labels: feature, study view

#2911 update svg2pdf to custom version (fix gradient shows up as solid block)
  package.json
  yarn.lock
Labels: bug
