Repository cBioPortal/cbioportal-frontend, pull requests merged in 2019-01, with the labels that each got.

#1834 use log2 odds ratio in Mutex
  end-to-end-tests/screenshots/reference/no_session_mutex_tab_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/session_mutex_tab_element_chrome_1600x1000.png
  src/pages/resultsView/mutualExclusivity/MutualExclusivityTable.tsx
  src/pages/resultsView/mutualExclusivity/MutualExclusivityUtil.spec.tsx
  src/pages/resultsView/mutualExclusivity/MutualExclusivityUtil.tsx
Labels: ready to review

#1926 change the links to list
  src/pages/studyView/studyPageHeader/studySummary/StudySummary.tsx
  src/pages/studyView/studyPageHeader/styles.module.scss
Labels: ready to review

#1923 Survival tab from group comparison
  src/pages/groupComparison/GroupComparisonPage.tsx
  src/pages/groupComparison/GroupComparisonStore.ts
  src/pages/groupComparison/GroupComparisonUtils.ts
  src/pages/groupComparison/MutationEnrichments.tsx
  src/pages/groupComparison/Survival.tsx
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/survival/SurvivalChart.tsx
  src/pages/resultsView/survival/SurvivalTab.tsx
  src/pages/resultsView/survival/SurvivalUtil.tsx
  src/pages/studyView/charts/ChartContainer.tsx
  src/pages/studyView/charts/survival/StudyViewSurvivalUtils.ts
Labels: DO NOT MERGE

#1938 search by study id in the home page
  src/shared/components/query/StudyListLogic.ts
Labels: feature, needs tests

#1930 fix select samples button text
  src/pages/studyView/table/FixedHeaderTable.tsx
Labels: ready to review

#1941 change url for whole slide viewer
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
  src/shared/api/urls.ts
Labels: ready to review

#1940 Group comparison - overlap tab
  package-lock.json
  package.json
  src/pages/groupComparison/GroupComparisonPage.tsx
  src/pages/groupComparison/GroupComparisonStore.ts
  src/pages/groupComparison/GroupComparisonUtils.spec.ts
  src/pages/groupComparison/GroupComparisonUtils.ts
  src/pages/groupComparison/Overlap.tsx
  src/pages/groupComparison/OverlapStackedBar.tsx
  src/pages/groupComparison/OverlapVenn.tsx
  src/pages/resultsView/cancerSummary/CancerSummaryChart.tsx
Labels: DO NOT MERGE

#1959 Fix two serious bugs in plots stacked bar
  end-to-end-tests/screenshots/reference/plots_tab_clinical_vs_clinical_horizontal_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/plots_tab_clinical_vs_clinical_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/plots_tab_copy_number_vs_clinical_horizontal_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/plots_tab_copy_number_vs_clinical_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/plots_tab_mutations_vs_clinical_horizontal_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/plots_tab_mutations_vs_clinical_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/plots_tab_mutations_wildtype_mode_vs_clinical_horizontal_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/plots_tab_mutations_wildtype_mode_vs_clinical_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-tests/specs/screenshot.spec.js
  package.json
  src/pages/resultsView/plots/PlotsTab.tsx
  src/shared/components/plots/StackedBarPlot.tsx
  src/shared/components/plots/StackedBarPlotUtils.spec.ts
  src/shared/components/plots/StackedBarPlotUtils.ts
  typings/missing.d.ts
  yarn.lock
Labels: bug, critical, needs-testing-from-product-team

#1950 change text for mrna and protein
  end-to-end-tests/screenshots/reference/acc_tcga_with_clinical_and_heatmap_tracks_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/blca_tcga_with_clinical_and_heatmap_tracks_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/coadread_tcga_pub_with_clinical_and_heatmap_tracks_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/oncoprinter_example_data,_dont_color_by_driver_vs_vus_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/oncoprinter_example_data,_dont_color_by_mutation_type_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/oncoprinter_example_data,_hide_vus_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/oncoprinter_example_data,_start_by_set_gene_order,_then_set_sample_order_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/oncoprinter_example_data,_start_by_set_sample_order,_then_set_gene_order_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/oncoprinter_example_data,_then_set_gene_order,_including_all_genes_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/oncoprinter_example_data,_then_set_gene_order,_not_including_all_genes_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/oncoprinter_example_data,_then_set_sample_order,_including_all_samples_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/oncoprinter_example_data_element_chrome_1600x1000.png
  src/pages/resultsView/cancerSummary/CancerSummaryChart.spec.tsx
  src/pages/resultsView/cancerSummary/CancerSummaryContent.tsx
  src/pages/staticPages/tools/oncoprinter/OncoprinterTool.tsx
  src/shared/components/oncoprint/geneticrules.ts
  src/shared/components/oncoprint/tabularDownload.ts
Labels: ready to review

#1847 Added basic Hotspots and OncoKB tracks for MutationMapper
  end-to-end-tests/screenshots/reference/no_session_mutation_tab_element_chrome_1600x1000.png
  end-to-end-tests/screenshots/reference/session_mutation_tab_element_chrome_1600x1000.png
  end-to-end-tests/specs/results.spec.js
  src/shared/components/HitZone.tsx
  src/shared/components/annotation/CancerHotspots.tsx
  src/shared/components/annotation/Civic.tsx
  src/shared/components/annotation/OncoKB.tsx
  src/shared/components/annotation/OncoKbFeedback.tsx
  src/shared/components/annotation/StatusHelpers.tsx
  src/shared/components/annotation/images/oncogenic-only.svg
  src/shared/components/lazyMobXTable/LazyMobXTable.tsx
  src/shared/components/lollipopMutationPlot/LollipopMutationPlot.tsx
  src/shared/components/lollipopMutationPlot/LollipopMutationPlotControls.tsx
  src/shared/components/lollipopMutationPlot/LollipopPlot.tsx
  src/shared/components/lollipopMutationPlot/LollipopPlotNoTooltip.tsx
  src/shared/components/lollipopMutationPlot/lollipopMutationPlotControls.scss
  src/shared/components/mutationMapper/MutationMapper.tsx
  src/shared/components/mutationMapper/MutationMapperDataStore.ts
  src/shared/components/mutationMapper/MutationMapperStore.ts
  src/shared/components/mutationTable/column/AnnotationColumnFormatter.tsx
  src/shared/components/proteinChainPanel/ProteinChainPanel.tsx
  src/shared/components/tracks/HotspotTrack.tsx
  src/shared/components/tracks/OncoKbSummaryTable.tsx
  src/shared/components/tracks/OncoKbTrack.tsx
  src/shared/components/tracks/OncoKbTrackTooltip.tsx
  src/shared/components/tracks/Track.tsx
  src/shared/components/tracks/TrackCircle.tsx
  src/shared/components/tracks/TrackPanel.tsx
  src/shared/components/tracks/TrackSelector.tsx
  src/shared/components/tracks/trackStyles.module.scss
  src/shared/lib/AnnotationUtils.ts
  src/shared/lib/CancerHotspotsUtils.spec.ts
  src/shared/lib/CancerHotspotsUtils.ts
  src/shared/lib/MutationUtils.ts
  src/shared/lib/OncoKbUtils.spec.tsx
  src/shared/lib/OncoKbUtils.ts
  src/shared/lib/SvgComponentUtils.ts
Labels: ready to review
