Repository cBioPortal/cbioportal-frontend, pull requests merged in 2019-09, with the labels that each got.

#2660 Download tab (await data at the same time)
  src/pages/resultsView/download/DownloadTab.tsx
Labels: ready to review

#2718 Improve robustness of GSVA feature e2e-localdb tests
  end-to-end-test/local/specs/gsva.spec.js
  src/shared/components/query/GenesetsJsTree.tsx
Labels: enhancement

#2715 Make first action button and related text render early in study view
  src/pages/studyView/StudyViewPage.tsx
  src/pages/studyView/studyPageHeader/ActionButtons.tsx
Labels: study view

#2722 Hide utilities menu when no plot data available
  end-to-end-test/local/specs/core/plotstab.spec.js
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_boxplot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_horizontal_grouped_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_horizontal_percentage_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_horizontal_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_percentage_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_table_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_copy_number_vs_clinical_horizontal_percentage_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_copy_number_vs_clinical_horizontal_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_copy_number_vs_clinical_percentage_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_copy_number_vs_clinical_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_copy_number_vs_clinical_table_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_vs_clinical_horizontal_percentage_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_vs_clinical_horizontal_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_vs_clinical_percentage_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_vs_clinical_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_vs_clinical_table_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_wildtype_mode_vs_clinical_horizontal_percentage_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_wildtype_mode_vs_clinical_horizontal_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_wildtype_mode_vs_clinical_percentage_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_wildtype_mode_vs_clinical_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_wildtype_mode_vs_clinical_table_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_one_box_clinical_vs_clinical_boxplot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_search_case_id_in_clinical_vs_clinical_boxplot_element_chrome_1600x1000.png
  src/pages/resultsView/plots/PlotsTab.tsx
Labels: bug

#2723 should use selectable selected study ids for query submit
  src/shared/components/query/QueryStoreUtils.ts
Labels: ready to review
