Repository cBioPortal/cbioportal-frontend, pull requests merged in 2019-10, with the labels that each got.

#2750 update p-value tooltip
  src/pages/resultsView/enrichments/AlterationEnrichmentsTable.tsx
  src/pages/resultsView/mutualExclusivity/MutualExclusivityTable.tsx
Labels: ready to review

#2743 Update MD5 fingerprint script to use correct docker image
  end-to-end-test/local/runtime-config/db_content_fingerprint.sh
Labels: bug, hyve

#2705 change case set options for virtual study
  src/pages/resultsView/ResultsViewPageStore.ts
  src/shared/components/query/CaseSetSelector.tsx
  src/shared/components/query/CaseSetSelectorUtils.spec.ts
  src/shared/components/query/CaseSetSelectorUtils.ts
  src/shared/components/query/QueryStore.ts
Labels: ready to review

#2679 molecular files download
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/download/DownloadTab.tsx
  src/pages/resultsView/download/DownloadUtils.spec.ts
  src/pages/resultsView/download/DownloadUtils.ts
  src/pages/resultsView/download/styles.module.scss
  src/shared/components/query/QueryContainer.tsx
Labels: ready to review

#2720 Use GeneSelectionBox on Query View
  end-to-end-test/remote/specs/core/home.spec.js
  src/pages/resultsView/enrichments/GeneBarPlot.tsx
  src/pages/studyView/studyPageHeader/rightPanel/RightPanel.tsx
  src/shared/components/GeneSelectionBox/GeneSelectionBox.spec.tsx
  src/shared/components/GeneSelectionBox/GeneSelectionBoxUtils.ts
  src/shared/components/GeneSelectionBox/GeneSymbolValidator.tsx
  src/shared/components/GeneSelectionBox/GeneSymbolValidatorMessage.tsx
  src/shared/components/GeneSelectionBox/OQLTextArea.tsx
  src/shared/components/oncoprint/controls/OncoprintControls.tsx
  src/shared/components/query/GeneSetSelector.tsx
  src/shared/components/query/GeneSymbolValidator.tsx
  src/shared/components/query/GenesetsSelector.tsx
  src/shared/components/query/GenesetsValidator.tsx
  src/shared/components/query/QueryStore.ts
Labels: refactoring

#2763 (download tab) show all molecular profiles by default
  src/pages/resultsView/download/DownloadTab.tsx
  src/pages/resultsView/download/DownloadUtils.ts
  src/pages/resultsView/download/styles.module.scss
Labels: ready to review

#2780 Fix sample navigator error
  src/pages/patientView/copyNumberAlterations/column/AnnotationColumnFormatter.tsx
Labels: ready to review

#2787 Fix warning message for invalid genes
  end-to-end-test/remote/specs/core/results.logic.spec.js
  src/pages/resultsView/querySummary/QuerySummary.tsx
  src/shared/components/query/QueryAndDownloadTabs.tsx
  src/shared/components/query/QueryContainer.tsx
Labels: ready to review

#2663 Fix #4090 tooltip display in segment tracks
  src/pages/patientView/genomicOverview/tracksHelper.ts
Labels: hyve, ready to review

#2744 Adjustments for mouse cBioPortal
  src/pages/patientView/genomicOverview/Tracks.tsx
  src/pages/patientView/genomicOverview/chromosomeSizes.json
  src/pages/patientView/genomicOverview/tracksHelper.ts
  src/pages/studyView/StudyViewPageStore.ts
Labels: DO NOT MERGE, bug

#2799 Fix undefined content shown on the view
  src/pages/patientView/trialMatch/TrialMatchTable.tsx
  src/pages/patientView/trialMatch/TrialMatchTableUtils.spec.ts
  src/pages/patientView/trialMatch/TrialMatchTableUtils.ts
  src/shared/api/MatchMinerAPI.ts
  src/shared/model/MatchMiner.ts
Labels: bug, ready to review

#2685 Implement gene panel API calls in PatientViewStore
  end-to-end-test/local/runtime-config/db_content_fingerprint.sh
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
  src/shared/api/generated/CBioPortalAPIInternal-docs.json
  src/shared/lib/StoreUtils.ts
Labels: RFC45, feature, hyve

#2800 Using Data Access Tokens - Web API DAT subsection redirection
  src/appShell/App/PortalHeader.tsx
  src/pages/staticPages/webAPI/WebAPIPage.tsx
  src/routes.jsx
  src/shared/components/dataAccessTokens/DataAccessTokensDropdown.tsx
Labels: enhancement

#2677 Extend LazyMobXTable to have resizable columns
  end-to-end-test/remote/screenshots/reference/patient_view_lgg_ucsf_2014_p04_element_chrome_1600x1000.png
  package.json
  src/pages/patientView/copyNumberAlterations/CopyNumberTableWrapper.spec.tsx
  src/pages/patientView/copyNumberAlterations/CopyNumberTableWrapper.tsx
  src/pages/patientView/mutation/PatientViewMutationTable.spec.tsx
  src/pages/patientView/mutation/PatientViewMutationTable.tsx
  src/shared/components/lazyMobXTable/LazyMobXTable.spec.tsx
  src/shared/components/lazyMobXTable/LazyMobXTable.tsx
  src/shared/components/lazyMobXTable/styles.scss
  src/shared/components/simpleTable/styles.scss
  typings/missing.d.ts
  yarn.lock
Labels: RFC45, feature, hyve

#2818 Show hidden axis (BoxScatterPlot)
  src/shared/components/plots/BoxScatterPlot.tsx
Labels: ready to review
