Repository cBioPortal/cbioportal-frontend, pull requests merged in 2020-11, with the labels that each got.

#3485 patient view - sample manager always has data on all samples for patient
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/SampleManager.tsx
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
Labels: enhancement

#3480 Skip annotating canonical transcript only for cBioPortal mutations
  packages/cbioportal-utils/src/mutation/MutationAnnotator.ts
  packages/react-mutation-mapper/src/store/DefaultMutationMapperStore.ts
  src/shared/components/mutationMapper/MutationMapperStore.ts
Labels: cl-package

#3492 By default, hide new installation map on homepage
  src/config/serverConfigDefaults.ts
Labels: bug

#3502 Add an e2e test for a virtual study
  end-to-end-test/remote/screenshots/reference/loads_a_virtual_study_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/studyview.spec.js
Labels: chore

#3469 Add OncoKB MSI-H, TMB-H annotation
  packages/react-mutation-mapper/src/component/oncokb/OncoKbCardBody.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbCardTitle.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbCardTreatmentContent.tsx
  packages/react-mutation-mapper/src/component/oncokb/constants.ts
  packages/react-mutation-mapper/src/index.tsx
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
  src/pages/patientView/oncokb/OtherBiomarkerAnnotation.tsx
  src/shared/constants.ts
  src/shared/lib/StoreUtils.ts
Labels: feature, oncokb, ready to review

#3494 Fixed display of column values in downloaded tsv
  src/pages/patientView/copyNumberAlterations/CopyNumberTableWrapper.tsx
  src/shared/components/lazyMobXTable/LazyMobXTable.spec.tsx
  src/shared/components/lazyMobXTable/LazyMobXTable.tsx
Labels: ready to review

#3504 Update some e2e tests broken by data changes
  end-to-end-test/ie11/specs/ie.js
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_render_the_oncoprint_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_lgg_ucsf_2014_p04_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_one_box_clinical_vs_clinical_boxplot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_add_a_mutation_to_line_chart_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_heatmap_hide_labels_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_heatmap_with_two_mutations_selected_from_before_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_hover_a_mutation_with_heatmap_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_hover_a_mutation_with_line_chart_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_initial_view_with_line_chart_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_one_mutation_selected_with_heatmap_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_one_mutation_selected_with_line_chart_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_show_timeline_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_transpose_heatmap_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_uncluster_heatmap_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/genomicEvolution.screenshot.spec.js
  end-to-end-test/remote/specs/core/studyview.spec.js
  end-to-end-test/shared/specUtils.js
Labels: chore

#3510 Update readme with info about chrome driver version on e2e tests
  README.md
Labels: skip-changelog

#3517 Update api docs and screenshots for v3.5.0
  end-to-end-test/remote/screenshots/reference/group_comparison_page_survival_tab_include_overlapping_samples_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_lgg_ucsf_2014_p04_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_heatmap_with_two_mutations_selected_from_before_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_hover_a_mutation_with_heatmap_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_hover_a_mutation_with_line_chart_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_initial_view_with_line_chart_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_one_mutation_selected_with_heatmap_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_one_mutation_selected_with_line_chart_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_show_timeline_element_chrome_1600x1000.png
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal.ts
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPIInternal-docs.json
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPIInternal.ts
Labels: chore
