Repository cBioPortal/cbioportal-frontend, pull requests merged in 2020-03, with the labels that each got.

#3091 Plots Tab: New gene settings when displaying clinical attributes with generic assay types (e.g. treatment response)
  end-to-end-test/local/screenshots/reference/applies_log-scale_in_waterfall_plot_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/removes_sample_stylings_when_selecting_"none"_in_gene_selection_box_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/reverses_order_of_waterfall_plot_data_when_`sort_order`_button_pressed_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/rotates_waterfall_plot_when_swapping_axes_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_`value_>8.00`_in_figure_legend_and_indicates_sub-threshold_data_points_in_plot_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_a_search_indicator_when_sample_search_term_is_entered_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_both_mutation_and_cna_types_in_clinical_attribute_vs_treatment_plot_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_cna_types_in_clinical_attribute_vs_treatment_plot_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_gsva_profile_data_on_horizontal_and_vertical_axes_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_gsva_scores_in_scatterplot_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_mutation_types_in_clinical_attribute_vs_treatment_plot_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_waterfall_plot_when_`ordered_samples`_option_is_selected_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/updates_title_of_watefall_plot_when_selecting_a_new_gene_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/when_option_deselected,_hides_`value_>8.00`_in_figure_legend_and_sub-threshold_data_point_indicators_in_waterfall_plot_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/when_option_deselected,_hides_`value_>8.00`_in_figure_legend_and_sub-threshold_data_points_in_plot_element_chrome_1600x1000.png
  end-to-end-test/local/specs/core/plotstab.spec.js
  end-to-end-test/local/specs/treatment.spec.js
  end-to-end-test/remote/screenshots/reference/coexpression_tab_coadread_tcga_pub_initial_load_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/coexpression_tab_coadread_tcga_pub_loc_scale_x_and_y_mutations_off_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/coexpression_tab_coadread_tcga_pub_log_scale_x_and_y_mutations_on_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/coexpression_tab_coadread_tcga_pub_log_scale_x_and_y_with_regression_line_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/coexpression_tab_coadread_tcga_pub_switch_profiles_+_regression_line_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/coexpression_tab_coadread_tcga_pub_switch_profiles_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/coexpression_tab_coadread_tcga_pub_switch_tabs_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/expression_tab_with_complex_oql_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_plots_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_boxplot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_molecular_boxplot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_molecular_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_copy_number_view_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_log_scale_off_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_molecular_vs_clinical_boxplot,_mutation_search_off_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_molecular_vs_molecular_different_genes_different_profiles_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_molecular_vs_molecular_different_genes_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_molecular_vs_molecular_same_gene_changed_gene_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_molecular_vs_molecular_same_gene_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_molecular_vs_molecular_swapped_axes_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutation_type_view_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_profile_with_duplicates_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_vs_clinical_boxplot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_wild_type_mode_vs_clinical_boxplot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_one_box_clinical_vs_clinical_boxplot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_search_case_id_and_mutation_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_search_case_id_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_search_case_id_in_clinical_vs_clinical_boxplot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_search_mutation_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_plots_tab_element_chrome_1600x1000.png
  src/pages/resultsView/plots/PlotsTab.tsx
  src/pages/resultsView/plots/PlotsTabUtils.spec.ts
  src/pages/resultsView/plots/PlotsTabUtils.tsx
  src/pages/resultsView/plots/styles.scss
  src/shared/components/plots/BoxScatterPlot.tsx
  src/shared/components/plots/ScatterPlot.tsx
  src/shared/components/plots/WaterfallPlot.tsx
Labels: ready to review

#3082 Add variant type column to mutation tables
  src/pages/patientView/mutation/PatientViewMutationTable.tsx
  src/pages/resultsView/mutation/ResultsViewMutationTable.tsx
  src/pages/staticPages/tools/mutationMapper/StandaloneMutationTable.tsx
  src/shared/components/mutationTable/MutationTable.tsx
  src/shared/components/mutationTable/column/CategoricalColumnFormatter.tsx
  src/shared/components/mutationTable/column/MutationTypeColumnFormatter.spec.tsx
  src/shared/components/mutationTable/column/MutationTypeColumnFormatter.tsx
  src/shared/components/mutationTable/column/VariantTypeColumnFormatter.spec.tsx
  src/shared/components/mutationTable/column/VariantTypeColumnFormatter.tsx
  src/shared/components/mutationTable/column/mutationType.module.scss
  src/shared/components/mutationTable/column/variantType.module.scss
Labels: feature

#3093 Consolidate bitly code
  end-to-end-test/remote/specs/core/redirect.spec.js
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/querySummary/ShareUI.tsx
  src/pages/studyView/StudyViewPage.tsx
  src/routes.jsx
  src/shared/api/urls.ts
  src/shared/components/addThis/AddThisBookmark.tsx.bak
  src/shared/lib/bitly.ts
  src/shared/lib/redirectHelpers.ts
Labels: chore

#3094 Fix a couple of prettier issues
  package.json
Labels: chore

#3102 check for relative import from packages directory
  .circleci/config.yml
  package.json
  scripts/check_incorrect_import_statements.sh
  src/pages/staticPages/tools/oncoprinter/OncoprinterGeneticUtils.ts
  src/shared/lib/comparison/ComparisonStore.ts
Labels: DO NOT MERGE

#3099 Support other types of survival plots
  end-to-end-test/remote/screenshots/reference/filter_study_from_url_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_survival_tab_exclude_overlapping_samples_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_survival_tab_include_overlapping_samples_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_survival_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_survival_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/when_quickly_adding_charts,_each_chart_should_get_proper_data._element_chrome_1600x1000.png
  src/config/serverConfigDefaults.ts
  src/pages/groupComparison/Survival.tsx
  src/pages/groupComparison/styles.module.scss
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/survival/SurvivalChart.tsx
  src/pages/resultsView/survival/SurvivalDescriptionTable.tsx
  src/pages/resultsView/survival/SurvivalUtil.tsx
  src/pages/studyView/StudyViewConfig.ts
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/StudyViewUtils.tsx
  src/pages/studyView/chartHeader/ChartHeader.tsx
  src/pages/studyView/charts/ChartContainer.tsx
  src/pages/studyView/tabs/SummaryTab.tsx
  src/shared/lib/comparison/ComparisonStore.ts
Labels: enhancement

#2981 Add civic support for annotation column in react-mutation-mapper
  package.json
  packages/cbioportal-frontend-commons/package.json
  packages/cbioportal-frontend-commons/src/index.tsx
  packages/cbioportal-frontend-commons/src/lib/getMobxPromiseGroupStatus.ts
  packages/react-mutation-mapper/package.json
  packages/react-mutation-mapper/src/component/civic/Civic.spec.tsx
  packages/react-mutation-mapper/src/component/civic/Civic.tsx
  packages/react-mutation-mapper/src/component/civic/CivicCard.spec.tsx
  packages/react-mutation-mapper/src/component/civic/CivicCard.tsx
  packages/react-mutation-mapper/src/component/civic/civicCard.scss
  packages/react-mutation-mapper/src/component/column/Annotation.tsx
  packages/react-mutation-mapper/src/component/mutationMapper/MutationMapper.tsx
  packages/react-mutation-mapper/src/component/mutationTable/DefaultMutationTable.tsx
  packages/react-mutation-mapper/src/images/civic-logo-no-variants.png
  packages/react-mutation-mapper/src/images/civic-logo.png
  packages/react-mutation-mapper/src/images/civic_text_logo.png
  packages/react-mutation-mapper/src/index.tsx
  packages/react-mutation-mapper/src/model/Civic.ts
  packages/react-mutation-mapper/src/model/MutationMapperStore.ts
  packages/react-mutation-mapper/src/store/CivicDataFetcher.ts
  packages/react-mutation-mapper/src/store/DefaultMutationMapperStore.ts
  packages/react-mutation-mapper/src/util/CivicUtils.ts
  src/config/config.ts
  src/pages/groupComparison/ClinicalData.tsx
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
  src/pages/patientView/copyNumberAlterations/column/AnnotationColumnFormatter.spec.tsx
  src/pages/patientView/copyNumberAlterations/column/AnnotationColumnFormatter.tsx
  src/pages/resultsView/cancerSummary/CancerSummaryContainer.tsx
  src/pages/resultsView/coExpression/CoExpressionTab.tsx
  src/pages/resultsView/download/DownloadTab.tsx
  src/pages/resultsView/mutation/ResultsViewMutationMapper.tsx
  src/pages/resultsView/mutation/ResultsViewMutationMapperStore.ts
  src/pages/resultsView/plots/PlotsTab.tsx
  src/pages/staticPages/tools/mutationMapper/StandaloneMutationMapper.tsx
  src/shared/api/civicClientInstance.ts
  src/shared/components/MobxView.tsx
  src/shared/components/annotation/Civic.spec.tsx
  src/shared/components/annotation/CivicCard.spec.tsx
  src/shared/components/mutationMapper/MutationMapperStore.ts
  src/shared/components/mutationTable/column/AnnotationColumnFormatter.spec.tsx
  src/shared/components/mutationTable/column/AnnotationColumnFormatter.tsx
  src/shared/components/oncoprint/ResultsViewOncoprint.tsx
  src/shared/components/progressIndicator/ProgressIndicator.tsx
  src/shared/lib/CivicUtils.spec.ts
  src/shared/lib/CivicUtils.ts
  src/shared/lib/StoreUtils.spec.ts
  src/shared/lib/StoreUtils.ts
  src/shared/model/Civic.ts
  src/test/CivicMockUtils.ts
Labels: enhancement

#3116 Update survival plots vocabulary
  src/config/serverConfigDefaults.ts
  src/pages/resultsView/survival/SurvivalUtil.tsx
  src/pages/studyView/StudyViewConfig.ts
Labels: study view

#3113 Make filter warnings more clear when VUS/germline alterations excluded
  src/shared/components/banners/AlterationFilterWarning.tsx
Labels: enhancement, needs-product-review

#3080 plots tab - store UI selections in URL parameters
  .prettierrc
  end-to-end-test/local/specs/core/postedquery.spec.js
  end-to-end-test/local/specs/treatment.screenshot.spec.js
  end-to-end-test/remote/specs/core/plots.screenshot.spec.js
  src/pages/resultsView/ResultsViewPage.tsx
  src/pages/resultsView/ResultsViewURLWrapper.ts
  src/pages/resultsView/pathwayMapper/ResultsViewPathwayMapper.tsx
  src/pages/resultsView/plots/PlotsTab.tsx
  src/shared/components/query/QueryStore.ts
  src/shared/components/query/QueryStoreUtils.spec.ts
  src/shared/components/query/QueryStoreUtils.ts
  src/shared/lib/ExtendedRouterStore.ts
  src/shared/lib/TypeScriptUtils.ts
  src/shared/lib/URLWrapper.spec.ts
  src/shared/lib/URLWrapper.ts
Labels: enhancement

#3090 Study View: New genomic profile samples count table
  end-to-end-test/remote/screenshots/reference/filter_study_from_url_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/fusion_filter_filter_study_from_url_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/when_quickly_adding_charts,_each_chart_should_get_proper_data._element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/studyview.spec.js
  src/config/serverConfigDefaults.ts
  src/globalStyles/images/intersection.svg
  src/globalStyles/images/union.svg
  src/pages/groupComparison/GroupComparisonUtils.tsx
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/plots/PlotsTabUtils.tsx
  src/pages/studyView/StudyViewConfig.ts
  src/pages/studyView/StudyViewPage.tsx
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/StudyViewUtils.spec.ts
  src/pages/studyView/StudyViewUtils.tsx
  src/pages/studyView/TableUtils.tsx
  src/pages/studyView/UserSelections.tsx
  src/pages/studyView/charts/ChartContainer.tsx
  src/pages/studyView/studyPageHeader/ActionButtons.tsx
  src/pages/studyView/studyPageHeader/StudyPageHeader.tsx
  src/pages/studyView/table/FixedHeaderTable.tsx
  src/pages/studyView/table/GeneCell.tsx
  src/pages/studyView/table/MultiSelectionTable.tsx
  src/pages/studyView/table/tables.module.scss
  src/pages/studyView/tabs/ClinicalDataTab.tsx
  src/pages/studyView/tabs/SummaryTab.tsx
  src/pages/studyView/virtualStudy/VirtualStudy.tsx
  src/shared/api/generated/CBioPortalAPIInternal-docs.json
  src/shared/api/generated/CBioPortalAPIInternal.ts
  src/shared/components/copyDownloadControls/CopyDownloadQueryLinks.tsx
Labels: feature

#3126 genomic evolution tab - make app state shareable in link
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/PatientViewUrlWrapper.ts
  src/pages/patientView/mutation/PatientViewMutationsDataStore.ts
  src/pages/patientView/mutation/PatientViewMutationsTab.tsx
  src/pages/patientView/mutation/oncoprint/MutationOncoprint.tsx
  src/shared/lib/URLWrapper.ts
Labels: enhancement
