Repository cBioPortal/cbioportal-frontend, pull requests merged in 2020-01, with the labels that each got.

#2912 Study view filter updates
  src/pages/groupComparison/GroupComparisonUtils.tsx
  src/pages/groupComparison/comparisonGroupManager/ComparisonGroupManager.tsx
  src/pages/studyView/StudyViewPage.tsx
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/StudyViewUtils.spec.ts
  src/pages/studyView/StudyViewUtils.tsx
  src/pages/studyView/TableUtils.tsx
  src/pages/studyView/UserSelections.tsx
  src/pages/studyView/charts/ChartContainer.tsx
  src/pages/studyView/charts/barChart/BarChart.tsx
  src/pages/studyView/charts/scatterPlot/StudyViewDensityScatterPlot.tsx
  src/pages/studyView/charts/scatterPlot/StudyViewScatterPlot.tsx
  src/pages/studyView/charts/scatterPlot/StudyViewScatterPlotUtils.ts
  src/pages/studyView/studyPageHeader/StudyPageHeader.tsx
  src/pages/studyView/table/GeneTable.tsx
  src/pages/studyView/tabs/SummaryTab.tsx
  src/shared/api/generated/CBioPortalAPIInternal-docs.json
  src/shared/api/generated/CBioPortalAPIInternal.ts
Labels: ready to review

#2967 Allow RMM and commons to be installed with a higher version of the node and yarn
  package.json
  packages/cbioportal-frontend-commons/package.json
  packages/react-mutation-mapper/package.json
Labels: chore

#2904 Add _GERMLINE and _DRIVER support to oncoprinter
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_annotated_by_oncokb_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_dont_color_by_driver_vs_vus_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_dont_color_by_mutation_type_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_hide_vus_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_start_by_set_gene_order,_then_set_sample_order_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_start_by_set_sample_order,_then_set_gene_order_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_then_set_gene_order,_including_all_genes_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_then_set_gene_order,_not_including_all_genes_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_then_set_sample_order,_including_all_samples_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_then_set_sample_order,_not_including_all_samples_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/oncoprinter.screenshot.spec.js
  end-to-end-test/remote/specs/core/oncoprinter.spec.js
  src/pages/resultsView/settings/DriverAnnotationControls.tsx
  src/pages/staticPages/tools/oncoprinter/Oncoprinter.tsx
  src/pages/staticPages/tools/oncoprinter/OncoprinterConstants.ts
  src/pages/staticPages/tools/oncoprinter/OncoprinterGeneticUtils.spec.ts
  src/pages/staticPages/tools/oncoprinter/OncoprinterGeneticUtils.ts
  src/pages/staticPages/tools/oncoprinter/OncoprinterStore.ts
  src/pages/staticPages/tools/oncoprinter/OncoprinterTool.tsx
  src/pages/staticPages/tools/oncoprinter/styles.module.scss
  src/pages/studyView/addChartButton/AddChartButton.tsx
  src/pages/studyView/infoBanner/SuccessBanner.tsx
  src/shared/components/banners/InfoBanner.tsx
  src/shared/components/oncoprint/controls/OncoprintControls.tsx
  src/shared/constants.ts
  src/shared/lib/MutationUtils.ts
  src/shared/lib/oql/oql-parser.d.ts
Labels: enhancement, ready to review

#2975 use new oncoprint version, which uses numbers for shape specification
  package.json
  src/pages/patientView/mutation/oncoprint/MutationOncoprintUtils.ts
  src/shared/components/oncoprint/OncoprintUtils.ts
  src/shared/components/oncoprint/geneticrules.ts
  src/shared/lib/ObjectManipulation.ts
  yarn.lock
Labels: enhancement

#2984 Use SAMPLE_ACQUISITION track for sample order
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/SampleManager.tsx
Labels: cl-prototype

#2993 [react-mutation-mapper] display error message when no transcript available
  package.json
  packages/react-mutation-mapper/package.json
  packages/react-mutation-mapper/src/component/lollipopMutationPlot/LollipopMutationPlot.tsx
Labels: enhancement

#2997 Remove empty param from URL in e2e test which was causing issues with…
  end-to-end-test/remote/specs/core/oncoprint.spec.js
Labels: bug, chore

#2998 Change footer version logic
  src/AppStore.ts
Labels: cl-style-tweak

#2999 SV: Fix failing test
  end-to-end-test/remote/screenshots/reference/fusion_filter_filter_study_from_url_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/studyview.spec.js
Labels: ready to review

#2930 oncoprint - fix occasional bug with removing tracks
  end-to-end-test/local/specs/core/querypage.spec.js
  end-to-end-test/remote/specs/core/coexpression.screenshot.spec.js
  end-to-end-test/remote/specs/core/mutationTable.spec.js
  end-to-end-test/remote/specs/core/oncoprint.screenshot.spec.js
  end-to-end-test/remote/specs/core/results.spec.js
  end-to-end-test/remote/specs/core/screenshot.spec.js
  src/shared/components/oncoprint/DeltaUtils.ts
  src/shared/components/oncoprint/Oncoprint.tsx
  src/shared/components/oncoprint/OncoprintUtils.ts
Labels: bug

#2988 Tweaks to ng-chm button (Fixes #6973)
  src/shared/components/oncoprint/controls/ConfirmNgchmModal.tsx
  src/shared/components/oncoprint/controls/OncoprintControls.tsx
  src/shared/components/oncoprint/controls/mdandersonlogo260x85.png
Labels: needs-product-review, style tweak

#3001 Update circleci build cache key to take packages folder into account
  .circleci/config.yml
Labels: chore

#2987 Show gnomad in number
  packages/react-mutation-mapper/src/component/gnomad/GnomadFrequency.tsx
  packages/react-mutation-mapper/src/component/gnomad/GnomadFrequencyTable.tsx
  packages/react-mutation-mapper/src/util/FormatUtils.ts
  src/shared/components/mutationTable/MutationTable.tsx
  src/shared/components/mutationTable/column/GnomadColumnFormatter.tsx
Labels: enhancement

#2978 Set width as 100% of clinical cretieria container when the trial is matc…
  src/pages/patientView/trialMatch/TrialMatchTable.tsx
  src/pages/patientView/trialMatch/TrialMatchTableUtils.ts
  src/pages/patientView/trialMatch/style/trialMatch.module.scss
Labels: ready to review

#2980 Study View: Always show selected genes on top and alternate selected rows color
  end-to-end-test/remote/screenshots/reference/filter_study_from_url_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/fusion_filter_filter_study_from_url_element_chrome_1600x1000.png
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/TableUtils.tsx
  src/pages/studyView/table/FixedHeaderTable.tsx
  src/pages/studyView/table/GeneTable.tsx
  src/pages/studyView/table/tables.module.scss
Labels: enhancement

#3006 On Netlify, optimize build times by running ts transpileOnly (except prod build)
  webpack.config.js
Labels: chore

#2985 Let results view oncoprint fill page, instead of imposing a maximum height
  end-to-end-test/remote/screenshots/reference/acc_tcga_with_clinical_and_heatmap_tracks_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/blca_tcga_with_clinical_and_heatmap_tracks_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_should_sort_patients_correctly_in_coadread_tcga_pub_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_should_sort_samples_correctly_in_coadread_tcga_pub_element_chrome_1600x1000.png
  package.json
  src/shared/components/oncoprint/Oncoprint.tsx
  src/shared/components/oncoprint/ResultsViewOncoprint.tsx
  yarn.lock
Labels: enhancement, needs-product-review

#2973 Study view: reset filters when custom cases are selected
  src/pages/studyView/StudyViewPage.tsx
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/addChartButton/customCaseSelection/CustomCaseSelection.tsx
  src/pages/studyView/addChartButton/customCaseSelection/styles.module.scss
Labels: needs-product-review, ready to review

#3007 Do not use new oncokb proxy as it doesn't work for private portal
  src/shared/api/urls.ts
Labels: skip-changelog

#2994 Add quick oql edit feature to results view page next to current gene list
  src/pages/resultsView/ResultsViewPage.tsx
  src/pages/resultsView/querySummary/QuerySummary.tsx
  src/pages/resultsView/styles.scss
  src/shared/components/GeneSelectionBox/OQLTextArea.tsx
  src/shared/components/GeneSelectionBox/styles.module.scss
  src/shared/components/query/styles/styles.module.scss
Labels: feature, needs-product-review

#2971 add hgvsg column and link out to genome nexus
  src/config/IAppConfig.ts
  src/config/serverConfigDefaults.ts
  src/pages/patientView/mutation/PatientViewMutationTable.tsx
  src/pages/resultsView/mutation/ResultsViewMutationTable.tsx
  src/pages/staticPages/tools/mutationMapper/StandaloneMutationTable.tsx
  src/shared/api/urls.ts
  src/shared/components/mutationTable/MutationTable.tsx
  src/shared/components/mutationTable/column/GenomeNexusLogo.png
  src/shared/components/mutationTable/column/HgvsgColumnFormatter.tsx
  src/shared/components/mutationTable/column/hgvsg.module.scss
  src/shared/lib/MutationUtils.spec.ts
  src/shared/lib/MutationUtils.ts
Labels: feature

#3011 Tweak wording of quick gene edit submit button
  src/pages/resultsView/ResultsViewPage.tsx
Labels: style tweak

#3012 Temporary fix for private portal consumption of oncokb
  src/shared/api/urls.ts
Labels: skip-changelog

#3026 In default search example configuration, change "provisional" to "leg…
  src/config/serverConfigDefaults.ts
Labels: style tweak
