Repository cBioPortal/cbioportal-frontend, pull requests merged in 2020-06, with the labels that each got.

#3244 Check intragenic before regular fusion & Do not set intragenic as functionalFusion
  packages/cbioportal-frontend-commons/src/lib/oncokb/OncoKbUtils.ts
Labels: bug

#3219 Trim off html entities coming from NCI API
  packages/cbioportal-frontend-commons/src/lib/StringUtils.spec.ts
  packages/cbioportal-frontend-commons/src/lib/StringUtils.ts
  packages/react-mutation-mapper/src/component/oncokb/PmidItem.tsx
Labels: bug

#3251 oncoprint - make counts tracks (e.g. mutation spectrum) downloadable)
  src/shared/components/oncoprint/tabularDownload.spec.ts
  src/shared/components/oncoprint/tabularDownload.ts
Labels: cl-bug

#3248 Split OncoKbCard to small components && Add e2e tests for OncoKB
  end-to-end-test/remote/screenshots/reference/patient_view_-_gene_is_cancer_gene_but_has_not_been_curated_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_-_with_levels_-_mutation_effect_tab_shows_correctly_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_-_with_levels_-_oncogenicity_tab_shows_correctly_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_-_without_levels_-_mutation_effect_tab_shows_correctly_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_-_without_levels_-_oncogenicity_tab_shows_correctly_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_-_gene_is_cancer_gene_but_has_not_been_curated_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_-_with_levels_-_oncogenicity_tab_shows_correctly_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_-_without_levels_-_oncogenicity_tab_shows_correctly_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/oncokb.spec.js
  end-to-end-test/remote/specs/core/oncoprint.screenshot.spec.js
  end-to-end-test/remote/specs/core/oncoprint.spec.js
  end-to-end-test/remote/specs/core/patient.logic.spec.js
  end-to-end-test/shared/specUtils.js
  packages/react-mutation-mapper/package.json
  packages/react-mutation-mapper/src/component/oncokb/OncoKbCard.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbCardBody.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbCardLevelsOfEvidenceDropdown.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbCardTitle.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbCardTreatmentContent.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbHelper.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbTooltip.tsx
Labels: DO NOT MERGE

#3258 Update screenshots for release-3.4.0
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_initial_patient_order_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_initial_sample_order_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_patient_order_1_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_patient_order_2_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_patient_order_3_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_patient_order_4_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_sample_order_1_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_sample_order_2_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_sample_order_3_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_sample_order_4_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_sample_order_5_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_sample_order_6_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_heatmap_tracks_sorted_-_sorted_patient_order_1_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_heatmap_tracks_sorted_-_sorted_sample_order_1_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_heatmap_tracks_sorted_-_sorted_sample_order_2_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_heatmap_tracks_sorted_-_sorted_sample_order_3_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_heatmap_tracks_sorted_-_sorted_sample_order_4_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_heatmap_tracks_sorted_-_sorted_sample_order_5_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_-_gene_is_cancer_gene_but_has_not_been_curated_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_-_with_levels_-_mutation_effect_tab_shows_correctly_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_-_without_levels_-_mutation_effect_tab_shows_correctly_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_-_without_levels_-_oncogenicity_tab_shows_correctly_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_lgg_ucsf_2014_p04_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_with_0_mutations_msk_impact_2017_p-0000053-t01-im3_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/study_view_laml_tcga_clinical_data_clicked_element_chrome_1600x1000.png
  src/pages/patientView/timeline/legacy.js
  src/shared/lib/Colors.ts
Labels: ready to review

#3260 (Patient page header) Remove prefix for OS_STATUS and DFS_STATUS
  end-to-end-test/remote/screenshots/reference/patient_view_-_gene_is_cancer_gene_but_has_not_been_curated_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_-_with_levels_-_mutation_effect_tab_shows_correctly_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_-_without_levels_-_mutation_effect_tab_shows_correctly_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_-_without_levels_-_oncogenicity_tab_shows_correctly_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_lgg_ucsf_2014_p04_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_with_0_mutations_msk_impact_2017_p-0000053-t01-im3_element_chrome_1600x1000.png
  src/pages/patientView/clinicalInformation/lib/clinicalAttributesUtil.js
  src/pages/patientView/patientHeader/style/clinicalAttributes.scss
Labels: ready to review

#3259 Combine Comparison and Survival navigation buttons into one button reading "Comparison/Surivval"
  end-to-end-test/remote/screenshots/reference/results_view_-_gene_is_cancer_gene_but_has_not_been_curated_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_-_with_levels_-_oncogenicity_tab_shows_correctly_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_-_without_levels_-_oncogenicity_tab_shows_correctly_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_delete_group_from_session_element_chrome_1600x1000.png
  src/pages/resultsView/ResultsViewPage.tsx
Labels: enhancement

#3227 oncoprint - open data in oncoprinter
  end-to-end-test/remote/screenshots/reference/oncoprinter_clinical_example_data_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_then_set_gene_order,_including_all_genes_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_then_set_sample_order,_including_all_samples_element_chrome_1600x1000.png
  src/pages/staticPages/tools/oncoprinter/OncoprinterClinicalUtils.spec.ts
  src/pages/staticPages/tools/oncoprinter/OncoprinterClinicalUtils.ts
  src/pages/staticPages/tools/oncoprinter/OncoprinterConstants.ts
  src/pages/staticPages/tools/oncoprinter/OncoprinterGeneticUtils.ts
  src/pages/staticPages/tools/oncoprinter/OncoprinterImportUtils.spec.ts
  src/pages/staticPages/tools/oncoprinter/OncoprinterImportUtils.ts
  src/pages/staticPages/tools/oncoprinter/OncoprinterTool.tsx
  src/shared/cache/ClinicalDataCache.ts
  src/shared/components/oncoprint/DeltaUtils.ts
  src/shared/components/oncoprint/Oncoprint.tsx
  src/shared/components/oncoprint/OncoprintUtils.ts
  src/shared/components/oncoprint/ResultsViewOncoprint.tsx
  src/shared/components/oncoprint/controls/OncoprintControls.tsx
  src/shared/components/oncoprint/tabularDownload.spec.ts
Labels: feature

#3263 update api docs
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPI-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPI.ts
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPI-docs.json
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPI.ts
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPIInternal-docs.json
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPIInternal.ts
  src/test/CivicMockUtils.ts
  src/test/MutationMockUtils.ts
Labels: automerge, chore

#3256 Remove local dev banner when doing e2e tests
  end-to-end-test/remote/screenshots/reference/should_show_error_message_for_wrong_patient_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/should_show_error_message_for_wrong_sample_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/home.spec.js
  end-to-end-test/remote/specs/core/oncokb.spec.js
  end-to-end-test/remote/specs/core/oncoprint.screenshot.spec.js
  end-to-end-test/remote/specs/core/oncoprint.spec.js
  end-to-end-test/shared/specUtils.js
  src/globalStyles/e2etest.scss
Labels: bug

#3264 Hide "Days since diagnosis label" on clinical timeline
  src/pages/patientView/timeline/styles.scss
Labels: cl-style-tweak

#3267 Add banner about #ShutDownAcademia
  src/shared/components/userMessager/UserMessage.tsx
  src/shared/components/userMessager/styles.module.scss
Labels: skip-changelog

#3262 rearrange mutation table columns
  src/pages/patientView/mutation/PatientViewMutationTable.tsx
  src/pages/resultsView/mutation/ResultsViewMutationTable.tsx
  src/pages/staticPages/tools/mutationMapper/StandaloneMutationTable.tsx
Labels: cl-style-tweak

#3273 Show survival charts by default for pan-cancer studies
  end-to-end-test/remote/screenshots/reference/check_for_survival_plots_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/studyview.spec.js
  src/pages/studyView/StudyViewPageStore.ts
Labels: ready to review

#3287 update oncokb client
  package.json
  packages/cbioportal-frontend-commons/package.json
  packages/oncokb-ts-api-client/package.json
  packages/oncokb-ts-api-client/src/generated/OncoKbAPI-docs.json
  packages/oncokb-ts-api-client/src/generated/OncoKbAPI.ts
  packages/react-mutation-mapper/package.json
Labels: chore

#3288 Update oncokb tests
  end-to-end-test/remote/screenshots/reference/patient_view_-_gene_is_cancer_gene_but_has_not_been_curated_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_-_with_levels_-_oncogenicity_tab_shows_correctly_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_-_without_levels_-_mutation_effect_tab_shows_correctly_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_-_without_levels_-_oncogenicity_tab_shows_correctly_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/oncokb.spec.js
Labels: test

#3293 Add mutation assessor definition to functional impact tooltip
  src/shared/components/mutationTable/column/FunctionalImpactColumnFormatter.tsx
Labels: enhancement

#3299 Edit localdb e2e test setup
  scripts/setup_localdb.sh
Labels: skip-changelog

#3292 Replace getMutationAligner.json servlet with proxy
  packages/react-mutation-mapper/src/cache/MutationAlignerCache.ts
  packages/react-mutation-mapper/src/util/DataFetcherUtils.ts
  src/pages/resultsView/mutation/Mutations.tsx
  src/pages/staticPages/tools/mutationMapper/MutationMapperTool.tsx
  src/shared/api/urls.ts
Labels: automerge, cl-external-api

#3301 Add filter alert banners to pathways tab
  src/pages/resultsView/pathwayMapper/ResultsViewPathwayMapper.tsx
Labels: feature
