Repository cBioPortal/cbioportal-frontend, pull requests merged in 2020-07, with the labels that each got.

#3283 Fix missing header for GSVA heatmap track group
  end-to-end-test/local/screenshots/reference/shows_gsva_heatmap_track_element_chrome_1600x1000.png
  src/shared/components/oncoprint/ResultsViewOncoprint.tsx
  src/shared/components/oncoprint/ResultsViewOncoprintUtils.tsx
Labels: style tweak

#3268 results view comparison tab - improve description of altered/unaltered groups and put them in tooltips
  src/pages/groupComparison/ClinicalData.tsx
  src/pages/groupComparison/CreateGroupFromOverlap.tsx
  src/pages/groupComparison/GroupComparisonStore.ts
  src/pages/groupComparison/Overlap.tsx
  src/pages/groupComparison/groupSelector/GroupSelector.tsx
  src/pages/groupComparison/groupSelector/GroupSelectorButton.tsx
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/comparison/ResultsViewComparisonStore.ts
  src/pages/resultsView/comparison/ResultsViewComparisonUtils.ts
  src/pages/resultsView/oncoprint/AddClinicalTracks.tsx
  src/shared/api/ComparisonGroupClient.ts
  src/shared/lib/comparison/ComparisonStore.ts
Labels: feature

#3284 generic assay data download on download tab
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/ResultsViewPageStoreUtils.ts
  src/pages/resultsView/download/DownloadTab.tsx
  src/pages/resultsView/download/DownloadUtils.ts
  src/shared/lib/GenericAssayUtils/GenericAssayCommonUtils.ts
Labels: ready to review

#3296 Retire use of api-legacy endpoints
  src/shared/api/MatchMinerAPI.ts
  src/shared/api/urls.ts
Labels: DO NOT MERGE, chore

#3309 Update session and matchminer endpoints
  src/shared/api/MatchMinerAPI.ts
  src/shared/api/urls.ts
Labels: external api

#3308 Fix portion of e2e tests for v3.4.3
  end-to-end-test/remote/screenshots/reference/blca_tcga_with_clinical_and_heatmap_tracks_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/enrichments_tab_coadread_tcga_pub_mrna_profile_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_mrna_enrichments_tab_several_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_mrna_enrichments_tab_two_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_comparison_tab_mrna_enrichments_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/removes_top_treatment_track_successfully_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_mrna_enrichments_tab_two_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_comparison_tab_mrna_enrichments_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/comparisonTab.screenshot.spec.js
Labels: DO NOT MERGE

#3266 Option to exclude unprofiled samples in results view
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_cancer_type_summary_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_comparison_tab_clinical_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_comparison_tab_mutation_enrichments_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_comparison_tab_mutation_enrichments_patient_mode_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_comparison_tab_overlap_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_mutex_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_pathwaymapper_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_plots_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_render_the_oncoprint_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_survival_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/screenshot.spec.js
  src/pages/groupComparison/GroupComparisonUtils.tsx
  src/pages/resultsView/NotUsingGenePanelWarning.tsx
  src/pages/resultsView/ResultsViewPage.tsx
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/ResultsViewURLWrapper.ts
  src/pages/resultsView/cancerSummary/CancerSummaryContainer.spec.tsx
  src/pages/resultsView/cancerSummary/CancerSummaryContainer.tsx
  src/pages/resultsView/cnSegments/CNSegments.tsx
  src/pages/resultsView/coExpression/CoExpressionTab.tsx
  src/pages/resultsView/comparison/ComparisonTab.tsx
  src/pages/resultsView/comparison/ResultsViewComparisonStore.ts
  src/pages/resultsView/comparison/ResultsViewComparisonUtils.ts
  src/pages/resultsView/download/DownloadTab.tsx
  src/pages/resultsView/expression/ExpressionWrapper.tsx
  src/pages/resultsView/mutation/Mutations.tsx
  src/pages/resultsView/mutualExclusivity/MutualExclusivityTab.tsx
  src/pages/resultsView/pathwayMapper/ResultsViewPathwayMapper.tsx
  src/pages/resultsView/plots/PlotsTab.tsx
  src/pages/resultsView/plots/PlotsTabUtils.tsx
  src/pages/resultsView/querySummary/QuerySummary.tsx
  src/pages/resultsView/querySummary/QuerySummaryUtils.tsx
  src/pages/resultsView/settings/ResultsPageSettings.tsx
  src/shared/cache/ClinicalDataCache.ts
  src/shared/components/banners/CaseFilterWarning.tsx
  src/shared/components/oncoprint/OncoprintUtils.ts
  src/shared/components/oncoprint/ResultsViewOncoprint.spec.tsx
  src/shared/components/oncoprint/ResultsViewOncoprint.tsx
  src/shared/lib/isSampleProfiled.ts
Labels: feature

#3291 Enable plots tab for multiple studies query
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_plots_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_plots_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_boxplot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_horizontal_grouped_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_horizontal_percentage_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_horizontal_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_percentage_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_table_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_molecular_boxplot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_molecular_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_copy_number_view_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_copy_number_vs_clinical_horizontal_percentage_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_copy_number_vs_clinical_horizontal_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_copy_number_vs_clinical_percentage_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_copy_number_vs_clinical_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_copy_number_vs_clinical_table_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_log_scale_off_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_molecular_vs_clinical_boxplot,_mutation_search_off_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_molecular_vs_molecular_different_genes_different_profiles_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_molecular_vs_molecular_different_genes_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_molecular_vs_molecular_same_gene_changed_gene_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_molecular_vs_molecular_same_gene_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_molecular_vs_molecular_swapped_axes_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_multiple_studies_with_data_availability_alert_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutation_type_view_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_profile_with_duplicates_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_vs_clinical_boxplot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_vs_clinical_horizontal_percentage_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_vs_clinical_horizontal_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_vs_clinical_percentage_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_vs_clinical_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_vs_clinical_table_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_wild_type_mode_vs_clinical_boxplot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_wildtype_mode_vs_clinical_horizontal_percentage_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_wildtype_mode_vs_clinical_horizontal_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_wildtype_mode_vs_clinical_percentage_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_wildtype_mode_vs_clinical_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_wildtype_mode_vs_clinical_table_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_one_box_clinical_vs_clinical_boxplot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_search_case_id_and_mutation_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_search_case_id_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_search_case_id_in_clinical_vs_clinical_boxplot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_search_mutation_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_plots_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/plots.screenshot.spec.js
  end-to-end-test/remote/specs/core/plots.spec.js
  src/pages/resultsView/ResultsViewPage.tsx
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/plots/PlotsTab.tsx
  src/pages/resultsView/plots/PlotsTabUtils.spec.ts
  src/pages/resultsView/plots/PlotsTabUtils.tsx
  src/pages/resultsView/plots/styles.scss
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/StudyViewUtils.tsx
  src/shared/lib/molecularProfileUtils.spec.ts
  src/shared/lib/molecularProfileUtils.ts
Labels: ready to review

#3315 Make mutation type colors be consistent in all places
  packages/react-mutation-mapper/src/component/column/mutationType.module.scss
  packages/react-mutation-mapper/src/component/column/mutationType.module.scss.d.ts
  src/shared/components/mutationTable/column/mutationType.module.scss
Labels: cl-style-tweak

#3304 Study page: updates to comparison group manager
  src/pages/groupComparison/GroupComparisonUtils.tsx
  src/pages/groupComparison/comparisonGroupManager/ComparisonGroupManager.tsx
  src/pages/groupComparison/comparisonGroupManager/ComparisonGroupManagerUtils.ts
  src/pages/groupComparison/comparisonGroupManager/GroupCheckbox.tsx
  src/pages/groupComparison/styles.module.scss
  src/pages/groupComparison/styles.module.scss.d.ts
  src/pages/resultsView/bookmark/BookmarkModal.tsx
  src/pages/studyView/StudyViewPage.tsx
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/addChartButton/geneLevelSelection/GeneLevelSelection.tsx
  src/shared/api/ComparisonGroupClient.ts
Labels: feature

#3211 Add transcript dropdown on result view
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/mutationMapperTool.spec.js
  packages/cbioportal-frontend-commons/src/lib/getCanonicalMutationType.ts
  packages/cbioportal-utils/src/mutation/MutationAnnotator.ts
  packages/react-mutation-mapper/src/component/filter/ProteinImpactTypeBadgeSelector.tsx
  packages/react-mutation-mapper/src/component/filter/ProteinImpactTypeHelper.tsx
  packages/react-mutation-mapper/src/component/lollipopMutationPlot/DefaultLollipopPlotLegend.tsx
  packages/react-mutation-mapper/src/component/lollipopMutationPlot/LollipopMutationPlot.tsx
  packages/react-mutation-mapper/src/component/mutationMapper/MutationMapper.tsx
  packages/react-mutation-mapper/src/component/track/TrackPanel.tsx
  packages/react-mutation-mapper/src/model/MutationMapperStore.ts
  packages/react-mutation-mapper/src/model/ProteinImpact.ts
  packages/react-mutation-mapper/src/store/DefaultMutationMapperStore.ts
  packages/react-mutation-mapper/src/util/MutationTypeUtils.ts
  src/config/IAppConfig.ts
  src/config/serverConfigDefaults.ts
  src/pages/resultsView/ResultsViewPage.tsx
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/ResultsViewURLWrapper.ts
  src/pages/resultsView/mutation/Mutations.tsx
  src/pages/resultsView/mutation/ResultsViewMutationMapper.tsx
  src/pages/resultsView/mutation/ResultsViewMutationMapperStore.ts
  src/pages/resultsView/mutation/ResultsViewMutationTable.tsx
  src/pages/staticPages/tools/mutationMapper/StandaloneMutationMapper.tsx
  src/shared/components/mutationMapper/MutationMapper.tsx
  src/shared/components/mutationMapper/MutationMapperStore.ts
  src/shared/components/mutationTable/MutationTable.tsx
  src/shared/components/mutationTable/column/HgvscColumnFormatter.tsx
  src/shared/components/mutationTable/column/MutationTypeColumnFormatter.spec.tsx
  src/shared/components/mutationTable/column/MutationTypeColumnFormatter.tsx
  src/shared/components/mutationTable/column/ProteinChangeColumnFormatter.tsx
  src/shared/lib/MutationUtils.ts
Labels: feature, needs-product-review

#3321 update genome nexus api docs
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPI-docs.json
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPI.ts
Labels: chore

#3325 update Generic Assay data tooltip on Oncoprint heatmap
  src/shared/components/oncoprint/Oncoprint.tsx
  src/shared/components/oncoprint/OncoprintUtils.ts
  src/shared/components/oncoprint/TooltipUtils.spec.ts
  src/shared/components/oncoprint/TooltipUtils.ts
Labels: ready to review

#3328 Fix Plots tab error when querying multiple studies with empty sample ids
  src/pages/resultsView/ResultsViewPageStore.ts
Labels: ready to review

#3323 Hide mutation assessor on functional impact column
  src/shared/components/mutationTable/column/FunctionalImpactColumnFormatter.tsx
Labels: bug

#3314 Add extra header to aid debugging in sentry (cbioportal only)
  src/appBootstrapper.jsx
  src/shared/lib/extraHeader.ts
Labels: skip-changelog

#3322 Add data download export option to Cancer Type Summary chart
  src/pages/resultsView/cancerSummary/CancerSummaryChart.tsx
  src/pages/resultsView/cancerSummary/CancerSummaryContent.tsx
Labels: enhancement

#3327 map variant annotation with mutation by originalVariantQuery
  end-to-end-test/remote/specs/core/mutationMapperTool.spec.js
  packages/cbioportal-utils/src/mutation/MutationAnnotator.spec.ts
  packages/cbioportal-utils/src/mutation/MutationAnnotator.ts
  packages/react-mutation-mapper/src/store/DefaultMutationMapperDataFetcher.ts
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
Labels: bug

#3338 Disable custom GA tracking events for all except MSK managed portals…
  src/shared/lib/tracking.ts
Labels: enhancement
