Repository cBioPortal/cbioportal-frontend, pull requests merged in 2020-08, with the labels that each got.

#3342 Add google drive link to tutorials/webinars
  src/pages/staticPages/tutorials/Tutorials.tsx
Labels: automerge, documentation

#3341 fix missing mutations in ATRX
  packages/cbioportal-utils/src/mutation/MutationAnnotator.ts
  packages/cbioportal-utils/src/mutation/MutationUtils.spec.ts
  packages/cbioportal-utils/src/mutation/MutationUtils.ts
Labels: bug

#3343 Fix heatmap bug
  package.json
  src/shared/components/oncoprint/ResultsViewOncoprint.tsx
  src/shared/components/oncoprint/controls/OncoprintControls.tsx
  yarn.lock
Labels: bug

#3346 Only call genome nexus annotation when transcript switch is enabled
  src/pages/resultsView/ResultsViewPageStore.ts
Labels: bug

#3347 Improve error screen with better instructions for reporting error
  end-to-end-test/remote/screenshots/reference/should_show_error_message_for_wrong_patient_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/should_show_error_message_for_wrong_sample_element_chrome_1600x1000.png
  src/shared/components/errorScreen/ErrorScreen.tsx
Labels: enhancement

#3352 Add a study view warning
  src/appShell/App/Container.tsx
  src/pages/studyView/studyPageHeader/studyViewWarning/StudyViewWarning.tsx
Labels: skip-changelog

#3333 fix colors change when filters are applied
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/StudyViewUtils.tsx
Labels: bug

#3348 Nonstart mutations should be categorized as Truncating
  packages/cbioportal-frontend-commons/src/lib/getCanonicalMutationType.ts
Labels: bug

#2982 Impl. download of OAuth2/OpenID Connect DAT tokens (triggered by backend)
  package.json
  src/config/serverConfigDefaults.ts
  src/pages/staticPages/webAPI/WebAPIPage.tsx
  src/shared/components/dataAccessTokens/DataAccessTokensDropdown.tsx
Labels: feature

#3345 Fix missing header for GSVA heatmap track group (resubmission)
  end-to-end-test/local/screenshots/reference/shows_gsva_heatmap_track_element_chrome_1600x1000.png
  package.json
  src/shared/components/oncoprint/OncoprintUtils.ts
  src/shared/components/oncoprint/ResultsViewOncoprint.tsx
  src/shared/components/oncoprint/ResultsViewOncoprintUtils.tsx
Labels: bug

#3353 do not invoke an API call if there are no samples to query
  src/pages/resultsView/coExpression/CoExpressionTab.tsx
Labels: bug

#3354 Fix bug in venn diagram when it cant find a good layout
  src/pages/groupComparison/rectangleVennDiagram/layout.ts
Labels: bug

#3350 add mutation assessor back to functional impact column
  src/config/IAppConfig.ts
  src/config/serverConfigDefaults.ts
  src/shared/components/mutationTable/column/FunctionalImpactColumnFormatter.tsx
  src/shared/lib/genomeNexusAnnotationSourcesUtils.ts
Labels: enhancement

#3339 Remove migration step from localdb (part of image)
  end-to-end-test/local/docker/setup_docker_containers.sh
Labels: test

#3356 Make sure reference genome json is parsed regardless of contentype
  src/shared/lib/StoreUtils.ts
Labels: bug

#3330 Allow user to resize study view charts
  end-to-end-test/remote/screenshots/reference/check_for_survival_plots_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/filter_study_from_url_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/fusion_filter_filter_study_from_url_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/non_cancer_gene_should_show_up_when_the_cancer_gene_filter_is_disabled_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/the_cancer_gene_filter_should_remove_non_cancer_gene_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/the_msi_score_should_use_the_custom_bins,_then_the_msi_score_column_should_be_added_in_the_clinical_data_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/when_quickly_adding_charts,_each_chart_should_get_proper_data._element_chrome_1600x1000.png
  src/pages/studyView/StudyViewConfig.ts
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/StudyViewUtils.spec.ts
  src/pages/studyView/StudyViewUtils.tsx
  src/pages/studyView/charts/ChartContainer.tsx
  src/pages/studyView/charts/pieChart/PieChart.tsx
  src/pages/studyView/table/ClinicalTable.tsx
  src/pages/studyView/tabs/SummaryTab.tsx
Labels: feature

#3357 (Generic Assay) Oncoprint and Plots tab update
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/plots/PlotsTab.tsx
  src/pages/resultsView/plots/PlotsTabUtils.tsx
  src/pages/resultsView/plots/styles.scss
  src/shared/components/oncoprint/OncoprintUtils.ts
  src/shared/components/oncoprint/ResultsViewOncoprint.tsx
  src/shared/components/oncoprint/ResultsViewOncoprintUtils.spec.ts
  src/shared/components/oncoprint/ResultsViewOncoprintUtils.tsx
  src/shared/components/oncoprint/controls/OncoprintControls.tsx
  src/shared/lib/GenericAssayUtils/GenericAssayCommonUtils.spec.ts
  src/shared/lib/GenericAssayUtils/GenericAssayCommonUtils.ts
Labels: enhancement, ready to review

#3375 Update generated api files and fix errors
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPI-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPI.ts
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal.ts
  src/pages/studyView/StudyViewUtils.spec.ts
  src/shared/lib/GenericAssayUtils/GenericAssayCommonUtils.ts
Labels: automerge

#3377 update api docs
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal.ts
  packages/cbioportal-ts-api-client/src/index.tsx
  src/pages/resultsView/enrichments/EnrichmentsUtil.tsx
  src/shared/lib/comparison/ComparisonStore.ts
Labels: automerge, chore

#3378 Update screenshots post data update, skip oql test
  end-to-end-test/remote/screenshots/reference/filter_study_from_url_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/study_view_laml_tcga_clinical_data_clicked_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/when_quickly_adding_charts,_each_chart_should_get_proper_data._element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/home.spec.js
Labels: test

#3310 Add Treatments Charts To Study View (Frontend)
  src/pages/studyView/StudyViewConfig.ts
  src/pages/studyView/StudyViewPage.tsx
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/StudyViewUtils.spec.ts
  src/pages/studyView/StudyViewUtils.tsx
  src/pages/studyView/UserSelections.tsx
  src/pages/studyView/charts/ChartContainer.tsx
  src/pages/studyView/studyPageHeader/StudyPageHeader.tsx
  src/pages/studyView/table/treatments/AbstractTreatmentsTable.tsx
  src/pages/studyView/table/treatments/PatientTreatmentsTable.tsx
  src/pages/studyView/table/treatments/SampleTreatmentsTable.tsx
  src/pages/studyView/table/treatments/treatmentsTableUtil.tsx
  src/pages/studyView/tabs/SummaryTab.tsx
  src/pages/studyView/tabs/studySummaryTabStyles.module.scss
  src/pages/studyView/tabs/studySummaryTabStyles.module.scss.d.ts
Labels: cl-prototype

#3361 Include splice hotspots on mutation table
  packages/cbioportal-utils/src/hotspot/CancerHotspotsUtils.spec.ts
  packages/cbioportal-utils/src/hotspot/CancerHotspotsUtils.ts
  packages/react-mutation-mapper/src/component/column/Annotation.tsx
  packages/react-mutation-mapper/src/component/track/HotspotTrack.tsx
  src/pages/resultsView/ResultsViewPageStore.ts
  src/shared/lib/AnnotationUtils.spec.tsx
  src/shared/lib/AnnotationUtils.ts
Labels: enhancement

#3380 Make treatments charts display by default if data
  src/pages/studyView/StudyViewPageStore.ts
Labels: enhancement
