Repository cBioPortal/cbioportal-frontend, pull requests merged in 2020-10, with the labels that each got.

#3431 update oncokb client
  packages/oncokb-ts-api-client/src/generated/OncoKbAPI-docs.json
Labels: chore

#3433 Fix hard-coded app name, treatment condition for genie portal
  src/pages/studyView/StudyViewPageStore.ts
Labels: skip-changelog

#3429 Add timeline data to patient clinical data tab
  src/globalStyles/global.scss
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/patient.scss
  src/pages/patientView/timeline2/ClinicalEventsTables.tsx
  src/pages/patientView/timeline2/TimelineWrapper.tsx
  src/pages/patientView/timeline2/timelineDataUtils.ts
Labels: needs-product-review

#3439 Update api clients
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPI-docs.json
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPI.ts
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPIInternal-docs.json
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPIInternal.ts
Labels: skip-changelog

#3441 Fix e2e test for homepage study count
  end-to-end-test/remote/specs/core/home.spec.js
Labels: skip-changelog

#3437 oncoprint - hide menu dots unless hovering
  end-to-end-test/remote/screenshots/reference/hcc_inserm_fr_2015_with_genes_including_tert_-_it_should_show_orange_promoter_mutations_in_tert_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/msk_impact_2017_with_alk_and_sos1_-_sos1_should_be_not_sequenced_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/msk_impact_2017_with_sos1_-_sos1_should_be_not_sequenced_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/msk_impact_2017_with_sos1_with_cna_profile_-_sos1_should_not_be_sequenced_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/multiple_tracks_with_same_gene_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_render_the_oncoprint_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_should_sort_patients_correctly_in_coadread_tcga_pub_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_should_sort_patients_correctly_in_gbm_tcga_pub_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_should_sort_samples_correctly_in_coadread_tcga_pub_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_should_sort_samples_correctly_in_gbm_tcga_pub_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_initial_patient_order_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_initial_sample_order_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_patient_order_1_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_patient_order_2_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_patient_order_3_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_patient_order_4_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_sample_order_1_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_sample_order_2_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_sample_order_3_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_sample_order_4_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_sample_order_5_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_sample_order_6_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_heatmap_tracks_sorted_-_sorted_patient_order_1_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_heatmap_tracks_sorted_-_sorted_sample_order_1_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_heatmap_tracks_sorted_-_sorted_sample_order_2_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_heatmap_tracks_sorted_-_sorted_sample_order_3_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_heatmap_tracks_sorted_-_sorted_sample_order_4_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_heatmap_tracks_sorted_-_sorted_sample_order_5_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_genetic_only_example_data_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/profiled_in_tracks_in_a_combined_study_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/profiled_in_tracks_in_msk_impact_with_3_not_profiled_genes_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/profiled_in_tracks_in_multiple_study_with_sos1_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_render_the_oncoprint_element_chrome_1600x1000.png
  src/globalStyles/oncoprintStyles.scss
  src/pages/resultsView/styles.scss
  src/pages/staticPages/tools/oncoprinter/Oncoprinter.tsx
  src/shared/components/oncoprint/ResultsViewOncoprint.tsx
Labels: enhancement

#3440 Fix styling for FixedHeaderTable controls at top
  end-to-end-test/remote/screenshots/reference/when_quickly_adding_charts,_each_chart_should_get_proper_data._element_chrome_1600x1000.png
  src/pages/studyView/table/FixedHeaderTable.tsx
  src/pages/studyView/table/tables.module.scss
  src/pages/studyView/table/tables.module.scss.d.ts
Labels: bug

#3450 Implement comparison groups based on mutated genes table and treatments tables in study view
  src/pages/studyView/StudyViewComparisonUtils.ts
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/chartHeader/ChartHeader.tsx
  src/pages/studyView/chartHeader/styles.module.scss
  src/pages/studyView/chartHeader/styles.module.scss.d.ts
  src/pages/studyView/charts/ChartContainer.tsx
  src/pages/studyView/table/ClinicalTable.tsx
  src/pages/studyView/table/MultiSelectionTable.tsx
  src/pages/studyView/table/treatments/AbstractTreatmentsTable.tsx
  src/pages/studyView/table/treatments/PatientTreatmentsTable.tsx
  src/pages/studyView/table/treatments/SampleTreatmentsTable.tsx
  src/pages/studyView/table/treatments/treatmentsTableUtil.tsx
  src/pages/studyView/tabs/SummaryTab.tsx
Labels: automerge, feature

#3451 Remove double info treatment chart
  src/pages/studyView/tabs/SummaryTab.tsx
Labels: bug

#3454 Timeline Handle deceased event with special square
  packages/cbioportal-clinical-timeline/src/lib/helpers.spec.ts
  packages/cbioportal-clinical-timeline/src/lib/helpers.ts
  src/pages/patientView/timeline2/TimelineWrapper.tsx
Labels: enhancement

#3464 Study View: Fix local error display in charts
  src/pages/studyView/charts/ChartContainer.tsx
  src/pages/studyView/charts/styles.module.scss
  src/pages/studyView/charts/styles.module.scss.d.ts
Labels: style tweak

#3459 create react-variant-view package
  packages/react-variant-view/README.md
  packages/react-variant-view/package.json
  packages/react-variant-view/rollup.config.ts
  packages/react-variant-view/src/component/biologicalFunction/BiologicalFunction.tsx
  packages/react-variant-view/src/component/biologicalFunction/Oncokb.tsx
  packages/react-variant-view/src/component/featureTable/FeatureTable.module.scss
  packages/react-variant-view/src/component/featureTable/FeatureTable.module.scss.d.ts
  packages/react-variant-view/src/component/featureTable/FeatureTable.tsx
  packages/react-variant-view/src/component/featureTable/FunctionalImpact.scss
  packages/react-variant-view/src/component/featureTable/FunctionalImpactTooltip.module.scss
  packages/react-variant-view/src/component/featureTable/FunctionalImpactTooltip.module.scss.d.ts
  packages/react-variant-view/src/component/functionalPrediction/FunctionalPrediction.tsx
  packages/react-variant-view/src/component/functionalPrediction/MutationAssessor.tsx
  packages/react-variant-view/src/component/functionalPrediction/MutationAssessorTooltip.module.scss
  packages/react-variant-view/src/component/functionalPrediction/MutationAssessorTooltip.module.scss.d.ts
  packages/react-variant-view/src/component/functionalPrediction/PolyPhen2.tsx
  packages/react-variant-view/src/component/functionalPrediction/PolyPhen2Tooltip.module.scss
  packages/react-variant-view/src/component/functionalPrediction/PolyPhen2Tooltip.module.scss.d.ts
  packages/react-variant-view/src/component/functionalPrediction/Sift.tsx
  packages/react-variant-view/src/component/functionalPrediction/SiftTooltip.module.scss
  packages/react-variant-view/src/component/functionalPrediction/SiftTooltip.module.scss.d.ts
  packages/react-variant-view/src/component/headerAnnotation/HeaderAnnotation.module.scss
  packages/react-variant-view/src/component/headerAnnotation/HeaderAnnotation.module.scss.d.ts
  packages/react-variant-view/src/component/headerAnnotation/HeaderAnnotation.tsx
  packages/react-variant-view/src/component/headerAnnotation/TranscriptSummaryTable.module.scss
  packages/react-variant-view/src/component/headerAnnotation/TranscriptSummaryTable.module.scss.d.ts
  packages/react-variant-view/src/component/headerAnnotation/TranscriptSummaryTable.tsx
  packages/react-variant-view/src/component/headerAnnotation/TranscriptTable.tsx
  packages/react-variant-view/src/component/populationPrevalence/PopulationPrevalence.tsx
  packages/react-variant-view/src/component/therapeuticImplication/TherapeuticImplication.module.scss
  packages/react-variant-view/src/component/therapeuticImplication/TherapeuticImplication.module.scss.d.ts
  packages/react-variant-view/src/component/therapeuticImplication/TherapeuticImplication.tsx
  packages/react-variant-view/src/component/variantView/Variant.scss
  packages/react-variant-view/src/component/variantView/Variant.tsx
  packages/react-variant-view/src/component/variantViewMutationMapper/VariantViewMutationMapper.tsx
  packages/react-variant-view/src/image/mutationAssessor.png
  packages/react-variant-view/src/image/oncokb.png
  packages/react-variant-view/src/image/polyPhen-2.png
  packages/react-variant-view/src/image/siftFunnel.png
  packages/react-variant-view/src/index.tsx
  packages/react-variant-view/src/store/VariantStore.ts
  packages/react-variant-view/src/typings.d.ts
  packages/react-variant-view/src/util/AnnotationSummaryUtil.ts
  packages/react-variant-view/src/util/ApiClientUtils.ts
  packages/react-variant-view/src/util/Constants.ts
  packages/react-variant-view/src/util/VariantUtil.ts
  packages/react-variant-view/tsconfig.json
  packages/react-variant-view/tsconfig.test.json
  yarn.lock
Labels: cl-package

#3475 update GenomeNexus API client
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPIInternal-docs.json
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPIInternal.ts
Labels: chore

#3455 Independent display logic for sample treatments chart
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPI-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPI.ts
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal.ts
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/table/treatments/treatmentsTableUtil.tsx
Labels: enhancement

#3476 toJS call to avoid empty lists
  src/pages/studyView/StudyViewPageStore.ts
Labels: bug

#3467 Add Grcm38/mm10 when looking for mixed ref genomes
  src/shared/lib/referenceGenomeUtils.tsx
Labels: bug

#3479 update screenshots
  end-to-end-test/remote/screenshots/reference/group_by_detailed_type_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_methylation_enrichments_tab_two_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/handles_change_to_absolute_value_yaxis_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/handles_change_to_sort_of_xaxis_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_methylation_enrichments_tab_several_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_methylation_enrichments_tab_two_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_protein_enrichments_tab_several_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_protein_enrichments_tab_two_groups_element_chrome_1600x1000.png
Labels: chore

#3410 Add iframe on homepage sidebar that leads to offsite installation map
  src/appShell/App/PortalHeader.tsx
  src/config/IAppConfig.ts
  src/config/serverConfigDefaults.ts
  src/pages/staticPages/installations/InstallationMap.tsx
  src/pages/staticPages/installations/styles.scss
  src/routes.jsx
  src/shared/components/rightbar/RightBar.tsx
Labels: enhancement
