Repository cBioPortal/cbioportal-frontend, pull requests merged in 2020-05, with the labels that each got.

#3190 Point coexpression api back to public portal (from master)
  src/pages/resultsView/coExpression/CoExpressionTab.tsx
Labels: skip-changelog

#3197 Add TOC to tutorials page
  src/pages/staticPages/tutorials/Tutorials.tsx
  src/pages/staticPages/tutorials/styles.scss
Labels: enhancement

#3204 Add webinar 2
  src/pages/staticPages/tutorials/Tutorials.tsx
Labels: documentation

#3182 Allow cbioportal use oncokb biological data without token
  packages/react-mutation-mapper/src/component/column/Annotation.tsx
  packages/react-mutation-mapper/src/component/mutationMapper/MutationMapper.tsx
  packages/react-mutation-mapper/src/component/mutationTable/DefaultMutationTable.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKB.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbCard.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbSummaryTable.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbTooltip.tsx
  packages/react-mutation-mapper/src/component/oncokb/main.module.scss
  packages/react-mutation-mapper/src/component/track/OncoKbTrack.tsx
  packages/react-mutation-mapper/src/component/track/OncoKbTrackTooltip.tsx
  packages/react-mutation-mapper/src/model/MutationMapperDataFetcher.ts
  packages/react-mutation-mapper/src/model/MutationMapperStore.ts
  packages/react-mutation-mapper/src/store/DefaultMutationMapperDataFetcher.ts
  packages/react-mutation-mapper/src/store/DefaultMutationMapperStore.ts
  packages/react-mutation-mapper/src/util/DataFetcherUtils.ts
  packages/react-mutation-mapper/src/util/OncoKbUtils.ts
  src/appShell/App/Container.tsx
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
  src/pages/patientView/copyNumberAlterations/CopyNumberTableWrapper.spec.tsx
  src/pages/patientView/copyNumberAlterations/CopyNumberTableWrapper.tsx
  src/pages/patientView/copyNumberAlterations/column/AnnotationColumnFormatter.tsx
  src/pages/patientView/mutation/PatientViewMutationTable.spec.tsx
  src/pages/patientView/mutation/PatientViewMutationsTab.tsx
  src/pages/resultsView/mutation/ResultsViewMutationMapper.tsx
  src/pages/staticPages/tools/mutationMapper/StandaloneMutationMapper.tsx
  src/shared/components/mutationMapper/MutationMapperStore.ts
  src/shared/components/mutationTable/MutationTable.tsx
  src/shared/components/mutationTable/column/AnnotationColumnFormatter.tsx
  src/shared/lib/StoreUtils.ts
Labels: ready to review

#3199 Survival plots fix: show only OS/DFS/PFS/DSS
  src/pages/studyView/StudyViewPageStore.ts
  src/shared/lib/comparison/ComparisonStore.ts
Labels: bug, ready to review

#3206 update oncokb ts client
  packages/oncokb-ts-api-client/src/generated/OncoKbAPI-docs.json
  packages/oncokb-ts-api-client/src/generated/OncoKbAPI.ts
Labels: chore

#3202 Enrichments: fix p-value column tooltip
  src/pages/resultsView/enrichments/AlterationEnrichmentsTable.tsx
Labels: ready to review

#3203 Use single restore key for cbio redirection
  src/appBootstrapper.jsx
Labels: DO NOT MERGE

#3191 results view - remove survival tab and redirect survival to comparison survival tab
  end-to-end-test/package.json
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_delete_group_from_session_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/oncoprint.screenshot.spec.js
  end-to-end-test/remote/specs/core/oncoprint.spec.js
  end-to-end-test/remote/specs/core/results.logic.spec.js
  end-to-end-test/shared/specUtils.js
  src/pages/resultsView/ResultsViewPage.tsx
  src/pages/resultsView/ResultsViewPageHelpers.ts
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/survival/SurvivalTransitionTab.tsx
  src/routes.jsx
  src/shared/lib/redirectHelpers.ts
Labels: enhancement

#3214 Add webinar 3
  src/pages/staticPages/tutorials/Tutorials.tsx
Labels: documentation

#3215 Revert commit after migrate database (2.12.5)
  src/pages/patientView/patientHeader/style/clinicalAttributes.scss
  src/pages/resultsView/survival/SurvivalUtil.tsx
  src/pages/studyView/StudyViewPageStore.ts
  src/shared/lib/comparison/ComparisonStore.ts
Labels: ready to review

#3216 Don't invoke coexpression api when there are no samples
  src/pages/resultsView/coExpression/CoExpressionTab.tsx
Labels: bug

#3220 comparison - download sample group membership data in overlap tab
  src/pages/groupComparison/GroupComparisonUtils.spec.ts
  src/pages/groupComparison/GroupComparisonUtils.tsx
  src/pages/groupComparison/Overlap.tsx
  src/shared/lib/comparison/ComparisonStore.ts
Labels: needs-product-review

#3223 oncoprint - make comparison group clinical tracks based on queried studies (even virtual)
  src/pages/resultsView/ResultsViewPageStore.ts
Labels: enhancement

#3210 point to new api docs location
  src/pages/staticPages/webAPI/WebAPIPage.tsx
Labels: documentation

#3226 add webinar 4
  src/pages/staticPages/tutorials/Tutorials.tsx
  src/shared/components/userMessager/UserMessage.tsx
Labels: documentation

#3228 Merge master to release 3.4.0
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_delete_group_from_session_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_overlap_tab_upset_groups_selected_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/results.logic.spec.js
  env/release-3.4.0.sh
  src/pages/groupComparison/GroupComparisonUtils.spec.ts
  src/pages/groupComparison/GroupComparisonUtils.tsx
  src/pages/groupComparison/Overlap.tsx
  src/pages/resultsView/ResultsViewPage.tsx
  src/pages/resultsView/ResultsViewPageHelpers.ts
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/staticPages/datasetView/DatasetList.tsx
  src/pages/staticPages/tutorials/Tutorials.tsx
  src/pages/staticPages/webAPI/WebAPIPage.tsx
  src/routes.jsx
  src/shared/components/userMessager/UserMessage.tsx
  src/shared/lib/StoreUtils.ts
  src/shared/lib/comparison/ComparisonStore.ts
Labels: ready to review

#3198 add warning for studies with mixed genome build
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/querySummary/QuerySummary.tsx
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/studyPageHeader/StudyPageHeader.tsx
  src/pages/studyView/studyPageHeader/studySummary/StudySummary.tsx
  src/shared/components/query/QueryStore.ts
  src/shared/components/query/studyList/StudyList.tsx
  src/shared/lib/referenceGenomeUtils.spec.ts
  src/shared/lib/referenceGenomeUtils.ts
  src/shared/lib/referenceGenomeUtils.tsx
Labels: enhancement, ready to review

#3233 update api docs link
  src/pages/staticPages/webAPI/WebAPIPage.tsx
Labels: documentation

#3229 Fix linkout from cancer type summary when there is a session
  src/pages/resultsView/cancerSummary/CancerSummaryChart.tsx
  src/pages/resultsView/cancerSummary/CancerSummaryContainer.tsx
  src/pages/resultsView/cancerSummary/CancerSummaryContent.tsx
  src/shared/lib/redirectHelpers.ts
Labels: bug

#3230 ExpressionEnrichment: Show NA for groups having no data
  src/pages/resultsView/enrichments/EnrichmentsUtil.tsx
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/StudyViewUtils.tsx
  src/shared/lib/DataUtils.ts
Labels: bug

#3234 Datasets page: update column header text. Remove datasets footer lang…
  src/config/IAppConfig.ts
  src/config/serverConfigDefaults.ts
  src/pages/staticPages/datasetView/DatasetPage.tsx
  src/pages/staticPages/datasetView/styles.module.scss
Labels: enhancement

#3239 Update generated clients to fix api sync
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPI-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPI.ts
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal.ts
Labels: chore, skip-changelog

#3238 Expression enrichment: fix box plot labels when the data is in log2 format
  end-to-end-test/remote/screenshots/reference/enrichments_tab_coadread_tcga_pub_mrna_profile_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_mrna_enrichments_tab_several_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_mrna_enrichments_tab_two_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_comparison_tab_mrna_enrichments_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_mrna_enrichments_tab_several_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_mrna_enrichments_tab_two_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_comparison_tab_mrna_enrichments_element_chrome_1600x1000.png
  src/pages/resultsView/enrichments/ExpressionEnrichmentsBoxPlot.tsx
Labels: enhancement

#3246 Add webinar 5 + remove webinar banner 😢
  src/pages/staticPages/tutorials/Tutorials.tsx
  src/shared/components/userMessager/UserMessage.tsx
Labels: documentation

#3242 Use client posted data method to pass data for number of patients larger than a limit (2000) from study view to patient view
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
  src/pages/studyView/studyPageHeader/ActionButtons.tsx
Labels: enhancement, ready to review
