Repository cBioPortal/cbioportal-frontend, pull requests merged in 2020-09, with the labels that each got.

#3384 (Download tab) Disable generic assay download for now before deriving entities from query
  src/pages/resultsView/download/DownloadTab.tsx
Labels: bug

#3386 Study View: remove unwanted promises from initial loading
  src/pages/studyView/StudyViewPageStore.ts
Labels: bug, ready to review

#3391 Timeline: scrollbar overlaps bottom row when timeline is zoomed
  packages/cbioportal-clinical-timeline/src/Timeline.tsx
  packages/cbioportal-clinical-timeline/src/timeline.scss
Labels: bug

#3390 update screenshots post data change
  end-to-end-test/remote/screenshots/reference/a_error_message_should_be_shown_when_the_filterattributeid_is_not_available_for_the_study_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/check_for_survival_plots_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/filter_study_from_url_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/study_view_laml_tcga_clinical_data_clicked_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/when_quickly_adding_charts,_each_chart_should_get_proper_data._element_chrome_1600x1000.png
Labels: test

#3389 Remove deprecated DAT-related property
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal.ts
  src/config/IAppConfig.ts
Labels: bug

#3382 timeline - Special render in sample tracks for multiple simultaneous samples
  packages/cbioportal-clinical-timeline/src/TimelineTrack.tsx
  packages/cbioportal-clinical-timeline/src/index.tsx
  packages/cbioportal-clinical-timeline/src/svg/renderStack.tsx
  packages/cbioportal-clinical-timeline/src/types.ts
  src/pages/patientView/timeline2/SampleMarker.tsx
  src/pages/patientView/timeline2/TimelineWrapper.tsx
  src/pages/patientView/timeline2/TimelineWrapperUtils.ts
Labels: cl-prototype

#3387 Update MSI default grouping
  end-to-end-test/remote/screenshots/reference/the_msi_score_should_use_the_custom_bins,_then_the_msi_score_column_should_be_added_in_the_clinical_data_tab_element_chrome_1600x1000.png
  src/pages/studyView/StudyViewConfig.ts
Labels: bug

#3392 Clinical Timeline: Truncate long labels and provide tooltip
  packages/cbioportal-clinical-timeline/src/TrackHeader.tsx
  packages/cbioportal-frontend-commons/src/components/truncatedText/TruncatedText.spec.tsx
  packages/cbioportal-frontend-commons/src/components/truncatedText/TruncatedText.tsx
  packages/cbioportal-frontend-commons/src/index.tsx
  src/pages/resultsView/enrichments/EnrichmentsUtil.tsx
  src/shared/components/mutationTable/column/CancerTypeColumnFormatter.tsx
  src/shared/components/mutationTable/column/ProteinChangeColumnFormatter.tsx
  src/shared/components/mutationTable/column/SampleColumnFormatter.tsx
  src/shared/components/mutationTable/column/StudyColumnFormatter.tsx
Labels: enhancement

#3396 Fix localdb e2e-tests caused by changes in study_es_0
  .circleci/config.yml
  end-to-end-test/local/screenshots/reference/removes_sample_stylings_when_selecting_"none"_in_gene_selection_box_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/removes_sample_stylings_when_selecting_none_in_gene_selection_box_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_gsva_heatmap_track_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_mutation_and_copy_number_by_default_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_only_cna_types_when_mutation_checkbox_is_deselected_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_only_mutation_types_when_copy_number_is_de-selected_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_treatment_profile_heatmap_track_for_treatment_element_chrome_1600x1000.png
  end-to-end-test/local/specs/core/plotstab.spec.js
Labels: test

#3398 Patient view clinical info tooltip - do not link to fake gene panel id WXS
  src/pages/patientView/clinicalInformation/ClinicalInformationPatientTable.tsx
Labels: bug

#3400 Improve timeline data downloading
  package.json
  packages/cbioportal-clinical-timeline/src/Timeline.tsx
  src/pages/patientView/timeline/Timeline.tsx
  src/pages/patientView/timeline/timelineTSV.ts
  src/pages/patientView/timeline2/TimelineWrapper.tsx
  src/pages/patientView/timeline2/TimelineWrapperUtils.ts
  yarn.lock
Labels: cl-prototype

#3403 Fix and unskip more e2e tests
  end-to-end-test/remote/specs/core/home.spec.js
Labels: chore

#3405 (survival) Reset range after switch to another plot
  src/pages/groupComparison/Survival.tsx
  src/pages/resultsView/survival/SurvivalChart.tsx
Labels: bug

#3415 comparison urls should not be relative
  src/shared/api/urls.ts
Labels: bug

#3351 GC: generic assay implementation
  src/pages/groupComparison/CopyNumberEnrichments.tsx
  src/pages/groupComparison/GenericAssayEnrichments.tsx
  src/pages/groupComparison/GroupComparisonPage.tsx
  src/pages/groupComparison/GroupComparisonTabs.ts
  src/pages/groupComparison/MRNAEnrichments.tsx
  src/pages/groupComparison/MethylationEnrichments.tsx
  src/pages/groupComparison/MutationEnrichments.tsx
  src/pages/groupComparison/ProteinEnrichments.tsx
  src/pages/resultsView/ResultsViewPageHelpers.ts
  src/pages/resultsView/ResultsViewPageStoreUtils.ts
  src/pages/resultsView/comparison/ComparisonTab.tsx
  src/pages/resultsView/enrichments/AlterationEnrichmentsContainer.tsx
  src/pages/resultsView/enrichments/EnrichmentsDataSetDropdown.tsx
  src/pages/resultsView/enrichments/EnrichmentsUtil.spec.tsx
  src/pages/resultsView/enrichments/EnrichmentsUtil.tsx
  src/pages/resultsView/enrichments/ExpressionEnrichmentsBoxPlot.tsx
  src/pages/resultsView/enrichments/ExpressionEnrichmentsTable.tsx
  src/pages/resultsView/enrichments/GenericAssayEnrichmentsContainer.tsx
  src/pages/resultsView/enrichments/GenericAssayEnrichmentsTable.tsx
  src/pages/resultsView/enrichments/GenericAssayEnrichmentsTableDataStore.ts
  src/pages/resultsView/enrichments/MiniScatterChart.tsx
  src/pages/resultsView/enrichments/styles.module.scss
  src/pages/resultsView/enrichments/styles.module.scss.d.ts
  src/routes.jsx
  src/shared/lib/comparison/ComparisonStore.ts
  src/shared/model/EnrichmentRow.ts
  src/shared/model/ExpressionEnrichmentRow.ts
Labels: ready to review

#3418 (SV) KM plot derive priority from config or related clinical attribute
  end-to-end-test/remote/screenshots/reference/check_for_survival_plots_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/when_quickly_adding_charts,_each_chart_should_get_proper_data._element_chrome_1600x1000.png
  src/pages/resultsView/survival/SurvivalUtil.tsx
  src/pages/studyView/StudyViewPageStore.ts
  src/shared/lib/StoreUtils.ts
Labels: enhancement
