Repository cBioPortal/cbioportal-frontend, pull requests merged in 2020-02, with the labels that each got.

#3040 exclude mutation uncalled profile and fusion profile
  end-to-end-test/remote/screenshots/reference/download_tab_-_msk_impact_2017_with_alk_and_sos1_-_sos1_should_be_not_sequenced_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/download_tab_-_nsclc_tcga_broad_2016_for_query_egfr:_mut=t790m_amp_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/download_tab_-_nsclc_tcga_broad_2016_with_cdkn2a_mdm2_and_merged_track_mdm4_tp53_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/download_tab_-_nsclc_tcga_broad_2016_with_overlapping_tp53_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/download_tab_-_nsclc_tcga_broad_2016_with_tp53_element_chrome_1600x1000.png
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/ResultsViewPageStoreUtils.ts
  src/pages/resultsView/download/DownloadTab.tsx
Labels: cl-bug, ready to review

#3042 In README Docs, removed reference to API URL and .env; closes #7095
  README.md
Labels: documentation

#3048 Updated README to fix #7133
  README.md
Labels: documentation

#3047 survival - use only 2 digit precision for median months
  src/pages/resultsView/survival/SurvivalUtil.tsx
Labels: enhancement

#3057 do not clear selected study list when click query tab
  src/shared/components/query/QueryAndDownloadTabs.tsx
Labels: enhancement, ready to review

#3058 Add Software acknowledgment page
  src/appShell/App/PortalFooter.tsx
  src/config/IAppConfig.ts
  src/config/serverConfigDefaults.ts
  src/pages/staticPages/software/Software.tsx
  src/pages/staticPages/software/styles.scss
  src/routes.jsx
Labels: documentation

#2926 oncoprint - allow adding gaps to string-valued clinical tracks
  end-to-end-test/remote/screenshots/reference/coadread_tcga_pub_with_column_gaps_inserted_based_on_clinical_track_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_then_set_gene_order,_including_all_genes_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_then_set_sample_order,_including_all_samples_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/removes_top_treatment_track_successfully_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/oncoprint.screenshot.spec.js
  packages/cbioportal-frontend-commons/src/api/generated/GenomeNexusAPI-docs.json
  packages/cbioportal-frontend-commons/src/api/generated/GenomeNexusAPI.ts
  packages/cbioportal-frontend-commons/src/api/generated/GenomeNexusAPIInternal-docs.json
  packages/cbioportal-frontend-commons/src/api/generated/GenomeNexusAPIInternal.ts
  src/pages/staticPages/tools/oncoprinter/Oncoprinter.tsx
  src/shared/components/oncoprint/DeltaUtils.ts
  src/shared/components/oncoprint/ResultsViewOncoprint.tsx
  src/shared/components/oncoprint/controls/OncoprintControls.tsx
Labels: feature, needs-product-review, results.oncoprint

#3055 Use OncoKB basic endpoints for annotation service
  package.json
  packages/cbioportal-frontend-commons/package.json
  packages/cbioportal-frontend-commons/src/api/generated/OncoKbAPI-docs.json
  packages/cbioportal-frontend-commons/src/api/generated/OncoKbAPI.ts
  packages/cbioportal-frontend-commons/src/index.tsx
  packages/cbioportal-frontend-commons/src/lib/OncoKbUtils.ts
  packages/cbioportal-frontend-commons/src/lib/oncokb/OncoKB.ts
  packages/cbioportal-frontend-commons/src/lib/oncokb/OncoKbUtils.spec.tsx
  packages/cbioportal-frontend-commons/src/lib/oncokb/OncoKbUtils.ts
  packages/react-mutation-mapper/package.json
  packages/react-mutation-mapper/src/cache/OncoKbEvidenceCache.ts
  packages/react-mutation-mapper/src/component/column/Annotation.tsx
  packages/react-mutation-mapper/src/component/mutationMapper/MutationMapper.tsx
  packages/react-mutation-mapper/src/component/mutationTable/DefaultMutationTable.tsx
  packages/react-mutation-mapper/src/component/oncokb/ArticleAbstractItem.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKB.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbCard.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbTooltip.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbTreatmentTable.tsx
  packages/react-mutation-mapper/src/component/oncokb/ReferenceList.tsx
  packages/react-mutation-mapper/src/component/track/OncoKbTrackTooltip.tsx
  packages/react-mutation-mapper/src/model/MutationMapperStore.ts
  packages/react-mutation-mapper/src/model/OncoKb.ts
  packages/react-mutation-mapper/src/store/DefaultMutationMapperDataFetcher.ts
  packages/react-mutation-mapper/src/store/DefaultMutationMapperFilterApplier.ts
  packages/react-mutation-mapper/src/store/DefaultMutationMapperStore.ts
  packages/react-mutation-mapper/src/util/DataFetcherUtils.ts
  packages/react-mutation-mapper/src/util/OncoKbUtils.spec.tsx
  packages/react-mutation-mapper/src/util/OncoKbUtils.ts
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
  src/pages/patientView/copyNumberAlterations/CopyNumberTableWrapper.tsx
  src/pages/patientView/copyNumberAlterations/column/AnnotationColumnFormatter.tsx
  src/pages/patientView/mutation/PatientViewMutationsTab.tsx
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/mutation/Mutations.tsx
  src/pages/resultsView/mutation/ResultsViewMutationMapper.tsx
  src/pages/resultsView/mutation/ResultsViewMutationMapperStore.ts
  src/pages/staticPages/tools/mutationMapper/MutationMapperTool.tsx
  src/pages/staticPages/tools/mutationMapper/MutationMapperToolStore.ts
  src/pages/staticPages/tools/mutationMapper/StandaloneMutationMapper.tsx
  src/pages/staticPages/tools/oncoprinter/OncoprinterGeneticUtils.ts
  src/pages/staticPages/tools/oncoprinter/OncoprinterStore.ts
  src/pages/studyView/StudyViewPageStore.ts
  src/shared/cache/OncoKbEvidenceCache.ts
  src/shared/components/mutationMapper/MutationMapper.tsx
  src/shared/components/mutationMapper/MutationMapperStore.ts
  src/shared/components/mutationTable/MutationTable.tsx
  src/shared/components/mutationTable/column/AnnotationColumnFormatter.tsx
  src/shared/lib/CopyNumberUtils.ts
  src/shared/lib/OncoKbUtils.ts
  src/shared/lib/StoreUtils.ts
  src/shared/model/OncoKB.ts
  yarn.lock
Labels: feature

#3076 On timeline generalize sample label replacement
  src/pages/patientView/timeline/legacy.js
Labels: cl-prototype

#3078 update react-table types
  package.json
  packages/react-mutation-mapper/package.json
  yarn.lock
Labels: chore

#3079 Do not attach mutation type when it is not available
  package.json
  packages/cbioportal-frontend-commons/package.json
  packages/cbioportal-frontend-commons/src/lib/oncokb/OncoKbUtils.ts
Labels: bug

#3077 Adding bitly option for filter session
  src/pages/studyView/StudyViewPage.tsx
Labels: ready to review

#3087 Shorten the alteration text when there are more then 5 alterations associated with the treatment
  package.json
  packages/react-mutation-mapper/package.json
  packages/react-mutation-mapper/src/component/oncokb/OncoKbCard.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbTreatmentTable.tsx
Labels: oncokb

#3025 Generic assay frontend implementation
  end-to-end-test/local/specs/treatment.screenshot.spec.js
  end-to-end-test/local/specs/treatment.spec.js
  src/config/IAppConfig.ts
  src/config/serverConfigDefaults.ts
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/ResultsViewPageStoreUtils.spec.ts
  src/pages/resultsView/ResultsViewPageStoreUtils.ts
  src/pages/resultsView/ResultsViewURLWrapper.ts
  src/pages/resultsView/plots/LastPlotsTabSelectionForDatatype.spec.ts
  src/pages/resultsView/plots/LastPlotsTabSelectionForDatatype.ts
  src/pages/resultsView/plots/PlotsTab.tsx
  src/pages/resultsView/plots/PlotsTabUtils.spec.ts
  src/pages/resultsView/plots/PlotsTabUtils.tsx
  src/pages/resultsView/plots/QuickPlots.spec.ts
  src/pages/resultsView/plots/QuickPlots.ts
  src/pages/resultsView/plots/styles.scss
  src/shared/cache/GenericAssayMolecularDataCache.ts
  src/shared/components/oncoprint/DataUtils.spec.ts
  src/shared/components/oncoprint/DeltaUtils.spec.ts
  src/shared/components/oncoprint/DeltaUtils.ts
  src/shared/components/oncoprint/Oncoprint.tsx
  src/shared/components/oncoprint/OncoprintUtils.spec.ts
  src/shared/components/oncoprint/OncoprintUtils.ts
  src/shared/components/oncoprint/ResultsViewOncoprint.tsx
  src/shared/components/oncoprint/ResultsViewOncoprintUtils.spec.ts
  src/shared/components/oncoprint/ResultsViewOncoprintUtils.tsx
  src/shared/components/oncoprint/TooltipUtils.spec.ts
  src/shared/components/oncoprint/TooltipUtils.ts
  src/shared/components/oncoprint/controls/OncoprintControls.tsx
  src/shared/components/oncoprint/controls/styles.scss
  src/shared/components/oncoprint/tabularDownload.ts
  src/shared/components/query/QueryStore.ts
  src/shared/lib/GenericAssayUtils/GenericAssayCommonUtils.ts
  src/shared/lib/GenericAssayUtils/TreatmentUtils.ts
  vendor-bundles.webpack.config.js
Labels: enhancement
