Repository cBioPortal/cbioportal-frontend, pull requests merged in 2020-04, with the labels that each got.

#3133 Fix floating numbers while creating groups from bar chart
  end-to-end-test/remote/screenshots/reference/filter_study_from_url_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/when_quickly_adding_charts,_each_chart_should_get_proper_data._element_chrome_1600x1000.png
  src/pages/studyView/StudyViewUtils.tsx
Labels: ready to review

#3128 Add study name to quick search sample results
  src/shared/components/query/QueryAndDownloadTabs.tsx
  src/shared/components/query/quickSearch/QuickSearch.tsx
Labels: enhancement

#3132 make study view dropdown not refresh unnecessarily when removing a chart
  end-to-end-test/remote/specs/core/studyview.spec.js
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/addChartButton/AddChartButton.tsx
  src/pages/studyView/addChartButton/addChartByType/AddChartByType.tsx
  src/pages/studyView/tabs/SummaryTab.tsx
Labels: bug

#3137 oncoprint - fix bug with comparison group track available counts
  src/pages/groupComparison/GroupComparisonUtils.spec.ts
  src/pages/groupComparison/GroupComparisonUtils.tsx
  src/pages/resultsView/ResultsViewPageStore.ts
Labels: bug

#3136 study view - remove zoom effect on selected samples count
  src/pages/studyView/StudyViewPage.tsx
  src/pages/studyView/styles.module.scss
Labels: cl-style-tweak

#3138 Make language clearer for negative matches
  src/pages/patientView/trialMatch/TrialMatchTable.tsx
Labels: skip-changelog

#3139 OncoKB Card improvement
  package.json
  packages/react-mutation-mapper/package.json
  packages/react-mutation-mapper/src/component/oncokb/OncoKbTreatmentTable.tsx
  packages/react-mutation-mapper/src/util/OncoKbUtils.spec.tsx
  packages/react-mutation-mapper/src/util/OncoKbUtils.ts
Labels: bug

#3140 Fix oncokb icon in ie11
  src/rootImages/oncokb-oncogenic-1.svg
Labels: bug

#3120 Support grch38 in mutation mapper tool
  end-to-end-test/remote/specs/core/mutationMapperTool.spec.js
  src/config/IAppConfig.ts
  src/config/serverConfigDefaults.ts
  src/pages/staticPages/tools/mutationMapper/MutationMapperTool.tsx
  src/pages/staticPages/tools/mutationMapper/MutationMapperToolStore.ts
  src/pages/staticPages/tools/mutationMapper/resources/standaloneMutationDataExampleGrch37.txt
  src/pages/staticPages/tools/mutationMapper/resources/standaloneMutationDataExampleGrch38.txt
  src/pages/staticPages/tools/mutationMapper/resources/standaloneMutationDataExampleWithGenomicCoordinatesOnlyGrch37.txt
  src/pages/staticPages/tools/mutationMapper/resources/standaloneMutationDataExampleWithGenomicCoordinatesOnlyGrch38.txt
  src/shared/api/urls.ts
  src/shared/cache/GenomeNexusCache.ts
  src/shared/cache/GenomeNexusMutationAssessorCache.ts
  src/shared/cache/GenomeNexusMyVariantInfoCache.ts
  src/shared/components/mutationMapper/MutationMapperStore.ts
  src/shared/lib/MutationTableDownloadDataFetcher.ts
  src/shared/lib/referenceGenomeUtils.ts
Labels: feature

#2890 SV: support genomic charts
  end-to-end-test/remote/screenshots/reference/when_quickly_adding_charts,_each_chart_should_get_proper_data._element_chrome_1600x1000.png
  package.json
  packages/cbioportal-ts-api-client/package.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal.ts
  packages/cbioportal-ts-api-client/src/index.tsx
  src/pages/studyView/StudyViewPage.tsx
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/StudyViewUtils.spec.ts
  src/pages/studyView/StudyViewUtils.tsx
  src/pages/studyView/UserSelections.tsx
  src/pages/studyView/addChartButton/AddChartButton.tsx
  src/pages/studyView/addChartButton/addChartByType/AddChartByType.tsx
  src/pages/studyView/addChartButton/geneLevelSelection/GeneLevelSelection.tsx
  src/pages/studyView/addChartButton/geneLevelSelection/styles.module.scss
  src/pages/studyView/chartHeader/ChartHeader.tsx
  src/pages/studyView/charts/ChartContainer.tsx
  src/pages/studyView/charts/barChart/BarChart.tsx
  src/pages/studyView/studyPageHeader/StudyPageHeader.tsx
  src/pages/studyView/styles.scss
  src/pages/studyView/table/FixedHeaderTable.tsx
  src/pages/studyView/tabs/SummaryTab.tsx
  src/shared/components/GeneSelectionBox/OQLTextArea.tsx
Labels: feature

#3142 SV: fix genomic chart name when filter in present in url
  src/pages/studyView/StudyViewPageStore.ts
Labels: cl-bug

#3151 coexpression - show cytoband of x axis gene
  end-to-end-test/local/screenshots/reference/shows_gsva_scores_in_scatterplot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/coexpression_tab_coadread_tcga_pub_initial_load_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/coexpression_tab_coadread_tcga_pub_loc_scale_x_and_y_mutations_off_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/coexpression_tab_coadread_tcga_pub_log_scale_x_and_y_mutations_on_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/coexpression_tab_coadread_tcga_pub_log_scale_x_and_y_with_regression_line_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/coexpression_tab_coadread_tcga_pub_switch_profiles_+_regression_line_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/coexpression_tab_coadread_tcga_pub_switch_profiles_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/coexpression_tab_coadread_tcga_pub_switch_tabs_element_chrome_1600x1000.png
  src/pages/resultsView/coExpression/CoExpressionPlot.tsx
  src/pages/resultsView/coExpression/CoExpressionPlotUtils.ts
Labels: enhancement

#3153 Run module publish action only on the main repo
  .github/workflows/module-publish.yml
Labels: cl-bug

#2950 Patient Timeline Improvements
  end-to-end-test/remote/screenshots/reference/patient_view_lgg_ucsf_2014_p04_element_chrome_1600x1000.png
  package.json
  packages/cbioportal-frontend-commons/src/components/downloadControls/DownloadControls.tsx
  src/pages/patientView/timeline/Timeline.tsx
  src/pages/patientView/timeline/legacy.js
  src/pages/patientView/timeline/styles.scss
  src/pages/patientView/timeline/timeline-lib.js
  src/pages/patientView/timeline/timelineTSV.ts
  yarn.lock
Labels: enhancement

#3150 Dont include CNA gain or hetloss when querying DRIVER in OQL
  src/shared/lib/oql/AccessorsForOqlFilter.ts
  src/shared/lib/oql/oqlfilter.d.ts
  src/shared/lib/oql/oqlfilter.spec.ts
  src/shared/lib/oql/oqlfilter.ts
Labels: enhancement

#3154 Show timeline in genomic evolution tab
  end-to-end-test/remote/screenshots/reference/pvge_add_a_mutation_to_line_chart_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_heatmap_hide_labels_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_heatmap_with_two_mutations_selected_from_before_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_hover_a_mutation_with_heatmap_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_hover_a_mutation_with_line_chart_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_initial_view_with_line_chart_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_line_chart_log_scale_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_line_chart_with_data_range_y_axis_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_one_mutation_selected_with_heatmap_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_one_mutation_selected_with_line_chart_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_only_show_highlighted_in_line_chart_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_show_timeline_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_transpose_heatmap_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_uncluster_heatmap_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/genomicEvolution.screenshot.spec.js
  src/pages/patientView/PatientViewUrlWrapper.ts
  src/pages/patientView/mutation/PatientViewMutationsTab.tsx
Labels: enhancement

#3166 Add user message about cbioportal seminar (public, genie & msk portal only)
  src/shared/components/userMessager/UserMessage.tsx
Labels: skip-changelog

#3171 Update typescript and fix arising type errors
  package.json
  packages/cbioportal-frontend-commons/package.json
  packages/cbioportal-frontend-commons/src/components/editableSpan/EditableSpan.tsx
  packages/cbioportal-ts-api-client/package.json
  packages/genome-nexus-ts-api-client/package.json
  packages/oncokb-ts-api-client/package.json
  packages/react-mutation-mapper/package.json
  packages/react-mutation-mapper/src/store/DefaultMutationMapperStore.ts
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/copyNumberAlterations/CopyNumberTableWrapper.tsx
  src/pages/resultsView/ResultsViewPageStoreUtils.spec.ts
  src/pages/resultsView/plots/PlotsTab.tsx
  src/shared/api/urls.ts
  src/shared/components/GeneSelectionBox/GeneSymbolValidatorMessage.tsx
  src/shared/components/mutationMapper/MutationMapperStore.ts
  src/shared/components/oncoprint/OncoprintUtils.spec.ts
  src/shared/components/plots/BoxScatterPlot.tsx
  src/shared/components/query/QueryStore.ts
  src/shared/lib/LazyMobXCache.ts
  src/shared/lib/MutationInputParser.ts
  src/shared/lib/URLWrapper.ts
  yarn.lock
Labels: chore

#3177 Fix Oncoprint controls hidden while loading generic assay data
  end-to-end-test/local/specs/treatment.spec.js
  src/shared/components/oncoprint/ResultsViewOncoprint.tsx
  src/shared/components/oncoprint/controls/OncoprintControls.tsx
Labels: ready to review

#3167 Oncoprint: do not unnecessarily re-render clinical dropdown, losing scroll position
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/oncoprint/AddClinicalTracks.tsx
  src/pages/studyView/addChartButton/addChartByType/AddChartByType.tsx
  src/pages/studyView/table/FixedHeaderTable.tsx
  src/shared/components/oncoprint/controls/OncoprintControls.tsx
Labels: bug

#3163 Use a forked version of igv.js as a workaround for segment count limit
  package.json
  yarn.lock
Labels: cl-bug

#3186 add webinar section
  src/appShell/App/PortalHeader.tsx
  src/pages/staticPages/tutorials/Tutorials.tsx
Labels: documentation
