Repository cBioPortal/cbioportal-frontend, pull requests merged in 2021-06, with the labels that each got.

#3764 Fix Patient View PathwayMapper node tooltips
  package.json
  yarn.lock
Labels: bug

#3767 display driver annotation setting button when hover legend panel
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_mutation_tab_element_chrome_1600x1000.png
  src/pages/resultsView/mutation/DriverAnnotationProteinImpactTypeBadgeSelector.tsx
  src/pages/resultsView/mutation/Mutations.tsx
  src/pages/resultsView/mutation/ResultsViewMutationMapper.tsx
  src/pages/resultsView/mutation/badgeSelector.module.scss
  src/pages/resultsView/mutation/badgeSelector.module.scss.d.ts
  src/shared/components/mutationMapper/MutationMapper.tsx
Labels: style tweak

#3789 Change chunk size for oncokb fetches to spread over more requests
  src/shared/lib/StoreUtils.ts
Labels: performance

#3787 force browser caching on reference genome data
  src/shared/lib/StoreUtils.ts
Labels: enhancement

#3780 Convert variant scss to a module and clean up unused css
  packages/react-variant-view/src/component/variantView/Variant.module.scss
  packages/react-variant-view/src/component/variantView/Variant.module.scss.d.ts
  packages/react-variant-view/src/component/variantView/Variant.scss
  packages/react-variant-view/src/component/variantView/Variant.tsx
Labels: cl-package

#3763 Get clinvar from GN annotation endpoint
  packages/cbioportal-utils/src/annotation/MyVariantInfoAnnotationUtils.ts
  packages/react-mutation-mapper/src/component/clinvar/ClinVarSummary.tsx
  packages/react-mutation-mapper/src/component/clinvar/ClinvarHelper.ts
  packages/react-mutation-mapper/src/component/clinvar/ClinvarSummary.tsx
  packages/react-mutation-mapper/src/component/column/ClinVar.tsx
  packages/react-mutation-mapper/src/component/column/ClinvarInterpretation.tsx
  packages/react-mutation-mapper/src/component/column/HgvsHelper.ts
  packages/react-mutation-mapper/src/component/column/VariantAnnotationHelper.ts
  packages/react-mutation-mapper/src/component/dbsnp/DbsnpId.tsx
  packages/react-mutation-mapper/src/component/mutationTable/DefaultMutationTable.tsx
  packages/react-mutation-mapper/src/component/mutationTable/MutationColumnHelper.tsx
  packages/react-mutation-mapper/src/index.tsx
  packages/react-variant-view/src/component/featureTable/FeatureTable.tsx
  packages/react-variant-view/src/component/pathogenicity/ClinVarInterpretation.tsx
  packages/react-variant-view/src/component/pathogenicity/ClinvarInterpretation.tsx
  packages/react-variant-view/src/component/pathogenicity/Pathogenicity.tsx
  packages/react-variant-view/src/component/variantView/Variant.tsx
  packages/react-variant-view/src/util/Constants.ts
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/staticPages/tools/mutationMapper/MutationMapperToolStore.ts
  src/shared/components/mutationTable/MutationTable.tsx
  src/shared/components/mutationTable/column/ClinvarColumnFormatter.tsx
  src/shared/constants.ts
Labels: cl-package, enhancement

#3786 make legend selector working as a checkbox
  packages/react-mutation-mapper/src/component/filter/ProteinImpactTypeBadgeSelector.tsx
  packages/react-mutation-mapper/src/index.tsx
  src/pages/patientView/structuralVariant/column/AnnotationColumnFormatter.tsx
  src/pages/resultsView/mutation/DriverAnnotationProteinImpactTypeBadgeSelector.tsx
  src/shared/components/mutationMapper/MutationMapper.tsx
Labels: enhancement

#3800 Fix screenshot after new gene data table and expression data changes
  end-to-end-test/remote/screenshots/reference/check_for_survival_plots_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/filter_study_from_url_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/fusion_filter_filter_study_from_url_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/generic_assay_chart_should_be_added_in_the_summary_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/loads_a_virtual_study_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/msk_impact_2017_with_alk_and_sos1_-_sos1_should_be_not_sequenced_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_comparison_tab_clinical_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/profiled_in_tracks_in_multiple_study_with_sos1_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/when_quickly_adding_charts,_each_chart_should_get_proper_data._element_chrome_1600x1000.png
Labels: chore, test

#3801 Patient page: show Event Info column by default on structural variant table
  end-to-end-test/remote/screenshots/reference/patient_view_with_0_mutations_msk_impact_2017_p-0000053-t01-im3_element_chrome_1600x1000.png
  src/pages/patientView/structuralVariant/PatientViewStructuralVariantTable.tsx
Labels: enhancement

#3798 Query page sample count should show sum of each study's allSampleCount property
  src/shared/components/query/QueryStore.ts
  src/shared/components/query/StudySelectorStats.tsx
Labels: bug

#3804 Add timing to oncoprint render
  src/shared/components/oncoprint/Oncoprint.tsx
Labels: skip-changelog

#3812 Fix SVG file download error
  src/pages/groupComparison/UpSet.tsx
Labels: bug

#3818 Add wait for visible to stabilize e2e test and repair oql edit tests
  end-to-end-test/remote/specs/core/home.spec.js
  end-to-end-test/remote/specs/core/oncoprint.spec.js
Labels: test

#3823 Changes related to rfc 56 revert
  end-to-end-test/local/specs/core/groupComparison.screenshot.spec.js
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPI-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPI.ts
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal.ts
  src/test/CivicMockUtils.ts
  src/test/MutationMockUtils.ts
Labels: chore

#3793 Add Clinical Attributes to Mutations Tab in Results View
  end-to-end-test/local/screenshots/reference/shows_ascn_columns_for_study_where_some_samples_have_ascn_data_and_some_do_not_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/download_tab_-_msk_impact_2017_with_alk_and_sos1_-_sos1_should_be_not_sequenced_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/download_tab_-_nsclc_tcga_broad_2016_for_query_egfr:_mut=t790m_amp_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/download_tab_-_nsclc_tcga_broad_2016_with_cdkn2a_mdm2_and_merged_track_mdm4_tp53_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/download_tab_-_nsclc_tcga_broad_2016_with_overlapping_tp53_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/download_tab_-_nsclc_tcga_broad_2016_with_tp53_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_comparison_tab_clinical_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_mutex_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_microbiome_signature_tab_several_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_microbiome_signature_tab_two_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_mrna_enrichments_tab_several_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_mrna_enrichments_tab_two_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_comparison_tab_mutation_enrichments_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_mutex_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_lgg_ucsf_2014_p04_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_with_0_mutations_msk_impact_2017_p-0000053-t01-im3_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_heatmap_with_two_mutations_selected_from_before_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_hover_a_mutation_with_heatmap_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_initial_view_with_line_chart_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_one_mutation_selected_with_heatmap_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_one_mutation_selected_with_line_chart_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_show_timeline_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_bar_chart_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_log_scale__kruskal_wallis_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_percentage_stacked_bar_chart_exclude_overlapping_samples_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_stacked_bar_chart_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_stacked_bar_chart_horizontal_bars_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_stacked_bar_chart_swaped_axes_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_swaped_axes_kruskal_wallis_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_protein_enrichments_tab_two_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_comparison_tab_mutation_enrichments_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_mutex_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/when_quickly_adding_charts,_each_chart_should_get_proper_data._element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/mutationTable.spec.js
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/mutation/AddColumns.tsx
  src/pages/resultsView/mutation/Mutations.tsx
  src/pages/resultsView/mutation/ResultsViewMutationMapper.tsx
  src/pages/resultsView/mutation/ResultsViewMutationMapperStore.ts
  src/pages/resultsView/mutation/ResultsViewMutationTable.tsx
  src/pages/staticPages/tools/mutationMapper/MutationMapperToolStore.ts
  src/pages/staticPages/tools/mutationMapper/StandaloneMutationTable.tsx
  src/pages/studyView/addChartButton/addChartByType/AddChartByType.tsx
  src/pages/studyView/table/FixedHeaderTable.tsx
  src/shared/cache/ClinicalAttributeCache.ts
  src/shared/components/columnVisibilityControls/ColumnVisibilityControls.tsx
  src/shared/components/lazyMobXTable/LazyMobXTable.tsx
  src/shared/components/mutationTable/MutationTable.tsx
  src/shared/components/mutationTable/column/ClinicalAttributeColumnFormatter.tsx
  src/shared/components/oncoprint/controls/CustomDropdown.tsx
  src/shared/lib/ISortMetric.ts
  src/shared/lib/MutationTableDownloadDataFetcher.ts
Labels: feature

#3367 Add support for Uniprot PTM data
  packages/cbioportal-utils/src/index.tsx
  packages/cbioportal-utils/src/model/PostTranslationalModification.ts
  packages/cbioportal-utils/src/model/Uniprot.ts
  packages/cbioportal-utils/src/ptm/PtmUtils.spec.ts
  packages/cbioportal-utils/src/ptm/PtmUtils.ts
  packages/react-mutation-mapper/src/component/mutationMapper/MutationMapper.tsx
  packages/react-mutation-mapper/src/component/ptm/PtmAnnotationTable.tsx
  packages/react-mutation-mapper/src/component/track/PtmTrack.tsx
  packages/react-mutation-mapper/src/component/track/TrackPanel.tsx
  packages/react-mutation-mapper/src/component/track/TrackSelector.tsx
  packages/react-mutation-mapper/src/model/MutationMapperDataFetcher.ts
  packages/react-mutation-mapper/src/model/MutationMapperStore.ts
  packages/react-mutation-mapper/src/store/DefaultMutationMapperDataFetcher.ts
  packages/react-mutation-mapper/src/store/DefaultMutationMapperStore.ts
  packages/react-mutation-mapper/src/util/PtmUtils.ts
  packages/react-mutation-mapper/src/util/TrackUtils.ts
  src/config/IAppConfig.ts
  src/pages/resultsView/mutation/Mutations.tsx
  src/shared/components/mutationMapper/MutationMapper.tsx
  src/shared/components/mutationMapper/MutationMapperConfig.ts
  src/shared/components/mutationMapper/MutationMapperStore.ts
Labels: cl-prototype
