Repository cBioPortal/cbioportal-frontend, pull requests merged in 2021-12, with the labels that each got.

#3983 Timeline: color treatment tracks by category
  src/pages/patientView/timeline2/timeline_helpers.tsx
Labels: cl-prototype

#4075 In timeline add HTAN OHSU Image Icon
  src/pages/patientView/timeline2/TimelineWrapper.tsx
  src/pages/patientView/timeline2/timeline_helpers.tsx
Labels: cl-prototype

#4078 Only show help widget on public portal
  src/shared/components/HelpWidget/HelpWidget.tsx
Labels: skip-changelog

#4080 Fix exon track error when no exon in transcript
  packages/react-mutation-mapper/src/component/track/ExonTrack.tsx
Labels: bug

#4082 Fix PathwayMapper in Safari
  package.json
  yarn.lock
Labels: bug

#4079 Timeline: show zoom instruction
  packages/cbioportal-clinical-timeline/src/Timeline.tsx
  packages/cbioportal-clinical-timeline/src/timeline.scss
  src/shared/components/HelpWidget/styles.module.scss.d.ts
Labels: enhancement

#4087 Remove console statement
  src/shared/components/HelpWidget/HelpWidget.tsx
Labels: skip-changelog

#4083 Returns an empty list for undefined profileIds in isSampleProfiledInMultiple function
  src/shared/lib/isSampleProfiled.ts
Labels: bug

#4092 Use alteration type enum to detect mutation profile
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
  src/shared/lib/StoreUtils.ts
Labels: bug

#4104 Add back github friendly markdown support to static markdown component
  package.json
  src/shared/components/staticContent/StaticContent.tsx
  vendor-bundles.webpack.config.js
  yarn.lock
Labels: bug
