Repository cBioPortal/cbioportal-frontend, pull requests merged in 2021-02, with the labels that each got.

#3623 Fix webdriver manager not starting selenium
  .circleci/config.yml
  end-to-end-test/local/docker/screenshottest.sh
  end-to-end-test/package.json
  end-to-end-test/yarn.lock
Labels: test

#3497 Add option to hide NA bar for specific bar charts
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/StudyViewUtils.tsx
  src/pages/studyView/chartHeader/ChartHeader.tsx
  src/pages/studyView/charts/ChartContainer.tsx
  src/pages/studyView/charts/barChart/BarChart.tsx
  src/pages/studyView/tabs/SummaryTab.tsx
Labels: enhancement

#3626 Fix cohort link to patient page when length exceeds browser limit
  src/pages/studyView/studyPageHeader/ActionButtons.tsx
Labels: bug

#3617 Filter by TCGA PanCancer Atlas pathways in Results and Patient views
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_pathwaymapper_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_pathwaymapper_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_pathways_tab_msk_impact_2017_p-0000377_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_pathwaymapper_tab_element_chrome_1600x1000.png
  package.json
  yarn.lock
Labels: feature

#3624 Improve mutation annotation performance
  packages/cbioportal-utils/package.json
  packages/cbioportal-utils/src/mutation/MutationAnnotator.ts
  packages/react-mutation-mapper/package.json
  packages/react-mutation-mapper/src/component/lollipopPlot/Domain.tsx
  packages/react-mutation-mapper/src/store/DefaultMutationMapperStore.ts
  packages/react-variant-view/package.json
  src/shared/components/mutationMapper/MutationMapperStore.ts
Labels: cl-package

#3638 Treatments Selection Fix
  end-to-end-test/remote/screenshots/reference/can_filter_a_study_by_patient_treatments_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/can_filter_a_study_by_sample_treatments_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/studyview.spec.js
  src/pages/studyView/StudyViewPageStore.ts
Labels: bug

#3640 add generic assay category and binary test profile
  end-to-end-test/local/studies/lgg_ucsf_2014_test_generic_assay/data_mutational_signature_binary_v2.txt
  end-to-end-test/local/studies/lgg_ucsf_2014_test_generic_assay/data_mutational_signature_category_v2.txt
  end-to-end-test/local/studies/lgg_ucsf_2014_test_generic_assay/meta_mutational_signature_binary_v2.txt
  end-to-end-test/local/studies/lgg_ucsf_2014_test_generic_assay/meta_mutational_signature_category_v2.txt
Labels: test

#3622 Add tracks dropdown implementation
  end-to-end-test/local/screenshots/reference/shows_treatment_profile_heatmap_track_for_treatment_element_chrome_1600x1000.png
  end-to-end-test/local/specs/gsva.spec.js
  end-to-end-test/local/specs/treatment.screenshot.spec.js
  end-to-end-test/local/specs/treatment.spec.js
  end-to-end-test/remote/screenshots/reference/acc_tcga_with_clinical_and_heatmap_tracks_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/blca_tcga_with_clinical_and_heatmap_tracks_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/brca_tcga_pub_with_kras_nras_braf_and_methylation_heatmap_tracks_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/coadread_tcga_pub_with_clinical_and_heatmap_tracks_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/coadread_tcga_pub_with_column_gaps_inserted_based_on_clinical_track_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/hcc_inserm_fr_2015_with_genes_including_tert_-_it_should_show_orange_promoter_mutations_in_tert_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/msk_impact_2017_query_stk11:homdel_mut_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/msk_impact_2017_with_alk_and_sos1_-_sos1_should_be_not_sequenced_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/msk_impact_2017_with_sos1_-_sos1_should_be_not_sequenced_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/msk_impact_2017_with_sos1_with_cna_profile_-_sos1_should_not_be_sequenced_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/multiple_tracks_with_same_gene_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/profiled_in_tracks_in_a_combined_study_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/profiled_in_tracks_in_msk_impact_with_3_not_profiled_genes_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/profiled_in_tracks_in_multiple_study_with_sos1_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/removes_top_treatment_track_successfully_element_chrome_1600x1000.png
  end-to-end-test/shared/specUtils.js
  src/pages/groupComparison/GenericAssayEnrichments.tsx
  src/pages/groupComparison/GroupComparisonPage.tsx
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/comparison/ComparisonTab.tsx
  src/pages/resultsView/oncoprint/AddClinicalTracks.tsx
  src/pages/resultsView/oncoprint/AddTracks.tsx
  src/pages/resultsView/plots/PlotsTab.tsx
  src/pages/resultsView/styles.scss
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/addChartButton/AddChartButton.tsx
  src/pages/studyView/addChartButton/genericAssaySelection/GenericAssaySelection.tsx
  src/shared/components/oncoprint/OncoprintUtils.ts
  src/shared/components/oncoprint/ResultsViewOncoprint.tsx
  src/shared/components/oncoprint/ResultsViewOncoprintUtils.tsx
  src/shared/components/oncoprint/controls/CustomDropdown.tsx
  src/shared/components/oncoprint/controls/OncoprintControls.tsx
  src/shared/components/oncoprint/controls/styles.scss
  src/shared/lib/GenericAssayUtils/GenericAssayCommonUtils.ts
  src/shared/lib/comparison/ComparisonStore.ts
Labels: feature

#3635 Support OncoKB resistance oncogenicity
  packages/react-mutation-mapper/package.json
  packages/react-mutation-mapper/src/util/OncoKbUtils.ts
  yarn.lock
Labels: feature

#3644 A few cleanup tasks (removing unused dep, circular deps, Cheerio issue)
  packages/cbioportal-clinical-timeline/src/LineChartAxis.tsx
  packages/cbioportal-clinical-timeline/src/TimelineTrack.tsx
  packages/cbioportal-clinical-timeline/src/lib/lineChartAxisUtils.ts
  src/pages/home/HomePage.tsx
  src/shared/components/barGraph/BarGraph.tsx
  src/shared/components/rightbar/RightBar.tsx
  typings/missing.d.ts
  vendor-bundles.webpack.config.js
Labels: chore

#3645 Dont show study url warning in MSKCIS setting
  src/appBootstrapper.jsx
  src/appShell/App/usageAgreements/StudyAgreement.tsx
Labels: skip-changelog

#3646 Resistance oncogenicity should be considered as driver
  src/pages/resultsView/ResultsViewPageStoreUtils.ts
  src/shared/lib/StoreUtils.spec.ts
Labels: cl-external-api
