Repository cBioPortal/cbioportal-frontend, pull requests merged in 2021-07, with the labels that each got.

#3827 Add fraction to columns button and tabs in mutations table
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_mutation_tab_element_chrome_1600x1000.png
  src/pages/resultsView/mutation/AddColumns.tsx
Labels: feature

#3837 Fix some tests
  end-to-end-test/remote/screenshots/reference/filter_study_from_url_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/study_view_laml_tcga_clinical_data_clicked_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/when_quickly_adding_charts,_each_chart_should_get_proper_data._element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/studyview.spec.js
  env/custom.sh
Labels: test

#3835 Fix blank HGVSc column
  packages/react-mutation-mapper/src/component/column/Hgvsc.tsx
Labels: bug

#3838 Fix broken e2e test for HLA-A mutations
  end-to-end-test/remote/specs/core/data/hla_a_test_mutation_mapper_tool.txt
  end-to-end-test/remote/specs/core/mutationMapperTool.spec.js
  packages/cbioportal-utils/src/mutation/MutationAnnotator.spec.ts
  packages/cbioportal-utils/src/mutation/MutationAnnotator.ts
Labels: bug

#3864 Update screenshots
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_box_plot_color_by_mutation_count_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_box_plot_color_by_mutation_count_log_scale_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_box_plot_color_by_tumor_type_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_box_plot_color_by_tumor_type_highlight_categories_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_scatter_plot_color_by_mutation_count_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_scatter_plot_color_by_mutation_count_log_scale_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_scatter_plot_color_by_tumor_type_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_scatter_plot_color_by_tumor_type_highlight_categories_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_waterfall_plot_color_by_mutation_count_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_waterfall_plot_color_by_mutation_count_log_scale_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_waterfall_plot_color_by_tumor_type_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_waterfall_plot_color_by_tumor_type_highlight_categories_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_mutation_tab_element_chrome_1600x1000.png
Labels: test

#3860 (GC) Disable other dataType except continuous data for Generic Assay tab
  src/pages/resultsView/enrichments/EnrichmentsUtil.spec.tsx
  src/pages/resultsView/enrichments/EnrichmentsUtil.tsx
Labels: enhancement

#3868 Get rid of innacurate logging statement regarding mismatch screenshot
  end-to-end-test/shared/lib/testUtils.js
Labels: test

#3867 In e2e test reporter, add network and file props
  end-to-end-test/shared/wdio/customReporter.v6.js
  end-to-end-test/shared/wdio/wdio.conf.js
Labels: test

#3856 Only show "ERROR" on failed mutations instead of all mutations
  src/shared/cache/GenomeNexusCache.ts
  src/shared/components/mutationTable/column/ExonColumnFormatter.tsx
Labels: bug, genome-nexus

#3826 Add tooltip for annotation column
  end-to-end-test/local/screenshots/reference/displays_ascn_columns_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/does_not_display_ascn_columns_for_studies_with_no_ascn_data_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/does_not_show_ascn_columns_study_with_no_ascn_data_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_ascn_columns_for_study_where_some_samples_have_ascn_data_and_some_do_not_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_ascn_columns_for_study_with_ascn_data_element_chrome_1600x1000.png
  end-to-end-test/local/specs/core/patientview.screenshot.spec.js
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_lgg_ucsf_2014_p04_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_with_0_mutations_msk_impact_2017_p-0000053-t01-im3_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_heatmap_with_two_mutations_selected_from_before_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_hover_a_mutation_with_heatmap_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_initial_view_with_line_chart_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_one_mutation_selected_with_heatmap_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_one_mutation_selected_with_line_chart_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_show_timeline_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_mutation_tab_element_chrome_1600x1000.png
  packages/react-mutation-mapper/src/component/column/Annotation.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKB.tsx
  packages/react-mutation-mapper/src/index.tsx
  src/pages/patientView/copyNumberAlterations/CopyNumberTableWrapper.tsx
  src/pages/patientView/copyNumberAlterations/column/AnnotationColumnFormatter.tsx
  src/pages/patientView/mutation/PatientViewMutationTable.tsx
  src/pages/patientView/structuralVariant/PatientViewStructuralVariantTable.tsx
  src/pages/patientView/structuralVariant/column/AnnotationColumnFormatter.tsx
  src/rootImages/civic-logo-no-variants.png
  src/rootImages/civic-logo.png
  src/rootImages/mcg_logo.png
  src/rootImages/oncokb-icons.png
  src/shared/components/mutationTable/MutationTable.tsx
  src/shared/components/mutationTable/column/AnnotationColumnFormatter.tsx
  src/shared/components/mutationTable/column/annotation/AnnotationHeader.tsx
Labels: feature

#3846 Save Column Visibility & Add "Reset Columns" Button
  packages/cbioportal-frontend-commons/src/lib/ColumnVisibilityResolver.spec.ts
  packages/cbioportal-frontend-commons/src/lib/ColumnVisibilityResolver.ts
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/mutation/AddColumns.tsx
  src/pages/resultsView/mutation/Mutations.tsx
  src/pages/resultsView/mutation/ResultsViewMutationMapper.tsx
  src/pages/resultsView/mutation/ResultsViewMutationTable.tsx
  src/shared/components/columnVisibilityControls/ColumnVisibilityControls.tsx
  src/shared/components/lazyMobXTable/LazyMobXTable.tsx
  src/shared/components/mutationMapper/MutationMapper.tsx
  src/shared/components/mutationMapper/MutationMapperUserSelectionStore.ts
  src/shared/components/mutationTable/MutationTable.tsx
Labels: feature

#3876 Fix jitpack build failure
  src/shared/components/mutationTable/column/CosmicColumnFormatter.tsx
Labels: bug

#3880 Fix mutation table column hover detection bug
  src/shared/components/lazyMobXTable/LazyMobXTable.tsx
Labels: bug

#3799 Oncoprint performance optimizations
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_pathwaymapper_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/msk_impact_2017_with_sos1_with_cna_profile_-_sos1_should_not_be_sequenced_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_pathwaymapper_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_pathways_tab_msk_impact_2017_p-0000377-t03-im3_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_pathways_tab_msk_impact_2017_p-0000377_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/profiled_in_tracks_in_msk_impact_with_3_not_profiled_genes_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_pathwaymapper_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/oncoprint.screenshot.spec.js
  end-to-end-test/remote/specs/core/oncoprint.spec.js
  end-to-end-test/remote/specs/core/studyview.spec.js
  end-to-end-test/shared/specUtils.js
  package.json
  src/pages/patientView/mutation/oncoprint/MutationOncoprint.tsx
  src/pages/patientView/mutation/oncoprint/MutationOncoprintUtils.ts
  src/pages/patientView/pathwayMapper/PatientViewPathwayMapper.tsx
  src/pages/staticPages/tools/oncoprinter/Oncoprinter.tsx
  src/shared/cache/ClinicalDataCache.ts
  src/shared/components/oncoprint/DeltaUtils.ts
  src/shared/components/oncoprint/Oncoprint.tsx
  src/shared/components/oncoprint/OncoprintUtils.spec.ts
  src/shared/components/oncoprint/OncoprintUtils.ts
  src/shared/components/oncoprint/ResultsViewOncoprint.tsx
  src/shared/components/oncoprint/geneticrules.ts
  src/shared/lib/Colors.ts
  yarn.lock
Labels: enhancement

#3882 Webdriver.io: Use out-of-box json reporter instead of custom reporter
  end-to-end-test/package.json
  end-to-end-test/shared/wdio/it-override.js
  end-to-end-test/shared/wdio/merge-e2e-reports.js
  end-to-end-test/shared/wdio/wdio.conf.js
  end-to-end-test/yarn.lock
  package.json
Labels: test

#3881 Timeline: fix tooltip date formatting for negative days
  packages/cbioportal-clinical-timeline/src/lib/helpers.ts
Labels: bug

#3879 Hide logout button in cBioPortal header via portal.properties
  end-to-end-test/local/specs/hide-login-button.spec.js
  end-to-end-test/shared/specUtils.js
  src/appShell/App/PortalHeader.tsx
  src/config/IAppConfig.ts
Labels: devops

#3889 Fix localdb reporting on circleci
  .circleci/config.yml
  end-to-end-test/local/specs/performance.spec.js
  end-to-end-test/shared/wdio/merge-e2e-reports.js
Labels: test
