Repository cBioPortal/cbioportal-frontend, pull requests merged in 2021-11, with the labels that each got.

#4019 Do not make empty call to generic assay meta endpoint on patient view page
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
Labels: bug

#4033 Fix mobx error
  src/pages/studyView/studyPageHeader/StudyPageHeader.tsx
Labels: test

#4036 Update OncoKB client
  packages/oncokb-ts-api-client/src/generated/OncoKbAPI-docs.json
  packages/oncokb-ts-api-client/src/generated/OncoKbAPI.ts
Labels: chore

#4048 Turn on Timeline toxicity coloring for mskcc portal
  src/pages/patientView/timeline2/TimelineWrapper.tsx
  src/pages/patientView/timeline2/timeline_helpers.tsx
Labels: skip-changelog

#4049 Upgrade jquery and bootstrap
  package.json
  yarn.lock
Labels: dependencies

#4032 Don't show Unknown values in Clinical Comparison
  src/pages/groupComparison/ClinicalData.tsx
Labels: enhancement
