Repository cBioPortal/cbioportal-frontend, pull requests merged in 2021-09, with the labels that each got.

#3947 Use the oncokb oncogenic icon from oncokb-styles
  end-to-end-test/local/screenshots/reference/displays_ascn_columns_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/does_not_display_ascn_columns_for_studies_with_no_ascn_data_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/does_not_show_ascn_columns_study_with_no_ascn_data_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_ascn_columns_for_study_where_some_samples_have_ascn_data_and_some_do_not_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_ascn_columns_for_study_with_ascn_data_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_mutation_tab_element_chrome_1600x1000.png
  package.json
  packages/react-mutation-mapper/package.json
  src/pages/resultsView/plots/PlotsTabUtils.tsx
  src/rootImages/oncokb-icons.png
  src/rootImages/oncokb-oncogenic-1.svg
  src/shared/components/mutationTable/column/annotation/AnnotationHeader.tsx
  src/shared/components/oncoprint/TooltipUtils.ts
  yarn.lock
Labels: bug

#3955 Include a tip when yarn start throws dependency error
  README.md
Labels: documentation

#3870 Generic Assay Categorical/Binary chart
  end-to-end-test/local/screenshots/reference/generic_assay_pie_chart_should_be_added_in_the_summary_tab_element_chrome_1600x1000.png
  end-to-end-test/local/specs/core/studyview.screenshot.spec.js
  src/pages/studyView/StudyViewPage.tsx
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/StudyViewUtils.tsx
  src/pages/studyView/UserSelections.tsx
  src/pages/studyView/addChartButton/AddChartButton.tsx
  src/pages/studyView/studyPageHeader/StudyPageHeader.tsx
  src/pages/studyView/tabs/SummaryTab.tsx
  src/shared/lib/Colors.ts
Labels: ready to review

#3962 Add new user survey banner message for msk portals
  src/shared/components/userMessager/UserMessage.tsx
Labels: skip-changelog

#3967 Make bar chart tooltip range notation more clear
  src/pages/studyView/StudyViewUtils.spec.ts
  src/pages/studyView/StudyViewUtils.tsx
Labels: enhancement

#3917 Add timeline event colors for triage (add improve configuration)
  packages/cbioportal-clinical-timeline/src/TimelineStore.tsx
  packages/cbioportal-clinical-timeline/src/TimelineTrack.tsx
  packages/cbioportal-clinical-timeline/src/configureTracks.ts
  packages/cbioportal-clinical-timeline/src/types.ts
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
  src/pages/patientView/timeline2/TimelineWrapper.tsx
  src/pages/patientView/timeline2/timeline_helpers.tsx
Labels: DO NOT MERGE

#3972 Change Y Label for Survival Charts
  end-to-end-test/remote/screenshots/reference/no_session_survival_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_survival_tab_element_chrome_1600x1000.png
  src/pages/groupComparison/Survival.tsx
  src/pages/resultsView/survival/SurvivalUtil.tsx
Labels: cl-style-tweak

#3973 Put a different color for each timeline track
  packages/cbioportal-clinical-timeline/src/TimelineTrack.tsx
  packages/cbioportal-clinical-timeline/src/index.tsx
  packages/cbioportal-frontend-commons/src/index.tsx
  packages/cbioportal-frontend-commons/src/lib/getColor.ts
  packages/cbioportal-frontend-commons/src/lib/hashString.ts
  src/pages/patientView/timeline2/timeline_helpers.tsx
  src/shared/lib/URLWrapper.ts
Labels: cl-prototype

#3977 Fix portals not working when deployed on a subpath/
  src/appBootstrapper.jsx
  src/config/IAppConfig.ts
  src/config/config.ts
Labels: bug
