Repository cBioPortal/cbioportal-frontend, pull requests merged in 2021-05, with the labels that each got.

#3735 Remove year related attributes from comparison
  src/pages/groupComparison/ClinicalData.tsx
Labels: cl-prototype

#3731 Performance improvements for initial oncoprint load
  src/pages/resultsView/ResultsViewPageStore.ts
  src/shared/lib/complexKeyDataStructures/ComplexKeyCounter.spec.ts
  src/shared/lib/complexKeyDataStructures/ComplexKeyCounter.ts
  src/shared/lib/oql/oqlfilter.ts
Labels: performance

#3743 Calculate data types for structural variants
  src/pages/patientView/structuralVariant/column/AnnotationColumnFormatter.tsx
Labels: bug, oncokb

#3745 Update oncokb SV type to deletion when sv is intragnic
  packages/cbioportal-utils/src/oncokb/OncoKbUtils.ts
Labels: bug

#3746 On mutations tab don't wait for gene panel data
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/mutation/ResultsViewMutationMapper.tsx
Labels: performance

#3708 oncoprint - dont distinguish drivers for amp and homdel
  end-to-end-test/remote/screenshots/reference/acc_tcga_with_clinical_and_heatmap_tracks_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/blca_tcga_with_clinical_and_heatmap_tracks_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/brca_tcga_pub_with_kras_nras_braf_and_methylation_heatmap_tracks_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/coadread_tcga_pub_with_clinical_and_heatmap_tracks_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/coadread_tcga_pub_with_column_gaps_inserted_based_on_clinical_track_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_render_the_oncoprint_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/msk_impact_2017_query_stk11:homdel_mut_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/multiple_tracks_with_same_gene_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_render_the_oncoprint_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_should_cluster_heatmap_group_correctly_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_should_delete_clustered_heatmap_group_correctly_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_should_delete_non-clustered_heatmap_group_correctly_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_should_return_to_non-clustered_state_correctly_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_should_sort_patients_correctly_in_coadread_tcga_pub_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_should_sort_patients_correctly_in_gbm_tcga_pub_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_should_sort_samples_correctly_in_coadread_tcga_pub_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_should_sort_samples_correctly_in_gbm_tcga_pub_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_initial_patient_order_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_initial_sample_order_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_patient_order_1_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_patient_order_2_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_patient_order_3_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_patient_order_4_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_sample_order_1_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_sample_order_2_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_sample_order_3_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_sample_order_4_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_sample_order_5_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_clinical_tracks_sorted_-_sorted_sample_order_6_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_heatmap_tracks_sorted_-_sorted_patient_order_1_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_heatmap_tracks_sorted_-_sorted_sample_order_1_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_heatmap_tracks_sorted_-_sorted_sample_order_2_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_heatmap_tracks_sorted_-_sorted_sample_order_3_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_heatmap_tracks_sorted_-_sorted_sample_order_4_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_sorts_through_a_flow_with_heatmap_tracks_sorted_-_sorted_sample_order_5_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_annotated_by_oncokb_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_dont_color_by_driver_vs_vus_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_dont_color_by_mutation_type_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_hide_vus_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_start_by_set_gene_order,_then_set_sample_order_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_start_by_set_sample_order,_then_set_gene_order_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_then_set_gene_order,_including_all_genes_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_then_set_gene_order,_not_including_all_genes_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_then_set_sample_order,_including_all_samples_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_genetic_only_example_data_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/profiled_in_tracks_in_a_combined_study_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/profiled_in_tracks_in_multiple_study_with_sos1_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/removes_top_treatment_track_successfully_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_render_the_oncoprint_element_chrome_1600x1000.png
  src/shared/components/oncoprint/geneticrules.ts
Labels: style tweak

#3753 Use samplesWithUniqueKeys for coverage information
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
Labels: bug

#3758 Add VAF numerator and denominator to VAF chart tooltip
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
  src/pages/patientView/mutation/PatientViewMutationsTabUtils.tsx
  src/pages/patientView/mutation/oncoprint/MutationOncoprint.tsx
  src/pages/patientView/mutation/oncoprint/MutationOncoprintUtils.ts
  src/pages/patientView/timeline2/VAFChart.tsx
  src/pages/patientView/timeline2/VAFChartUtils.ts
  src/shared/lib/MutationUtils.tsx
Labels: enhancement

#3756 Add a screenshot test for pathways tab for single sample view
  end-to-end-test/remote/screenshots/reference/patient_view_pathways_tab_msk_impact_2017_p-0000377-t03-im3_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/screenshot.spec.js
Labels: test

#3762 Update api client and use new resource definition api for multiple studies
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal.ts
  src/pages/studyView/StudyViewPageStore.ts
Labels: performance

#3768 Fix loader indicator for modify query form
  src/pages/resultsView/ResultsViewPage.tsx
Labels: bug

#3765 Added "Deselect all" button: Resolved Issue #8541
  end-to-end-test/remote/screenshots/reference/when_quickly_adding_charts,_each_chart_should_get_proper_data._element_chrome_1600x1000.png
  src/pages/studyView/table/FixedHeaderTable.tsx
Labels: enhancement
