Repository cBioPortal/cbioportal-frontend, pull requests merged in 2021-01, with the labels that each got.

#3560 Fix routing issue for nested portals
  src/appBootstrapper.jsx
  src/config/IAppConfig.ts
  src/routes.jsx
  src/shared/lib/redirectHelpers.ts
Labels: bug

#3548 Allow '_SURVIVAL' word to occur in custom survival clin vars
  src/pages/studyView/tabs/SummaryTab.tsx
Labels: bug

#3541 Results page: settings button should never wrap
  src/pages/resultsView/querySummary/QuerySummary.tsx
Labels: style tweak

#3562 Remove IE11 e2e test job
  .circleci/config.yml
Labels: chore

#3563 E2E test for multi study view where both studies have treatments
  end-to-end-test/remote/screenshots/reference/loads_multiple_studies_with_treatments_tables_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/studyview.spec.js
Labels: automerge, test

#3569 Remove empty treatment filters from study view bookmark URL
  src/pages/studyView/StudyViewPageStore.ts
Labels: automerge, refactoring

#3458 Add Pathway Mapper to Patient View
  end-to-end-test/local/screenshots/reference/show_tooltip_for_patient_who_has_significant_v2_significant_signatures_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_pathwaymapper_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_pathwaymapper_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_lgg_ucsf_2014_p04_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_pathways_tab_msk_impact_2017_p-0000377_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_with_0_mutations_msk_impact_2017_p-0000053-t01-im3_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_pathwaymapper_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/show_tooltip_for_patient_who_has_significant_v2_significant_signatures_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/screenshot.spec.js
  package.json
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/PatientViewPageTabs.ts
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
  src/pages/patientView/pathwayMapper/PatientViewPathwayMapper.tsx
  src/pages/resultsView/pathwayMapper/PathwayMapperHelpers.ts
  src/pages/resultsView/pathwayMapper/ResultsViewPathwayMapper.tsx
  src/shared/lib/StoreUtils.ts
  src/shared/lib/pathwayMapper/PathwayMapperHelpers.spec.ts
  src/shared/lib/pathwayMapper/PathwayMapperHelpers.ts
  src/shared/lib/pathwayMapper/PathwayMapperMessageBox.tsx
  src/shared/lib/pathwayMapper/PathwayMapperTable.tsx
  yarn.lock
Labels: enhancement, feature

#3570 Add statistical caution info to comparison clinical tab
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_comparison_tab_clinical_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_survival_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_clinical_tab_bar_chart_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_clinical_tab_include_overlapping_samples_kruskal_wallis_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_clinical_tab_log_scale__kruskal_wallis_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_clinical_tab_percentage_stacked_bar_chart_exclude_overlapping_samples_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_clinical_tab_stacked_bar_chart_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_clinical_tab_stacked_bar_chart_horizontal_bars_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_clinical_tab_stacked_bar_chart_swaped_axes_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_clinical_tab_swaped_axes_kruskal_wallis_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_survival_tab_exclude_overlapping_samples_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_survival_tab_include_overlapping_samples_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_comparison_tab_clinical_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_survival_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_hover_a_mutation_with_line_chart_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_bar_chart_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_include_overlapping_samples_kruskal_wallis_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_log_scale__kruskal_wallis_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_percentage_stacked_bar_chart_exclude_overlapping_samples_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_stacked_bar_chart_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_stacked_bar_chart_horizontal_bars_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_stacked_bar_chart_swaped_axes_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_swaped_axes_kruskal_wallis_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_survival_tab_exclude_overlapping_samples_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_survival_tab_include_overlapping_samples_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_comparison_tab_clinical_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_survival_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/when_adding_chart_with_categories_more_than_the_pie2table_threshold,_the_pie_chart_should_be_converted_to_table_element_chrome_1600x1000.png
  src/pages/groupComparison/ClinicalData.tsx
  src/pages/groupComparison/GroupComparisonUtils.tsx
  src/pages/groupComparison/Survival.tsx
Labels: cl-prototype

#3571 (GC )hide columns for clinical tab
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_comparison_tab_clinical_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_clinical_tab_bar_chart_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_clinical_tab_include_overlapping_samples_kruskal_wallis_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_clinical_tab_log_scale__kruskal_wallis_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_clinical_tab_percentage_stacked_bar_chart_exclude_overlapping_samples_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_clinical_tab_stacked_bar_chart_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_clinical_tab_stacked_bar_chart_horizontal_bars_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_clinical_tab_stacked_bar_chart_swaped_axes_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_clinical_tab_swaped_axes_kruskal_wallis_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_comparison_tab_clinical_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_hover_a_mutation_with_line_chart_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_bar_chart_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_include_overlapping_samples_kruskal_wallis_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_log_scale__kruskal_wallis_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_percentage_stacked_bar_chart_exclude_overlapping_samples_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_stacked_bar_chart_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_stacked_bar_chart_horizontal_bars_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_stacked_bar_chart_swaped_axes_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_swaped_axes_kruskal_wallis_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_comparison_tab_clinical_element_chrome_1600x1000.png
  src/pages/groupComparison/ClinicalDataEnrichmentsTable.tsx
Labels: enhancement

#3572 Fix caution warning for session urls
  .circleci/config.yml
  src/pages/groupComparison/Survival.tsx
Labels: cl-prototype

#3573 Fix error in loading chart data that are in user preference
  src/pages/studyView/StudyViewPageStore.ts
Labels: bug

#3574 Fix broken PFAM domain tooltip
  packages/react-mutation-mapper/src/component/lollipopPlot/DomainTooltip.tsx
Labels: bug

#3448 Improve support of custom data
  end-to-end-test/remote/screenshots/reference/when_quickly_adding_charts,_each_chart_should_get_proper_data._element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/studyview.spec.js
  package.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPI-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPI.ts
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal.ts
  src/AppStore.ts
  src/appShell/App/PortalHeader.tsx
  src/pages/groupComparison/comparisonGroupManager/ComparisonGroupManager.tsx
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/ResultsViewPageStoreUtils.ts
  src/pages/studyView/StudyViewPage.tsx
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/StudyViewUtils.spec.ts
  src/pages/studyView/StudyViewUtils.tsx
  src/pages/studyView/UserSelections.tsx
  src/pages/studyView/addChartButton/AddChartButton.tsx
  src/pages/studyView/addChartButton/addChartByType/AddChartByType.tsx
  src/pages/studyView/addChartButton/addChartByType/styles.module.scss
  src/pages/studyView/addChartButton/addChartByType/styles.module.scss.d.ts
  src/pages/studyView/addChartButton/customCaseSelection/CustomCaseSelection.tsx
  src/pages/studyView/addChartButton/customCaseSelection/CustomCaseSelectionUtils.spec.ts
  src/pages/studyView/addChartButton/customCaseSelection/CustomCaseSelectionUtils.tsx
  src/pages/studyView/addChartButton/styles.module.scss
  src/pages/studyView/addChartButton/styles.module.scss.d.ts
  src/pages/studyView/studyPageHeader/StudyPageHeader.tsx
  src/pages/studyView/tabs/SummaryTab.tsx
  src/shared/api/ComparisonGroupClient.ts
  src/shared/api/sessionServiceAPI.ts
  src/shared/components/dataAccessTokens/DataAccessTokensDropdown.tsx
  yarn.lock
Labels: feature

#3581 remove build of image from fingerprint step
  .circleci/config.yml
  end-to-end-test/local/runtime-config/db_content_fingerprint.sh
Labels: test

#3584 Fix flakey e2e
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_bar_chart_chi_squared_test_element_chrome_1600x1000.png
Labels: test

#3557 add isoform mskcc for signal variant page GN query
  packages/react-variant-view/src/component/headerAnnotation/HeaderAnnotation.tsx
  packages/react-variant-view/src/store/VariantStore.ts
Labels: cl-package

#3588 Support study view without any molecuar profiles
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/addChartButton/AddChartButton.tsx
Labels: bug

#3591 Fix CNA sort in oncoprint
  end-to-end-test/remote/screenshots/reference/oncoprint_should_sort_patients_correctly_in_coadread_tcga_pub_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_should_sort_samples_correctly_in_coadread_tcga_pub_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_annotated_by_oncokb_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_dont_color_by_mutation_type_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_hide_vus_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_then_set_gene_order,_including_all_genes_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data,_then_set_gene_order,_not_including_all_genes_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_example_data_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprinter_genetic_only_example_data_element_chrome_1600x1000.png
  src/shared/components/oncoprint/SortUtils.ts
Labels: bug

#3585 Include OncoKB diagnostic and prognostic implications
  end-to-end-test/local/screenshots/reference/displays_ascn_columns_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/does_not_display_ascn_columns_for_studies_with_no_ascn_data_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/does_not_show_ascn_columns_study_with_no_ascn_data_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_ascn_columns_for_study_where_some_samples_have_ascn_data_and_some_do_not_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_ascn_columns_for_study_with_ascn_data_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_lgg_ucsf_2014_p04_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_heatmap_with_two_mutations_selected_from_before_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_hover_a_mutation_with_heatmap_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_hover_a_mutation_with_line_chart_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_initial_view_with_line_chart_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_one_mutation_selected_with_heatmap_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_one_mutation_selected_with_line_chart_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_show_timeline_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/oncokb.spec.js
  packages/cbioportal-utils/src/model/OncoKB.ts
  packages/cbioportal-utils/src/oncokb/OncoKbUtils.ts
  packages/react-mutation-mapper/package.json
  packages/react-mutation-mapper/src/component/column/Annotation.tsx
  packages/react-mutation-mapper/src/component/oncokb/AnnotationIcon.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKB.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbCard.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbCardBody.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbCardLevelsOfEvidenceDropdown.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbCardTreatmentContent.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbHelper.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbTooltip.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbTreatmentTable.tsx
  packages/react-mutation-mapper/src/component/oncokb/ReferenceList.tsx
  packages/react-mutation-mapper/src/component/oncokb/main.module.scss
  packages/react-mutation-mapper/src/component/oncokb/main.module.scss.d.ts
  packages/react-mutation-mapper/src/component/oncokb/oncokb.scss
  packages/react-mutation-mapper/src/component/oncokb/oncokbCard/BiologicalContent.tsx
  packages/react-mutation-mapper/src/component/oncokb/oncokbCard/EvidenceReferenceContent.tsx
  packages/react-mutation-mapper/src/component/oncokb/oncokbCard/ImplicationContent.tsx
  packages/react-mutation-mapper/src/util/OncoKbUtils.ts
  src/pages/patientView/copyNumberAlterations/column/AnnotationColumnFormatter.tsx
  src/pages/patientView/oncokb/OtherBiomarkerAnnotation.tsx
  yarn.lock
Labels: feature, oncokb, ready to review

#3600 Use MSI_TYPE to determine the MSI-H annotation in patient view
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
  src/shared/constants.ts
  src/shared/lib/StoreUtils.ts
Labels: enhancement

#3613 OncoKB Card minor changes
  packages/cbioportal-clinical-timeline/src/svg/getSvg.ts
  packages/cbioportal-clinical-timeline/src/svg/renderStack.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbCardTitle.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbHelper.tsx
  packages/react-mutation-mapper/src/component/oncokb/oncokb.scss
  src/pages/patientView/PatientViewPage.tsx
Labels: bug

#3614 Fix annotation tracks bug
  packages/react-mutation-mapper/src/component/column/HotspotAnnotation.tsx
  packages/react-mutation-mapper/src/component/hotspot/HotspotInfo.tsx
  packages/react-mutation-mapper/src/component/track/HotspotTrack.tsx
  packages/react-mutation-mapper/src/component/track/OncoKbTrack.tsx
  packages/react-mutation-mapper/src/component/track/OncoKbTrackTooltip.tsx
  packages/react-mutation-mapper/src/component/track/PtmTrack.tsx
  packages/react-mutation-mapper/src/index.tsx
Labels: bug

#3566 Display interpretation instead of ClinVar ID
  end-to-end-test/remote/specs/core/mutationTable.spec.js
  packages/react-mutation-mapper/src/component/clinvar/ClinVarId.tsx
  packages/react-mutation-mapper/src/component/clinvar/ClinVarSummary.tsx
  packages/react-mutation-mapper/src/component/column/ClinVar.tsx
  packages/react-mutation-mapper/src/component/column/MyVariantInfoHelper.tsx
  packages/react-mutation-mapper/src/component/mutationTable/MutationColumnHelper.tsx
  packages/react-mutation-mapper/src/index.tsx
  packages/react-variant-view/src/component/pathogenicity/ClinVarInterpretation.tsx
  src/shared/components/mutationTable/MutationTable.tsx
  src/shared/components/mutationTable/column/ClinVarColumnFormatter.tsx
Labels: automerge, feature
