Repository cBioPortal/cbioportal-frontend, pull requests merged in 2021-08, with the labels that each got.

#3891 fix hover detection bug
  src/shared/components/lazyMobXTable/LazyMobXTable.tsx
Labels: bug

#3895 Update api documents
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPI-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPI.ts
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal.ts
  src/pages/resultsView/ResultsViewPageStore.spec.ts
  src/shared/components/query/CancerStudyTreeData.ts
Labels: chore

#3694 Generic Assay plots tab implementation(Categorical / Binary)
  end-to-end-test/local/screenshots/reference/show_binary_vs_mutation_count_plot_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/show_binary_vs_os_status_plot_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/show_category_vs_mutation_count_plot_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/show_category_vs_os_status_plot_element_chrome_1600x1000.png
  end-to-end-test/local/specs/core/plotstab.screenshot.spec.js
  end-to-end-test/remote/specs/core/plots.screenshot.spec.js
  end-to-end-test/shared/specUtils.js
  src/config/serverConfigDefaults.ts
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/plots/PlotsTab.tsx
  src/pages/resultsView/plots/PlotsTabUtils.spec.ts
  src/pages/resultsView/plots/PlotsTabUtils.tsx
  src/shared/cache/GenericAssayMolecularDataCache.ts
  src/shared/lib/GenericAssayUtils/GenericAssayCommonUtils.ts
Labels: ready to review

#3890 Add link to filtered study view + Fix URL generation
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/mutation/ResultsViewMutationMapper.tsx
  src/pages/resultsView/mutation/ResultsViewMutationMapperStore.ts
  src/pages/resultsView/querySummary/QuerySummary.tsx
  src/pages/resultsView/querySummary/QuerySummaryUtils.tsx
  src/shared/api/urls.ts
  src/shared/components/mutationMapper/MutationMapperDataStore.ts
Labels: feature

#3900 Fix error fetching only SV enrichments
  src/shared/lib/comparison/ComparisonStore.ts
Labels: bug

#3897 Add circleci job test e2e against backend master
  .circleci/config.yml
  env/master.sh
Labels: test

#3887 Study View: Fix exporting cancer study table
  src/pages/studyView/StudyViewPageStore.ts
Labels: bug

#3906 Fix bug relating to molecularData preload with massive data
  src/pages/resultsView/ResultsViewPageStore.ts
Labels: bug

#3912 SV: ignore alterationFilter while checking initial filter state
  src/pages/studyView/StudyViewPageStore.ts
Labels: bug

#3888 Adding an Alteration Amount column to the download data table
  src/pages/resultsView/cancerSummary/CancerSummaryChart.spec.tsx
  src/pages/resultsView/cancerSummary/CancerSummaryChart.tsx
  src/pages/resultsView/cancerSummary/CancerSummaryContent.tsx
Labels: enhancement

#3875 Add Exon Track to Mutations Tab with Tooltip and Highlight Functionality
  packages/cbioportal-utils/src/exon/ExonUtils.spec.ts
  packages/cbioportal-utils/src/exon/ExonUtils.ts
  packages/cbioportal-utils/src/index.tsx
  packages/cbioportal-utils/src/model/Exon.ts
  packages/react-mutation-mapper/src/component/lollipopPlot/LollipopPlotNoTooltip.tsx
  packages/react-mutation-mapper/src/component/track/ExonTrack.tsx
  packages/react-mutation-mapper/src/component/track/HotspotTrack.tsx
  packages/react-mutation-mapper/src/component/track/OncoKbTrack.tsx
  packages/react-mutation-mapper/src/component/track/PtmTrack.tsx
  packages/react-mutation-mapper/src/component/track/Track.tsx
  packages/react-mutation-mapper/src/component/track/TrackCircle.tsx
  packages/react-mutation-mapper/src/component/track/TrackItem.tsx
  packages/react-mutation-mapper/src/component/track/TrackPanel.tsx
  packages/react-mutation-mapper/src/component/track/TrackRect.tsx
  packages/react-mutation-mapper/src/component/track/TrackSelector.tsx
  packages/react-mutation-mapper/src/util/FilterUtils.ts
  packages/react-mutation-mapper/src/util/LabelUtils.tsx
  packages/react-mutation-mapper/src/util/TrackUtils.ts
  src/shared/components/mutationMapper/MutationMapper.tsx
Labels: ready to review, feature

#3920 Adding new dataset column for Mass Spectrometry
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPI-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPI.ts
  src/pages/resultsView/ResultsViewPageStore.spec.ts
  src/pages/staticPages/datasetView/DatasetList.tsx
Labels: enhancement

#3845 Add drugs to Civic model
  packages/cbioportal-utils/src/civic/CivicDataFetcher.ts
  packages/cbioportal-utils/src/civic/CivicUtils.ts
  packages/cbioportal-utils/src/model/Civic.ts
  packages/react-mutation-mapper/src/component/civic/Civic.spec.tsx
  packages/react-mutation-mapper/src/component/civic/Civic.tsx
  packages/react-mutation-mapper/src/component/civic/CivicCard.tsx
  packages/react-mutation-mapper/src/component/column/Annotation.tsx
  packages/react-mutation-mapper/src/component/mutationTable/DefaultMutationTable.tsx
  packages/react-mutation-mapper/src/model/MutationMapperStore.ts
  packages/react-mutation-mapper/src/store/DefaultMutationMapperStore.ts
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
  src/pages/patientView/copyNumberAlterations/CopyNumberTableWrapper.tsx
  src/pages/patientView/copyNumberAlterations/column/AnnotationColumnFormatter.tsx
  src/shared/components/mutationTable/MutationTable.tsx
  src/shared/components/mutationTable/column/AnnotationColumnFormatter.tsx
  src/shared/lib/CivicUtils.ts
  src/test/CivicMockUtils.ts
Labels: enhancement

#3935 Add study view screenshot test for tcga pancancer atlas studies
  end-to-end-test/remote/screenshots/reference/tcga_pancancer_atlas_page_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/studyview.spec.js
Labels: test
