Repository cBioPortal/cbioportal-frontend, pull requests merged in 2022-02, with the labels that each got.

#4160 Revert "Show namespace columns in MAF file in Mutation Table component"
  end-to-end-test/local/specs/namespace-columns-in-mutation-tables.spec.js
  env/custom.sh
  env/rfc56_annot_settings_menu.sh
  src/config/IAppConfig.ts
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/mutation/PatientViewMutationTable.tsx
  src/pages/patientView/mutation/PatientViewMutationsDataStore.ts
  src/pages/patientView/mutation/PatientViewMutationsTab.tsx
  src/pages/resultsView/mutation/ResultsViewMutationMapper.tsx
  src/pages/resultsView/mutation/ResultsViewMutationMapperStore.ts
  src/pages/resultsView/mutation/ResultsViewMutationTable.tsx
  src/pages/staticPages/tools/mutationMapper/StandaloneMutationMapper.tsx
  src/pages/staticPages/tools/mutationMapper/StandaloneMutationTable.tsx
  src/shared/components/mutationMapper/MutationMapperStore.ts
  src/shared/components/mutationMapper/MutationMapperUtils.spec.ts
  src/shared/components/mutationMapper/MutationMapperUtils.ts
  src/shared/components/mutationTable/MutationTable.tsx
  src/shared/components/mutationTable/MutationTableUtils.ts
  src/shared/components/mutationTable/column/CategoricalNamespaceColumnFormatter.tsx
  src/shared/components/mutationTable/column/NumericNamespaceColumnFormatter.tsx
Labels: revert

#4170 Genome Nexus api clients sync
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPIInternal-docs.json
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPIInternal.ts
Labels: chore

#4175 Fix hrefs on MSKTabs (for opening directly in new tab)
  src/pages/groupComparison/GroupComparisonPage.tsx
  src/pages/resultsView/ResultsViewPage.tsx
  src/pages/studyView/StudyViewPage.tsx
  src/shared/components/MSKTabs/MSKTabs.tsx
Labels: bug

#4165 Add genomic coordinates to exon track tooltip
  packages/cbioportal-utils/src/exon/ExonUtils.spec.ts
  packages/cbioportal-utils/src/exon/ExonUtils.ts
  packages/cbioportal-utils/src/model/Exon.ts
  packages/react-mutation-mapper/src/component/track/ExonTrack.tsx
  packages/react-mutation-mapper/src/model/MutationMapperStore.ts
  packages/react-mutation-mapper/src/store/DefaultMutationMapperStore.ts
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/staticPages/tools/mutationMapper/MutationMapperToolStore.ts
  src/shared/components/mutationMapper/MutationMapperStore.ts
  src/shared/lib/StoreUtils.ts
Labels: enhancement

#4182 Rename timeline folder in patientview
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/mutation/PatientViewMutationsTab.tsx
  src/pages/patientView/mutation/PatientViewMutationsTabUtils.tsx
  src/pages/patientView/timeline/ClinicalEventsTables.tsx
  src/pages/patientView/timeline/SampleMarker.tsx
  src/pages/patientView/timeline/TimelineWrapper.tsx
  src/pages/patientView/timeline/TimelineWrapperUtils.ts
  src/pages/patientView/timeline/VAFChart.tsx
  src/pages/patientView/timeline/VAFChartControls.tsx
  src/pages/patientView/timeline/VAFChartHeader.tsx
  src/pages/patientView/timeline/VAFChartUtils.spec.ts
  src/pages/patientView/timeline/VAFChartUtils.ts
  src/pages/patientView/timeline/VAFChartWrapper.tsx
  src/pages/patientView/timeline/VAFChartWrapperStore.tsx
  src/pages/patientView/timeline/styles.scss
  src/pages/patientView/timeline/timelineDataUtils.ts
  src/pages/patientView/timeline/timeline_helpers.spec.tsx
  src/pages/patientView/timeline/timeline_helpers.tsx
Labels: skip-changelog

#4189 Fix heatmap screenshots (heatmap working again)
  end-to-end-test/remote/screenshots/reference/filter_study_from_url_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/study_view_laml_tcga_clinical_data_clicked_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/when_quickly_adding_charts,_each_chart_should_get_proper_data._element_chrome_1600x1000.png
Labels: test

#4186 Fix bug where a comparison group has no survival data
  src/pages/resultsView/survival/SurvivalChart.tsx
Labels: bug

#4183 Change TumorColumnFormatter to support structural variant alterations (two genes)
  src/pages/patientView/mutation/column/TumorColumnFormatter.tsx
  src/pages/patientView/structuralVariant/PatientViewStructuralVariantTable.tsx
  src/shared/lib/StoreUtils.ts
Labels: bug

#4191 Don't show legacy tooltip (qtip) when hovering VAF plot on patient page
  src/pages/patientView/vafPlot/legacyVAFCode.js
Labels: bug
