Repository cBioPortal/cbioportal-frontend, pull requests merged in 2022-08, with the labels that each got.

#4343 Set data limit and add warning message for study view clinical tab
  end-to-end-test/local/runtime-config/portal.properties
  src/config/IAppConfig.ts
  src/config/serverConfigDefaults.ts
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/tabs/ClinicalDataTab.tsx
Labels: enhancement

#4349 Update more screenshots after data changes
  end-to-end-test/remote/screenshots/reference/generic_assay_chart_should_be_added_in_the_summary_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_page_pathwaymapper_tab_with_unprofiled_genes_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/tcga_pancancer_atlas_page_element_chrome_1600x1000.png
Labels: test

#4353 Update screenshots after data changes
  end-to-end-test/remote/screenshots/reference/patient_view_pathways_tab_msk_impact_2017_p-0000377_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_page_pathwaymapper_tab_with_unprofiled_genes_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/tcga_pancancer_atlas_page_element_chrome_1600x1000.png
Labels: test

#4354 Redirect from legacy static routes to new docs site
  src/pages/staticPages/aboutus/AboutUs.tsx
  src/pages/staticPages/aboutus/styles.scss
  src/pages/staticPages/faq/FAQ.tsx
  src/pages/staticPages/faq/styles.scss
  src/pages/staticPages/news/News.tsx
  src/pages/staticPages/news/styles.scss
  src/pages/staticPages/oql/OQL.tsx
  src/pages/staticPages/oql/styles.scss
  src/pages/staticPages/rmatlab/RMatLAB.tsx
  src/pages/staticPages/rmatlab/styles.scss
  src/pages/staticPages/tutorials/Tutorials.tsx
  src/pages/staticPages/tutorials/styles.scss
  src/pages/staticPages/webAPI/WebAPIPage.tsx
  src/pages/staticPages/webAPI/styles.scss
  src/routes.tsx
Labels: bug

#4304 react-mutation-mapper updates
  packages/react-mutation-mapper/src/component/column/Annotation.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKB.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbCardBody.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbHelper.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKbSummaryTable.tsx
  packages/react-mutation-mapper/src/component/oncokb/icon/AnnotationIcon.tsx
  packages/react-mutation-mapper/src/component/oncokb/icon/CompactAnnotationIcon.tsx
  packages/react-mutation-mapper/src/component/oncokb/icon/LevelIcon.tsx
  packages/react-mutation-mapper/src/component/oncokb/icon/OncogenicIcon.tsx
  packages/react-mutation-mapper/src/component/track/OncoKbTrackTooltip.tsx
  packages/react-mutation-mapper/src/store/DefaultMutationMapperStore.ts
Labels: oncokb, cl-external-api

#4351 Remember selected pathways source
  src/pages/resultsView/ResultsViewPage.tsx
  src/pages/resultsView/ResultsViewURLWrapper.ts
  src/pages/resultsView/pathwayMapper/PathWayMapperContainer.tsx
Labels: enhancement

#4357 Add workaround to limit the height of the twitter widget
  src/shared/components/rightbar/RightBar.tsx
Labels: bug

#4358 Restore webAPI page for token download
  src/pages/staticPages/webAPI/WebAPIPage.tsx
  src/pages/staticPages/webAPI/styles.scss
  src/routes.tsx
Labels: bug

#4362 Oncoprint tooltip should properly display "fusion partner message"
  src/shared/components/oncoprint/makeGeneticTrackTooltip.tsx
Labels: bug

#4314 When we detect an invalid profile id in study view filter, show a site error
  end-to-end-test/remote/screenshots/reference/fusion_filter_filter_study_from_url_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_pathways_tab_msk_impact_2017_p-0000377_element_chrome_1600x1000.png
  src/AppStore.ts
  src/pages/studyView/StudyViewPageStore.ts
  src/shared/components/errorScreen/ErrorScreen.tsx
Labels: bug
