Repository cBioPortal/cbioportal-frontend, pull requests merged in 2022-04, with the labels that each got.

#4223 Fix quick search e2e tests
  end-to-end-test/remote/specs/core/quickSearch.spec.js
Labels: test

#4220 Don't call mutation assessor for download when it's disabled
  src/shared/components/mutationTable/column/FunctionalImpactColumnFormatter.tsx
Labels: bug

#4224 Disable treatment range feature
  src/pages/studyView/StudyViewPageStore.ts
Labels: skip-changelog

#4180 Generic Assay improvement for Methylation data
  end-to-end-test/remote/screenshots/reference/group_comparison_page_microbiome_signature_tab_several_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_microbiome_signature_tab_two_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_microbiome_signature_tab_several_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_microbiome_signature_tab_two_groups_element_chrome_1600x1000.png
  src/appBootstrapper.tsx
  src/pages/groupComparison/GroupComparisonPage.tsx
  src/pages/resultsView/comparison/ComparisonTab.tsx
  src/pages/resultsView/download/DownloadTab.tsx
  src/pages/resultsView/download/DownloadUtils.ts
  src/pages/resultsView/enrichments/ExpressionEnrichmentsBoxPlot.tsx
  src/pages/resultsView/enrichments/GenericAssayEnrichmentsContainer.tsx
  src/pages/resultsView/enrichments/GenericAssayEnrichmentsTable.tsx
  src/pages/resultsView/enrichments/GenericAssayMiniScatterChart.tsx
  src/pages/resultsView/enrichments/MiniScatterChart.tsx
  src/pages/resultsView/oncoprint/AddTracks.tsx
  src/pages/resultsView/plots/PlotsTab.tsx
  src/pages/resultsView/plots/PlotsTabUtils.spec.ts
  src/pages/resultsView/plots/PlotsTabUtils.tsx
  src/pages/studyView/addChartButton/AddChartButton.tsx
  src/pages/studyView/addChartButton/genericAssaySelection/GenericAssaySelection.tsx
  src/shared/components/oncoprint/ResultsViewOncoprintUtils.tsx
  src/shared/components/oncoprint/TooltipUtils.ts
  src/shared/lib/GenericAssayUtils/GenericAssayCommonUtils.spec.ts
  src/shared/lib/GenericAssayUtils/GenericAssayCommonUtils.ts
  src/shared/lib/GenericAssayUtils/GenericAssayConfig.ts
  src/shared/lib/GenericAssayUtils/GenericAssaySelectionUtils.spec.ts
  src/shared/lib/GenericAssayUtils/GenericAssaySelectionUtils.ts
  src/shared/lib/GenericAssayUtils/MutationalSignaturesUtils.tsx
Labels: ready to review

#4227 Remove cbioportal and cosmic annotation threshholds in oncoprint controls
  end-to-end-test/remote/specs/core/oncoprint.spec.js
  end-to-end-test/remote/specs/core/oncoprinter.spec.js
  src/pages/staticPages/tools/oncoprinter/Oncoprinter.tsx
  src/shared/alterationFiltering/AnnotationFilteringSettings.ts
  src/shared/components/driverAnnotations/DriverAnnotationControls.tsx
  src/shared/components/oncoprint/ResultsViewOncoprint.tsx
  src/shared/components/oncoprint/controls/OncoprintControls.tsx
Labels: enhancement

#4210 Fix display value for selected filters in study view
  src/pages/studyView/StudyViewUtils.spec.tsx
  src/pages/studyView/StudyViewUtils.tsx
Labels: bug, gsoc

#4231 Change comparison page na category delimiter
  src/pages/groupComparison/ClinicalDataUtils.ts
Labels: enhancement

#4222 Put timeline image viewer in modal
  packages/cbioportal-clinical-timeline/src/TimelineTrack.tsx
  src/globalStyles/global.scss
Labels: cl-prototype

#4236 Update screenshots
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_microbiome_signature_tab_several_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_microbiome_signature_tab_two_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/tcga_pancancer_atlas_page_element_chrome_1600x1000.png
Labels: test

#4237 Add tooltip support for MSKTab pills
  src/shared/components/MSKTabs/MSKTabs.tsx
Labels: enhancement
