Repository cBioPortal/cbioportal-frontend, pull requests merged in 2022-01, with the labels that each got.

#4106 Conditionally fetch mutation assessor download data
  src/shared/lib/MutationTableDownloadDataFetcher.ts
Labels: enhancement

#4109 Add e2e test for freqency calculation in study view on study with cal…
  end-to-end-test/remote/screenshots/reference/shows_mutation_frequencies_correctly_for_called_but_unprofiled_mutations_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/studyview.spec.js
Labels: test

#4113 Optionally show NA when comparing categorical clinical data
  end-to-end-test/remote/screenshots/reference/group_comparison_page_clinical_tab_bar_chart_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_clinical_tab_percentage_stacked_bar_chart_exclude_overlapping_samples_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_clinical_tab_stacked_bar_chart_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_clinical_tab_stacked_bar_chart_horizontal_bars_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_clinical_tab_stacked_bar_chart_swaped_axes_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_comparison_tab_clinical_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_bar_chart_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_percentage_stacked_bar_chart_exclude_overlapping_samples_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_stacked_bar_chart_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_stacked_bar_chart_horizontal_bars_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_stacked_bar_chart_swaped_axes_chi_squared_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_comparison_tab_clinical_element_chrome_1600x1000.png
  src/pages/groupComparison/ClinicalData.tsx
  src/pages/groupComparison/GroupComparisonStore.ts
Labels: enhancement

#3992 Make numerical interval filter breadcrumbs in study view editable
  end-to-end-test/local/screenshots/reference/breadcrumbs_are_editable_for_mutation_count_chart_element_chrome_1600x1000.png
  end-to-end-test/local/specs/core/studyview.screenshot.spec.js
  end-to-end-test/remote/screenshots/reference/filter_study_from_url_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/multiple_tracks_with_same_gene_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_render_the_oncoprint_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/ov_tcga_pub_with_germline_mutations_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_render_the_oncoprint_element_chrome_1600x1000.png
  end-to-end-test/shared/wdio/wdio.conf.js
  package.json
  packages/cbioportal-frontend-commons/src/components/editableSpan/EditableSpan.tsx
  packages/cbioportal-frontend-commons/src/components/editableSpan/styles.module.scss
  packages/cbioportal-frontend-commons/src/components/editableSpan/styles.module.scss.d.ts
  packages/cbioportal-frontend-commons/src/index.tsx
  packages/cbioportal-frontend-commons/src/lib/onMobxPromise/onMobxPromise.spec.ts
  packages/cbioportal-frontend-commons/src/lib/onMobxPromise/onMobxPromise.ts
  src/pages/resultsView/ResultsViewPage.tsx
  src/pages/resultsView/download/DownloadTab.tsx
  src/pages/resultsView/plots/PlotsTab.tsx
  src/pages/staticPages/tools/oncoprinter/Oncoprinter.tsx
  src/pages/studyView/StudyViewPage.tsx
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/StudyViewUtils.spec.tsx
  src/pages/studyView/StudyViewUtils.tsx
  src/pages/studyView/UserSelections.tsx
  src/pages/studyView/studyPageHeader/StudyPageHeader.tsx
  src/pages/studyView/styles.module.scss
  src/pages/studyView/styles.module.scss.d.ts
  src/shared/components/PillTag/PillTag.tsx
  src/shared/components/cnSegments/CNSegmentsDownloader.tsx
  src/shared/components/oncoprint/ResultsViewOncoprint.spec.tsx
  src/shared/components/oncoprint/ResultsViewOncoprint.tsx
  src/shared/lib/comparison/ComparisonStore.ts
  yarn.lock
Labels: enhancement

#4115 Fix issue with aligning arrow in DefaultTooltip
  packages/cbioportal-frontend-commons/src/components/defaultTooltip/DefaultTooltip.tsx
Labels: style tweak

#4118 Remove unused line causing issues in DefaultTooltip
  packages/cbioportal-frontend-commons/src/components/defaultTooltip/DefaultTooltip.tsx
Labels: bug

#4121 Properly adjust oncokb content within annotation column
  packages/react-mutation-mapper/src/component/column/Annotation.tsx
  packages/react-mutation-mapper/src/component/oncokb/OncoKB.tsx
  src/pages/patientView/copyNumberAlterations/CopyNumberTableWrapper.tsx
  src/pages/patientView/structuralVariant/PatientViewStructuralVariantTable.tsx
  src/shared/components/mutationTable/MutationTable.tsx
  src/shared/lib/AnnotationColumnUtils.ts
Labels: bug

#4133 Clear localdb circleci cache and update screenshot
  .circleci/config.yml
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_render_the_oncoprint_element_chrome_1600x1000.png
Labels: test

#4134 Correct failing CNA e2e-localdb test
  end-to-end-test/local/specs/core/comparison-alterations-tab.spec.js
Labels: test

#4144 Fix getData function of exon column formatter
  src/shared/components/mutationTable/column/ExonColumnFormatter.tsx
Labels: bug

#4131 Format exon start and end location
  packages/cbioportal-utils/src/exon/ExonUtils.spec.ts
  packages/cbioportal-utils/src/exon/ExonUtils.ts
  packages/react-mutation-mapper/src/component/track/ExonTrack.tsx
Labels: enhancement

#4130 Update signal component to support both somatic and germline
  packages/cbioportal-utils/src/signal/SignalMutationUtils.ts
  packages/react-mutation-mapper/src/component/column/Signal.tsx
  packages/react-mutation-mapper/src/component/mutationTable/DefaultMutationTable.tsx
  packages/react-mutation-mapper/src/index.tsx
  packages/react-variant-view/src/component/cancerPatientPopulation/CancerPatientPrevalence.tsx
  packages/react-variant-view/src/component/frequencyTable/FrequencyTable.tsx
  packages/react-variant-view/src/util/Constants.ts
  src/config/serverConfigDefaults.ts
  src/shared/components/mutationTable/column/SignalColumnFormatter.tsx
Labels: cl-package

#4156 Revert "Improve performance for generic assay selection in add charts workflow"
  package.json
  src/pages/studyView/addChartButton/genericAssaySelection/GenericAssaySelection.tsx
  src/shared/components/select/OptimizedOption.tsx
  yarn.lock
Labels: revert

#4154 Fix bar chart selection bug
  package.json
  src/pages/studyView/StudyViewUtils.spec.tsx
  src/pages/studyView/StudyViewUtils.tsx
  src/pages/studyView/charts/barChart/BarChart.tsx
  yarn.lock
Labels: bug

#4149 Remove observability from MutationTable columns collection to fix tooltip issue
  end-to-end-test/remote/specs/core/mutationTable.spec.js
  src/shared/components/mutationTable/MutationTable.tsx
Labels: bug

#4157 Collapse GSVA hierarchy selector on initialization
  end-to-end-test/local/specs/gsva.spec.js
  src/config/IAppConfig.ts
  src/shared/components/query/GenesetsJsTree.tsx
Labels: enhancement
