Repository cBioPortal/cbioportal-frontend, pull requests merged in 2022-07, with the labels that each got.

#4309 Update pathway mapper version to the latest beta
  end-to-end-test/remote/screenshots/reference/results_page_pathwaymapper_tab_with_unprofiled_genes_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/screenshot.spec.js
  package.json
  yarn.lock
Labels: bug

#4316 Switch to the new uniprot rest API
  packages/react-mutation-mapper/src/component/lollipopMutationPlot/LollipopMutationPlot.tsx
  packages/react-mutation-mapper/src/component/mutationMapper/GeneSummary.tsx
  packages/react-mutation-mapper/src/util/DataFetcherUtils.ts
  src/config/serverConfigDefaults.ts
Labels: external api

#4328 Fix default bins when user adjust bins in filter textbox
  src/pages/studyView/StudyViewUtils.tsx
Labels: bug

#4327 Fix Genomic Alterations tab local crash issue
  src/pages/groupComparison/AlterationEnrichments.tsx
Labels: chore

#4312 Springfox Upgrade
  package.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPI-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPI.ts
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal.ts
  src/pages/resultsView/ResultsViewPageStore.spec.ts
  src/pages/resultsView/ResultsViewPageStoreUtils.spec.ts
  src/pages/resultsView/download/DownloadUtils.spec.ts
  src/pages/studyView/addChartButton/customCaseSelection/CustomCaseSelectionUtils.spec.ts
Labels: dependencies

#4333 Fix IGV sample names displayed next to tracks
  src/pages/patientView/genomicOverview/GenomicOverview.tsx
  src/shared/lib/IGVUtils.spec.ts
  src/shared/lib/IGVUtils.ts
Labels: bug

#4339 Stabilize study view generic assay e2e test
  end-to-end-test/remote/specs/core/studyview.spec.js
Labels: test

#4334 Make entire CNA table row clickable and add feature instruction
  src/pages/patientView/PatientViewPage.tsx
  src/pages/patientView/PatientViewPageTabs.tsx
  src/pages/patientView/copyNumberAlterations/CopyNumberTableWrapper.tsx
Labels: enhancement
