Repository cBioPortal/cbioportal-frontend, pull requests merged in 2022-10, with the labels that each got.

#4387 Fix errant console.log statement
  src/pages/patientView/PatientViewPageTabs.tsx
Labels: skip-changelog

#4390 Remove samples of overlapping patients in patient-level analysis
  src/pages/groupComparison/ClinicalData.tsx
  src/pages/groupComparison/ClinicalDataUtils.spec.ts
  src/pages/groupComparison/ClinicalDataUtils.ts
Labels: enhancement

#4400 Use genomenexus.isoform_override_source serverprop
  packages/react-mutation-mapper/README.md
  packages/react-mutation-mapper/src/store/DefaultMutationMapperDataFetcher.ts
  packages/react-mutation-mapper/src/store/DefaultMutationMapperStore.ts
  packages/react-mutation-mapper/src/util/DataFetcherUtils.spec.ts
  packages/react-mutation-mapper/src/util/DataFetcherUtils.ts
  src/config/IAppConfig.ts
  src/config/serverConfigDefaults.ts
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/mutation/Mutations.tsx
  src/pages/resultsView/mutation/ResultsViewMutationMapperStore.ts
  src/pages/staticPages/tools/mutationMapper/MutationMapperTool.tsx
  src/pages/staticPages/tools/mutationMapper/MutationMapperToolStore.ts
  src/shared/cache/GenomeNexusCache.ts
  src/shared/cache/GenomeNexusMutationAssessorCache.ts
  src/shared/components/mutationMapper/MutationMapperServerConfig.ts
  src/shared/components/mutationMapper/MutationMapperStore.ts
  src/shared/components/mutationMapper/MutationMapperUtils.ts
  src/shared/lib/StoreUtils.ts
Labels: devops

#4395 Fix hidden columns when switching transcripts
  packages/cbioportal-frontend-commons/src/lib/ColumnVisibilityResolver.ts
  src/shared/components/lazyMobXTable/LazyMobXTable.tsx
Labels: bug
