Repository cBioPortal/cbioportal-frontend, pull requests merged in 2023-03, with the labels that each got.

#4529 Handle empty body in registerRequestBodyCompression function
  src/config/config.ts
Labels: bug

#4407 Show reference genome in study list
  src/config/IAppConfig.ts
  src/shared/components/query/QueryStore.ts
  src/shared/components/query/studyList/StudyList.tsx
Labels: enhancement

#4526 #9925 Issue: Mass Spec label changed in dataset page
  src/pages/staticPages/datasetView/DatasetList.tsx
Labels: style tweak

#4532 Cleanup unused "user_email_address" variable
  end-to-end-test/local/specs/user-display-name.spec.js
  src/config/IAppConfig.ts
  src/config/config.ts
  src/pages/patientView/copyNumberAlterations/CopyNumberTableWrapper.tsx
  src/pages/patientView/trialMatch/TrialMatchTable.tsx
Labels: hyve, chore, test

#4538 MSKTabs should not interpret tooltip clicks as clicks on tab buttons
  src/pages/resultsView/pathwayMapper/PathWayMapperContainer.tsx
  src/shared/components/MSKTabs/MSKTabs.tsx
Labels: gsoc

#4535 Fix the localdb tests for ARM architecture macOS
  end-to-end-test/local/docker_compose/keycloak.yml
  end-to-end-test/local/docker_compose/start.sh
  scripts/e2e.sh
Labels: devops

#4524 Edit filter panel layout and group "Other" mutations into drivers and vus in comparison lollipop
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/hcc_inserm_fr_2015_with_genes_including_tert_-_it_should_show_orange_promoter_mutations_in_tert_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_mutation_tab_element_chrome_1600x1000.png
  packages/cbioportal-frontend-commons/src/components/checkedSelect/BadgeCell.tsx
  packages/cbioportal-frontend-commons/src/components/checkedSelect/badgeListSelector.module.scss
  packages/cbioportal-frontend-commons/src/lib/AlterationColors.ts
  packages/cbioportal-frontend-commons/src/lib/getCanonicalMutationType.ts
  packages/oncoprintjs/rules/geneticrules.ts
  packages/react-mutation-mapper/src/component/filter/BadgeLabel.tsx
  packages/react-mutation-mapper/src/component/filter/BadgeSelector.tsx
  packages/react-mutation-mapper/src/component/filter/ProteinImpactTypeBadgeSelector.tsx
  packages/react-mutation-mapper/src/model/ProteinImpact.ts
  packages/react-mutation-mapper/src/util/MutationTypeUtils.ts
  src/pages/groupComparison/GroupComparisonMutationMapper.tsx
  src/pages/groupComparison/GroupComparisonMutationsTabPlot.tsx
  src/pages/groupComparison/styles.module.scss
  src/pages/groupComparison/styles.module.scss.d.ts
  src/pages/resultsView/mutation/Mutations.tsx
  src/pages/resultsView/plots/PlotsTabUtils.tsx
  src/shared/components/mutationMapper/DriverAnnotationProteinImpactTypeBadgeSelector.tsx
  src/shared/components/mutationMapper/LegendColorCodes.tsx
  src/shared/components/mutationMapper/MutationMapper.tsx
  src/shared/components/mutationMapper/badgeSelector.module.scss
  src/shared/components/mutationMapper/badgeSelector.module.scss.d.ts
  src/shared/components/oncoprint/geneticrules.ts
  src/shared/lib/MutationUtils.tsx
Labels: feature

#4558 :bug: Update Freq Col Alignment in Timeline Event Availability Chart
  end-to-end-test/local/screenshots/reference/breadcrumbs_are_editable_for_mutation_count_chart_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/can_filter_a_study_by_patient_treatments_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/can_filter_a_study_by_sample_treatments_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/generic_assay_chart_should_be_added_in_the_summary_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/loads_multiple_studies_with_treatments_tables_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/tcga_pancancer_atlas_page_element_chrome_1600x1000.png
  src/pages/studyView/table/ClinicalEventTypeCountTable.tsx
Labels: bug

#4559 Fix driver/vus filter in badge selector for results and comparison
  end-to-end-test/remote/specs/core/groupComparisonLollipop.spec.js
  src/shared/components/mutationMapper/DriverAnnotationProteinImpactTypeBadgeSelector.tsx
Labels: bug

#4533 Allow numeric data type for custom data charts
  end-to-end-test/local/screenshots/reference/add_custom_data_tab_should_have_numerical_and_categorical_selector_element_chrome_1600x1000.png
  end-to-end-test/local/specs/core/studyview.screenshot.spec.js
  env/custom.sh
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal.ts
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/StudyViewUtils.spec.tsx
  src/pages/studyView/StudyViewUtils.tsx
  src/pages/studyView/addChartButton/customCaseSelection/CustomCaseSelection.tsx
  src/pages/studyView/charts/barChart/BarChart.tsx
  src/pages/studyView/studyPageHeader/StudyPageHeader.tsx
  src/pages/studyView/tabs/SummaryTab.tsx
Labels: feature
