Repository cBioPortal/cbioportal-frontend, pull requests merged in 2023-11, with the labels that each got.

#4766 Update screenshots after oncokb update and pie chart label change
  end-to-end-test/remote/screenshots/reference/group_comparison_page_mutations_tab_two_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/tcga_pancancer_atlas_page_element_chrome_1600x1000.png
Labels: test

#4758 Fix incorrect oncokb data and cancer type label used in mutations table
  src/pages/groupComparison/GroupComparisonMutationMapper.tsx
  src/pages/groupComparison/GroupComparisonMutationMapperWrapper.tsx
  src/pages/groupComparison/GroupComparisonMutationTable.tsx
  src/shared/components/mutationMapper/MutationMapperStore.ts
  src/shared/components/mutationTable/MutationTable.tsx
  src/shared/lib/StoreUtils.ts
  src/shared/lib/comparison/AnalysisStore.ts
Labels: enhancement

#4767 Study view: fix comparison session generation from study view bin cha…
  src/pages/studyView/StudyViewUtils.tsx
Labels: bug

#4768 Clinical attribute types with priority of zero should not appear by default on study view
  src/pages/studyView/StudyViewPageStore.ts
Labels: bug

#4778 Fix for endless loop preventing gene update using modify query interface (after direct load of results of view)
  package.json
  yarn.lock
Labels: bug

#4770 Change gene add behavior to improve user experience
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/StudyViewUtils.tsx
  src/pages/studyView/table/GeneCell.tsx
Labels: enhancement

#4721 [RFC77] Filter buttons on the landing page study search menu
  src/shared/components/query/CancerStudySelector.tsx
  src/shared/components/query/DataTypeFilter.spec.ts
  src/shared/components/query/DataTypeFilter.tsx
  src/shared/components/query/QueryStore.ts
  src/shared/components/query/StudyListLogic.ts
  src/shared/components/query/filteredSearch/Phrase.tsx
  src/shared/components/query/filteredSearch/StudySearchControls.tsx
  src/shared/components/query/filteredSearch/field/CheckboxFilterField.tsx
  src/shared/components/query/studyList/StudyList.tsx
Labels: feature

#4779 Restore asterisks in oncoprint track percentage labels
  end-to-end-test/local/screenshots/reference/expands_and_shows_correlation_genes_for_go_atp_dependent_chromatin_remodeling_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/initializes_as_configured_by_default_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/initializes_correctly_when_clinicallist_config_present_in_url_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_gsva_heatmap_track_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_oql_structural_variant_variations_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_treatment_profile_heatmap_track_for_treatment_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/still_supports_legacy_clinicallist_format_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/msk_impact_2017_with_alk_and_sos1_-_sos1_should_be_not_sequenced_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/profiled_in_tracks_in_multiple_study_with_sos1_element_chrome_1600x1000.png
  packages/oncoprintjs/src/js/oncoprinttrackinfoview.ts
  src/shared/components/oncoprint/OncoprintUtils.ts
Labels: bug

#4781 Fix spec import that is currently breaking local db test report
  end-to-end-test/local/specs/struct-var-table.spec.js
Labels: test

#4699 Add user color configuration for oncoprint
  end-to-end-test/remote/screenshots/reference/oncoprint_reflects_default_colors_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_reflects_user_selected_colors_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_uses_default_background_for_glyphs_when_option_not_toggled_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_uses_white_background_for_glyphs_when_option_toggled_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/resultsOncoprintColorConfig.spec.js
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/ResultsViewURLWrapper.ts
  src/shared/components/oncoprint/ClinicalTrackColorPicker.tsx
  src/shared/components/oncoprint/DeltaUtils.ts
  src/shared/components/oncoprint/Oncoprint.tsx
  src/shared/components/oncoprint/OncoprintUtils.ts
  src/shared/components/oncoprint/ResultsViewOncoprint.tsx
  src/shared/components/oncoprint/controls/OncoprintControls.tsx
  src/shared/lib/Colors.ts
Labels: enhancement

#4785 Add datadog logging to frontend
  package.json
  src/appBootstrapper.tsx
  yarn.lock
Labels: skip-changelog
