Repository cBioPortal/cbioportal-frontend, pull requests merged in 2023-02, with the labels that each got.

#4503 Update DataSetList to include treatmentCount col
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPI.ts
  src/pages/staticPages/datasetView/DatasetList.tsx
Labels: enhancement

#4512 Update Treatment Filters to wrap groupLogic wrapper with parent to ho…
  end-to-end-test/remote/screenshots/reference/can_filter_a_study_by_patient_treatments_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/can_filter_a_study_by_sample_treatments_element_chrome_1600x1000.png
  src/pages/studyView/UserSelections.tsx
Labels: bug

#4514 Add link to study view to view a group of comparison view
  src/pages/groupComparison/groupSelector/GroupSelector.tsx
  src/pages/groupComparison/groupSelector/GroupSelectorButton.tsx
Labels: enhancement

#4513 Fix localdb bootup (on local linux machines)
  end-to-end-test/local/docker_compose/keycloak.yml
Labels: test

#4498 Rename 'user email' variables to 'user display name' for consistency
  end-to-end-test/local/specs/user-display-name.spec.js
  end-to-end-test/shared/specUtils.js
  packages/oncokb-frontend-commons/src/components/OncoKB.tsx
  packages/oncokb-frontend-commons/src/components/OncoKbFeedback.tsx
  packages/react-mutation-mapper/src/component/column/Annotation.tsx
  src/config/IAppConfig.ts
  src/config/config.ts
  src/pages/patientView/copyNumberAlterations/CopyNumberTableWrapper.tsx
  src/pages/patientView/mutation/MutationTableWrapper.tsx
  src/pages/patientView/mutation/PatientViewMutationsTab.tsx
  src/pages/patientView/structuralVariant/StructuralVariantTableWrapper.tsx
  src/pages/patientView/trialMatch/TrialMatchFeedback.tsx
  src/pages/patientView/trialMatch/TrialMatchTable.tsx
  src/pages/resultsView/mutation/Mutations.tsx
  src/pages/resultsView/mutation/ResultsViewMutationMapper.tsx
  src/pages/studyView/virtualStudy/VirtualStudy.tsx
  src/shared/components/mutationTable/MutationTable.tsx
  src/shared/lib/openSocialAuthWindow.ts
Labels: enhancement, hyve

#4525 fix formatNumberValueInSignificantDigits function for bigger numbers
  packages/cbioportal-utils/src/format/FormatUtils.spec.ts
  packages/cbioportal-utils/src/format/FormatUtils.ts
Labels: bug
