Repository cBioPortal/cbioportal-frontend, pull requests merged in 2023-10, with the labels that each got.

#4741 Update home page citation
  src/config/serverConfigDefaults.ts
Labels: style tweak, cl-style-tweak

#4747 Configure left logo in the cBioPortal header via 'skin.left_logo' property
  src/appShell/App/PortalHeader.tsx
  src/config/IAppConfig.ts
  src/shared/api/urls.ts
Labels: devops

#4751 Patient page: fix Clinical Events table search (handle numerical data)
  src/pages/patientView/timeline/ClinicalEventsTables.tsx
Labels: bug

#4752 Fix search issue in SV table when site1 gene is missing
  src/pages/patientView/structuralVariant/StructuralVariantTableWrapper.tsx
Labels: bug

#4750 match cna chart colors with oncoprint and adjust label colors accordi…
  end-to-end-test/remote/screenshots/reference/check_for_survival_plots_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/fusion_filter_filter_study_from_url_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/loads_a_virtual_study_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/loads_multiple_studies_with_treatments_tables_element_chrome_1600x1000.png
  packages/cbioportal-frontend-commons/src/lib/AlterationColors.ts
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/StudyViewUtils.tsx
  src/pages/studyView/charts/pieChart/PieChart.tsx
Labels: feature

#4754 Genie portal timeline: tweak track ordering for assessment tracks
  src/pages/patientView/timeline/timeline_helpers.tsx
Labels: style tweak

#4757 Add download data and PDF option
  src/pages/resultsView/survival/SurvivalChart.tsx
Labels: bug

#4761 Fix SVG download (prevent embedding of css)
  package.json
  packages/cbioportal-frontend-commons/package.json
  packages/cbioportal-frontend-commons/src/components/downloadControls/DownloadControls.tsx
  yarn.lock
Labels: bug

#4762 Refactor to allow pie and table charts to download both full and summ…
  packages/cbioportal-frontend-commons/src/components/downloadControls/DownloadControls.tsx
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/tabs/SummaryTab.tsx
Labels: bug

#4765 Update API clients
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPI-docs.json
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPI.ts
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPIInternal-docs.json
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPIInternal.ts
Labels: chore
