Repository cBioPortal/cbioportal-frontend, pull requests merged in 2023-04, with the labels that each got.

#4564 Fix localdb keycloak docker image issue
  end-to-end-test/local/docker_compose/keycloak.yml
  end-to-end-test/local/docker_compose/start.sh
  scripts/e2e.sh
Labels: test

#4568 Apply oncokb configuration to patient page (where it was missing)
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
Labels: bug

#4517 Update gene related search in Oncoprint and Plots tab
  end-to-end-test/remote/specs/core/plots.spec.js
  package.json
  src/pages/resultsView/plots/PlotsTab.tsx
  src/shared/lib/GenericAssayUtils/GenericAssayCommonUtils.spec.ts
  src/shared/lib/GenericAssayUtils/GenericAssayCommonUtils.ts
Labels: enhancement

#4572 Disable oncokb fetch from MutationMapper when show_oncokb config is off
  src/pages/resultsView/mutation/ResultsViewMutationMapper.tsx
  src/pages/staticPages/tools/mutationMapper/StandaloneMutationMapper.tsx
Labels: bug

#4542 Oncoprint Add Track UI Tweak
  end-to-end-test/local/specs/core/studyview.screenshot.spec.js
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_plots_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/generic_assay_chart_should_be_added_in_the_summary_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/studyview.spec.js
  end-to-end-test/shared/specUtils.js
  src/pages/studyView/addChartButton/genericAssaySelection/GenericAssaySelection.tsx
Labels: gsoc

#4592 :bug: Add Missing Operations Button Txt to Clinical Event Type Table
  src/pages/studyView/charts/ChartContainer.tsx
  src/pages/studyView/table/ClinicalEventTypeCountTable.tsx
Labels: bug

#4587 :wrench: Add Configurable Param for max number of samples in study vi…
  src/config/IAppConfig.ts
  src/config/serverConfigDefaults.ts
  src/shared/components/query/QueryContainer.tsx
Labels: enhancement

#4589 Add revue icon for revue variants
  end-to-end-test/local/screenshots/reference/displays_ascn_columns_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/does_not_display_ascn_columns_for_studies_with_no_ascn_data_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/does_not_show_ascn_columns_study_with_no_ascn_data_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_ascn_columns_for_study_where_some_samples_have_ascn_data_and_some_do_not_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/shows_ascn_columns_for_study_with_ascn_data_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_page_valid_after_cohort_navigation_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_lgg_ucsf_2014_p04_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_view_with_0_mutations_msk_impact_2017_p-0000053-t01-im3_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_heatmap_with_two_mutations_selected_from_before_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_hover_a_mutation_with_heatmap_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_initial_view_with_line_chart_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_one_mutation_selected_with_heatmap_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_one_mutation_selected_with_line_chart_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_show_timeline_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_mutation_tab_element_chrome_1600x1000.png
  packages/cbioportal-utils/src/mutation/ProteinChangeUtils.ts
  packages/react-mutation-mapper/src/component/column/Annotation.tsx
  packages/react-mutation-mapper/src/component/mutationMapper/MutationMapper.tsx
  packages/react-mutation-mapper/src/component/mutationTable/DefaultMutationTable.tsx
  packages/react-mutation-mapper/src/component/revue/Revue.tsx
  packages/react-mutation-mapper/src/images/vue_logo.png
  packages/react-mutation-mapper/src/index.tsx
  packages/react-mutation-mapper/src/store/DefaultMutationMapperStore.ts
  src/config/IAppConfig.ts
  src/config/serverConfigDefaults.ts
  src/pages/patientView/copyNumberAlterations/CopyNumberTableWrapper.tsx
  src/pages/patientView/structuralVariant/StructuralVariantTableWrapper.tsx
  src/pages/resultsView/mutation/ResultsViewMutationMapper.tsx
  src/rootImages/vue_logo.png
  src/shared/components/mutationMapper/MutationMapper.tsx
  src/shared/components/mutationTable/MutationTable.tsx
  src/shared/components/mutationTable/column/AnnotationColumnFormatter.tsx
  src/shared/components/mutationTable/column/MutationTypeColumnFormatter.tsx
  src/shared/components/mutationTable/column/ProteinChangeColumnFormatter.tsx
  src/shared/components/mutationTable/column/annotation/AnnotationHeader.tsx
  src/shared/components/mutationTable/column/mutationType.module.scss
  src/shared/components/mutationTable/column/mutationType.module.scss.d.ts
  src/shared/components/mutationTable/column/proteinChange.module.scss
  src/shared/components/mutationTable/column/proteinChange.module.scss.d.ts
Labels: feature

#4595 fixes #10122
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/tabs/SummaryTab.tsx
Labels: gsoc

#4604 Check undefined annotation_summary when fetching revue
  packages/react-mutation-mapper/src/component/column/Annotation.tsx
Labels: bug
