Repository cBioPortal/cbioportal-frontend, pull requests merged in 2023-09, with the labels that each got.

#4706 Discrete molecular data counts
  packages/cbioportal-frontend-commons/src/lib/AlterationColors.ts
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal.ts
  src/pages/resultsView/enrichments/EnrichmentsUtil.tsx
  src/pages/studyView/StudyViewPage.tsx
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/StudyViewUtils.spec.tsx
  src/pages/studyView/StudyViewUtils.tsx
  src/pages/studyView/UserSelections.tsx
  src/pages/studyView/addChartButton/geneLevelSelection/GeneLevelSelection.tsx
  src/pages/studyView/charts/ChartContainer.tsx
  src/pages/studyView/charts/pieChart/PieChart.tsx
  src/pages/studyView/studyPageHeader/StudyPageHeader.tsx
  src/pages/studyView/table/ClinicalTable.tsx
  src/pages/studyView/tabs/SummaryTab.tsx
Labels: feature

#4700 Add e2e tests for Interactive Web Tour
  end-to-end-test/local/specs/web-tour.spec.js
Labels: test

#4715 Update API clients and fix screenshots after Oncobk update
  end-to-end-test/remote/screenshots/reference/coadread_tcga_pub_with_clinical_and_heatmap_tracks_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/coadread_tcga_pub_with_column_gaps_inserted_based_on_clinical_track_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_plots_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_render_the_oncoprint_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_loads_and_expands_a_merged_track_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_should_cluster_heatmap_group_correctly_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_should_delete_clustered_heatmap_group_correctly_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_should_delete_non-clustered_heatmap_group_correctly_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_should_return_to_non-clustered_state_correctly_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_should_sort_patients_correctly_in_coadread_tcga_pub_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/oncoprint_should_sort_samples_correctly_in_coadread_tcga_pub_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_plots_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_render_the_oncoprint_element_chrome_1600x1000.png
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal.ts
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPI-docs.json
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPI.ts
Labels: test

#4677 Render custom tooltip in oncoprint using custom js function
  src/appBootstrapper.tsx
  src/config/IAppConfig.ts
  src/shared/components/oncoprint/DeltaUtils.ts
  src/shared/getCustomJsFunctions.ts
Labels: skip-changelog

#4716 [Snyk] Security upgrade less from 2.7.3 to 3.0.2
  package.json
Labels: chore

#4722 Update yarn lock file
  yarn.lock
Labels: dependencies

#4736 Revert breaking updates to dependencies
  package.json
  yarn.lock
Labels: skip-changelog

#4686 (GSoC) Generic Assay Categorical/Binary data implementation Frontend
  end-to-end-test/local/screenshots/reference/results_view_comparison_tab_alteration_enrichments_several_groups_element_chrome_1600x1000.png
  packages/cbioportal-ts-api-client/src/index.tsx
  src/pages/groupComparison/GenericAssayEnrichmentCollections.tsx
  src/pages/groupComparison/GroupComparisonPage.tsx
  src/pages/groupComparison/GroupComparisonTabs.ts
  src/pages/resultsView/ResultsViewPageStoreUtils.ts
  src/pages/resultsView/comparison/ComparisonTab.tsx
  src/pages/resultsView/enrichments/EnrichmentsUtil.tsx
  src/pages/resultsView/enrichments/GenericAssayBarPlot.tsx
  src/pages/resultsView/enrichments/GenericAssayBinaryEnrichmentsContainer.tsx
  src/pages/resultsView/enrichments/GenericAssayBinaryEnrichmentsTable.tsx
  src/pages/resultsView/enrichments/GenericAssayBinaryEnrichmentsTableDataStore.tsx
  src/pages/resultsView/enrichments/GenericAssayCategoricalEnrichmentsContainer.tsx
  src/pages/resultsView/enrichments/GenericAssayCategoricalEnrichmentsTable.tsx
  src/pages/resultsView/enrichments/GenericAssayCategoricalEnrichmentsTableDataStore.tsx
  src/pages/resultsView/enrichments/MiniFrequencyScatterChart.tsx
  src/shared/featureFlags.ts
  src/shared/lib/GenericAssayUtils/GenericAssayCommonUtils.ts
  src/shared/lib/comparison/ComparisonStore.ts
  src/shared/model/EnrichmentRow.ts
Labels: feature, cl-prototype, gsoc

#4739 Remove revue from Annotation column sorting
  packages/react-mutation-mapper/src/component/revue/Revue.tsx
Labels: style tweak

#4711 Fix SV pane search box: Only filter genes when present
  src/pages/studyView/table/StructuralVariantMultiSelectionTable.tsx
Labels: bug

#4709 [RFC 76] Redesign oncoprint annotation menu
  end-to-end-test/local/runtime-config/portal.properties
  end-to-end-test/local/specs/custom-driver-annotations-in-result-view.spec.js
  end-to-end-test/remote/specs/core/oncoprinter.screenshot.spec.js
  src/config/serverConfigDefaults.ts
  src/shared/alterationFiltering/AnnotationFilteringSettings.ts
  src/shared/alterationFiltering/SettingsMenu.tsx
  src/shared/components/driverAnnotations/DriverAnnotationControls.tsx
  src/shared/components/driverAnnotations/SettingsMenuButton.tsx
  src/shared/components/driverAnnotations/styles.module.scss
  src/shared/components/driverAnnotations/styles.module.scss.d.ts
Labels: enhancement

#4744 [RFC68] Enable Struct Var table feature on Study View with 'skin.study_view.show_sv_table' property
  end-to-end-test/local/specs/struct-var-table.spec.js
  src/config/IAppConfig.ts
  src/config/serverConfigDefaults.ts
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/table/GeneCell.tsx
  src/pages/studyView/table/StructVarCell.tsx
  src/shared/featureFlags.ts
Labels: devops

#4745 Enable Results View Structural Variants Tab
  src/pages/resultsView/ResultsViewPage.tsx
Labels: feature

#4748 On patient page, default to SBS mutational signatures
  end-to-end-test/local/screenshots/reference/show_mutational_signatures_table_for_patient_who_has_significant_sbs_signatures_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/show_stacked_bar_chart_for_patient_who_has_significant_sbs_signatures_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/show_tooltip_for_patient_who_has_significant_sbs_signatures_element_chrome_1600x1000.png
  src/shared/lib/GenericAssayUtils/MutationalSignaturesUtils.tsx
Labels: enhancement, test
