Repository cBioPortal/cbioportal-frontend, pull requests merged in 2023-05, with the labels that each got.

#4605 Check undefined revue for mutation type and protein change column
  src/shared/components/mutationTable/column/MutationTypeColumnFormatter.tsx
  src/shared/components/mutationTable/column/ProteinChangeColumnFormatter.tsx
Labels: bug

#4606 Import image as source for revue logo
  packages/react-mutation-mapper/src/component/revue/Revue.tsx
Labels: bug

#4602 :wrench: Add configurability for StudyDownloadUrl
  src/config/IAppConfig.ts
  src/config/serverConfigDefaults.ts
  src/pages/staticPages/datasetView/DatasetPage.tsx
  src/pages/studyView/StudyViewPageStore.ts
  src/shared/api/urls.ts
  src/shared/components/StudyDataDownloadLink/StudyDataDownloadLink.tsx
Labels: enhancement

#4588 Structural Variant table
  src/pages/patientView/PatientViewPage.tsx
  src/pages/resultsView/ResultsViewPage.tsx
  src/pages/resultsView/ResultsViewPageHelpers.tsx
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/mutation/Mutations.tsx
  src/pages/resultsView/structuralVariant/ResultsViewStructuralVariantMapper.tsx
  src/pages/resultsView/structuralVariant/ResultsViewStructuralVariantMapperDataStore.ts
  src/pages/resultsView/structuralVariant/ResultsViewStructuralVariantMapperStore.ts
  src/pages/resultsView/structuralVariant/ResultsViewStructuralVariantTable.tsx
  src/pages/resultsView/structuralVariant/StructuralVariants.tsx
  src/pages/staticPages/tools/mutationMapper/MutationMapperTool.tsx
  src/shared/components/mutationMapper/MutationMapperUserSelectionStore.ts
  src/shared/components/structuralVariantTable/StructuralVariantTable.tsx
  src/shared/lib/AnnotationColumnUtils.ts
  src/shared/lib/StoreUtils.ts
  src/shared/model/Fusion.ts
Labels: skip-changelog

#4601 Update svg2pdf to fix broken Overlap charts download
  package.json
  packages/cbioportal-frontend-commons/package.json
  yarn.lock
Labels: dependencies

#4610 Add TCGA Pancan pathways to query selector
  src/shared/components/query/gene_lists.ts
Labels: enhancement

#4616 :sparkles: Add PatientIdentifiers URL Parameter
  src/pages/studyView/StudyViewPage.tsx
  src/pages/studyView/StudyViewPageStore.ts
  src/shared/model/PatientIdentifierFilter.ts
Labels: enhancement

#4596 Add profile filtering when adding Generic Entity IDs in Oncoprint
  src/pages/resultsView/oncoprint/TracksMenu.tsx
Labels: bug

#4622 Revert "Add profile filtering when adding Generic Entity IDs in Oncoprint"
  src/pages/resultsView/oncoprint/TracksMenu.tsx
Labels: skip-changelog

#4617 Add new "queue" gene icon to study view gene tables
  end-to-end-test/local/screenshots/reference/breadcrumbs_are_editable_for_mutation_count_chart_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/non_cancer_gene_should_show_up_when_the_cancer_gene_filter_is_disabled_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/the_cancer_gene_filter_should_remove_non_cancer_gene_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/oncoprint.screenshot.spec.js
  end-to-end-test/shared/specUtils.js
  package.json
  src/appShell/App/Container.tsx
  src/pages/studyView/StudyViewPage.tsx
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/TableUtils.tsx
  src/pages/studyView/studyPageHeader/rightPanel/RightPanel.tsx
  src/pages/studyView/table/GeneCell.tsx
  src/pages/studyView/table/tables.module.scss
  src/pages/studyView/table/tables.module.scss.d.ts
  src/shared/components/query/QueryContainer.tsx
  yarn.lock
Labels: enhancement

#4624 Update e2e
  end-to-end-test/remote/screenshots/reference/a_error_message_should_be_shown_when_the_filterattributeid_is_not_available_for_the_study_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/can_filter_a_study_by_patient_treatments_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/can_filter_a_study_by_sample_treatments_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/check_for_survival_plots_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/filter_study_from_url_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/fusion_filter_filter_study_from_url_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/generic_assay_chart_should_be_added_in_the_summary_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/loads_a_virtual_study_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/loads_multiple_studies_with_treatments_tables_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/study_view_laml_tcga_clinical_data_clicked_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/tcga_pancancer_atlas_page_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/when_quickly_adding_charts,_each_chart_should_get_proper_data._element_chrome_1600x1000.png
Labels: skip-changelog
