Repository cBioPortal/cbioportal-frontend, pull requests merged in 2023-07, with the labels that each got.

#4665 Update seedDB url for localdb test
  end-to-end-test/local/runtime-config/setup_environment.sh
Labels: test

#4673 Add custom url handling for resource tab iframes (enables state persistence for Minerva viewer)
  src/shared/components/resources/ResourceTab.tsx
  src/shared/components/resources/customResourceHelpers.ts
Labels: cl-prototype

#4661 Add VEP link in reVUE tooltip
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPI-docs.json
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPI.ts
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPIInternal-docs.json
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPIInternal.ts
  packages/react-mutation-mapper/src/component/revue/Revue.tsx
  src/shared/components/mutationTable/column/AnnotationColumnFormatter.tsx
Labels: enhancement
