Repository cBioPortal/cbioportal-frontend, pull requests merged in 2023-08, with the labels that each got.

#4670 Update screenshots for two-sided fisher test
  end-to-end-test/local/screenshots/reference/group_comparison_alteration_enrichments_two_groups_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/results_view_comparison_tab_alteration_enrichments_two_groups_element_chrome_1600x1000.png
Labels: skip-changelog

#4683 Update q value banner language and placement
  src/shared/components/userMessager/UserMessage.tsx
Labels: enhancement

#4691 Fix mutated and total profiled patient counts in comparison mutations table and lollipop tooltip
  end-to-end-test/remote/screenshots/reference/group_comparison_page_mutations_tab_three_groups_first_unselected_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/groupComparison.screenshot.spec.js
  src/pages/groupComparison/GroupComparisonStore.ts
  src/pages/groupComparison/LollipopTooltipCountInfo.tsx
Labels: bug

#4692 bug fix: case no meta data from mutational signatures endpoint
  end-to-end-test/local/screenshots/reference/show_mutational_bar_chart_dbs_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/show_mutational_bar_chart_id_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/show_mutational_bar_chart_sbs_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/show_mutational_signatures_table_for_patient_who_has_significant_id_signatures_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/show_mutational_signatures_table_for_patient_who_has_significant_sbs_signatures_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/show_the_bar_chart_with_percentage_on_y_axis_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/show_tooltip_for_patient_who_has_significant_dbs_signatures_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/show_tooltip_for_patient_who_has_significant_id_signatures_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/show_tooltip_for_patient_who_has_significant_sbs_signatures_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/switch_between_samples_to_update_mutational_bar_chart_element_chrome_1600x1000.png
  src/pages/patientView/PatientViewPageUtils.tsx
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
  src/pages/patientView/mutationalSignatures/MutationalSignatureBarChart.tsx
  src/pages/patientView/mutationalSignatures/MutationalSignatureBarChartUtils.ts
Labels: bug

#4688 Adding jitpack build script and label check test for pull request
  .github/workflows/jitpack-build.yml
  .github/workflows/label-check.yml
Labels: devops

#4678 Fix pathway table page reset issue
  src/shared/lib/pathwayMapper/PathwayMapperTable.tsx
Labels: bug

#4694 Fix default value bug when backend parameter is missing for oncoprint clustered option
  src/config/IAppConfig.ts
  src/config/serverConfigDefaults.ts
Labels: test

#4696 Update jitpack-build for pre-release
  .github/workflows/jitpack-build.yml
Labels: devops

#4685 Replace twitter with news feed
  package.json
  src/globalStyles/global.scss
  src/shared/components/rightbar/RightBar.tsx
  src/shared/lib/parseNews.ts
  yarn.lock
Labels: bug

#4687 Add Interactive Web Tour for Virtual Studies and Group Comparison
  end-to-end-test/local/runtime-config/portal.properties
  src/config/IAppConfig.ts
  src/config/serverConfigDefaults.ts
  src/pages/groupComparison/GroupComparisonPage.tsx
  src/pages/groupComparison/groupSelector/GroupSelector.tsx
  src/pages/home/HomePage.tsx
  src/pages/studyView/StudyViewPage.tsx
  src/pages/studyView/charts/ChartContainer.tsx
  src/pages/studyView/studyPageHeader/ActionButtons.tsx
  src/pages/studyView/studyPageHeader/studySummary/StudySummary.tsx
  src/pages/studyView/tabs/SummaryTab.tsx
  src/pages/studyView/virtualStudy/VirtualStudy.tsx
  src/shared/components/PageLayout/PageLayout.tsx
  src/shared/components/query/CancerStudySelector.tsx
  src/shared/components/query/CancerStudyTreeData.ts
  src/shared/components/query/QueryContainer.tsx
  src/shared/components/query/studyList/StudyList.tsx
  src/shared/components/rightbar/RightBar.tsx
  src/shared/components/survival/LeftTruncationCheckbox.tsx
  src/tours/Steps/GroupComparison.tsx
  src/tours/Steps/VirtualStudy.tsx
  src/tours/Steps/index.tsx
  src/tours/Tour/index.tsx
  src/tours/Tour/styles.css
  src/tours/Tour/types.tsx
  src/tours/index.tsx
Labels: feature, gsoc

#4710 Update mysql 8 connection string for localdb tests
  end-to-end-test/local/runtime-config/portal.properties
Labels: test

#4695 Enhancements to patient page
  end-to-end-test/remote/screenshots/reference/patient_page_valid_after_cohort_navigation_element_chrome_1600x1000.png
  src/pages/patientView/PatientViewPage.tsx
  src/shared/components/lazyMobXTable/LazyMobXTable.spec.tsx
  src/shared/components/paginationControls/PaginationControls.tsx
Labels: enhancement

#4679 Extend sample type colors in patient view
  src/pages/patientView/SampleManager.tsx
  src/pages/patientView/clinicalInformation/lib/clinicalAttributesUtil.js
  src/pages/patientView/patientHeader/style/clinicalAttributes.scss
Labels: enhancement

#4712 Fix hidden non-genomic data when excluding VUS in oncoprint
  src/pages/resultsView/ResultsViewPageStore.ts
  src/shared/components/oncoprint/ResultsViewOncoprint.tsx
Labels: enhancement

#4701 Improve non-profiled gene panel links in oncoprint tooltip
  src/shared/components/oncoprint/TooltipUtils.spec.ts
  src/shared/components/oncoprint/TooltipUtils.ts
Labels: enhancement

#4704 Add property to define custom sample type colors in patient view
  src/config/IAppConfig.ts
  src/config/config.ts
  src/config/serverConfigDefaults.ts
  src/pages/patientView/SampleManager.tsx
  src/pages/patientView/clinicalInformation/lib/clinicalAttributesUtil.js
Labels: enhancement
