Repository cBioPortal/cbioportal-frontend, pull requests merged in 2024-08, with the labels that each got.

#4962 Update Genome Nexus API client to include Alpha Missense
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPI-docs.json
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPI.ts
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPIInternal-docs.json
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPIInternal.ts
Labels: cl-package

#4963 Add organoid icon and color on Patient View
  src/pages/patientView/SVGIcons.tsx
  src/pages/patientView/SampleManager.tsx
  src/pages/patientView/clinicalInformation/lib/clinicalAttributesStyleConsts.ts
  src/pages/patientView/clinicalInformation/lib/clinicalAttributesUtil.js
  src/pages/patientView/patientHeader/style/clinicalAttributes.scss
  src/pages/patientView/sampleHeader/SampleSummaryList.tsx
  src/pages/patientView/sampleHeader/mouse_icon.svg
  src/pages/patientView/sampleHeader/organoid_icon.svg
  typings/missing.d.ts
Labels: enhancement

#4961 Add Patient and Sample Resources to Study View
  end-to-end-test/remote/screenshots/reference/tcga_pancancer_atlas_page_element_chrome_1600x1000.png
  src/pages/studyView/StudyViewPage.tsx
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/resources/FilesAndLinks.tsx
  src/pages/studyView/resources/ResourcesTab.tsx
  src/shared/api/urls.ts
Labels: enhancement

#4980 Genomic and Generic assay bin counts tests
  apiTests/specs/generic-assay-data-bin-counts.json
  apiTests/specs/genomic-data-bin-counts.json
Labels: DO NOT MERGE
