Repository cBioPortal/cbioportal-frontend, pull requests merged in 2024-12, with the labels that each got.

#4924 Group comparison view: update boxplot info in clinical tab
  end-to-end-test/local/screenshots/reference/shows_table_when_selecting_table_visualisation_element_chrome_1600x1000.png
  src/pages/groupComparison/ClinicalNumericalDataVisualisation.tsx
  src/pages/groupComparison/GroupComparisonUtils.tsx
  src/pages/groupComparison/SummaryStatisticsTable.tsx
  src/shared/components/plots/BoxScatterPlot.tsx
Labels: enhancement

#5060 Configure timeline changes for cdsi data release
  src/appBootstrapper.tsx
  src/pages/patientView/timeline/timeline_helpers.tsx
Labels: skip-changelog

#5065 add donate button
  src/appShell/App/PortalHeader.tsx
  src/config/IAppConfig.ts
Labels: enhancement

#5057 Use NP instead of NS for Mutations in Download tab
  src/pages/resultsView/download/DownloadUtils.spec.ts
  src/pages/resultsView/download/DownloadUtils.ts
Labels: bug

#5067 automate jitpack build and frontend version update for new releases
  .github/workflows/jitpack-build.yml
Labels: devops

#5061 Change file and links name to resource displayName
  src/pages/studyView/StudyViewPage.tsx
Labels: enhancement
