Repository cBioPortal/cbioportal-frontend, pull requests merged in 2024-07, with the labels that each got.

#4922 Fix swapping generic assay profiles in comparison view
  src/pages/groupComparison/GenericAssayEnrichments.tsx
  src/shared/lib/comparison/ComparisonStore.ts
Labels: bug

#4936 Move 'juice' inside cbioportal-frontend-commons
  package.json
  packages/cbioportal-frontend-commons/package.json
Labels: bug, dependencies

#4930 Fix mutational sig bug
  end-to-end-test/local/screenshots/reference/show_mutational_bar_chart_dbs_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/show_mutational_bar_chart_id_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/show_mutational_bar_chart_sbs_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/show_mutational_signatures_table_for_patient_who_has_significant_id_signatures_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/show_mutational_signatures_table_for_patient_who_has_significant_sbs_signatures_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/show_the_bar_chart_with_percentage_on_y_axis_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/show_tooltip_for_patient_who_has_significant_dbs_signatures_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/show_tooltip_for_patient_who_has_significant_id_signatures_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/show_tooltip_for_patient_who_has_significant_sbs_signatures_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/switch_between_samples_to_update_mutational_bar_chart_element_chrome_1600x1000.png
  src/pages/patientView/PatientViewPageTabs.tsx
  src/pages/patientView/PatientViewPageUtils.tsx
  src/pages/patientView/clinicalInformation/ClinicalInformationMutationalSignatureTable.spec.tsx
  src/pages/patientView/clinicalInformation/ClinicalInformationMutationalSignatureTable.tsx
  src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
  src/pages/patientView/mutationalSignatures/MutationalSignatureBarChartUtils.ts
  src/pages/patientView/mutationalSignatures/MutationalSignaturesContainer.tsx
  src/pages/patientView/mutationalSignatures/MutationalSignaturesDataStore.ts
  src/shared/lib/GenericAssayUtils/GenericAssayCommonUtils.ts
Labels: bug

#4940 Update screenshots after oncokb data and clinical data tab column change
  end-to-end-test/remote/screenshots/reference/no_session_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/study_view_laml_tcga_clinical_data_clicked_element_chrome_1600x1000.png
Labels: test

#4944 Regenerate api clients
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal.ts
Labels: chore

#4946 Fix e2e tests after microbiome generic assay removed
  end-to-end-test/remote/screenshots/reference/tcga_pancancer_atlas_page_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/comparisonTab.screenshot.spec.js
  end-to-end-test/remote/specs/core/groupComparison.screenshot.spec.js
  end-to-end-test/remote/specs/core/studyview.spec.js
Labels: test

#4947 Fix flaky e2e test on patient view line chart
  end-to-end-test/remote/specs/core/genomicEvolution.screenshot.spec.js
Labels: test

#4952 Show summary stats on homepage
  src/shared/components/query/QueryStore.ts
  src/shared/components/query/StudySelectorStats.tsx
Labels: enhancement
