Repository cBioPortal/cbioportal-frontend, pull requests merged in 2024-11, with the labels that each got.

#5034 On Study View handle larger number of resource files
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal.ts
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPI-docs.json
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPI.ts
  packages/oncokb-ts-api-client/src/generated/OncoKbAPI-docs.json
  packages/oncokb-ts-api-client/src/generated/OncoKbAPI.ts
  src/pages/studyView/resources/FilesAndLinks.tsx
Labels: performance

#5038 Modify fetch resources from single study to multi-study
  src/pages/studyView/resources/FilesAndLinks.tsx
Labels: bug

#5040 add retry logic for 404 errors
  .github/workflows/jitpack-build.yml
Labels: devops

#5039 Fix Sift and Polyphen blank in NRAS
  packages/react-variant-view/src/component/functionalPrediction/FunctionalPrediction.tsx
  src/shared/components/mutationTable/MutationTable.tsx
  src/shared/components/mutationTable/column/FunctionalImpactColumnFormatter.tsx
Labels: bug

#4964 Add description to top of resource tab on patient view
  src/shared/components/resources/ResourceTab.tsx
Labels: enhancement

#5042 Add alphaMissense in functional impact column
  src/shared/components/annotation/genomeNexus/AlphaMissense.tsx
  src/shared/components/annotation/genomeNexus/MutationAssessor.tsx
  src/shared/components/annotation/genomeNexus/PolyPhen2.tsx
  src/shared/components/annotation/genomeNexus/Sift.tsx
  src/shared/components/annotation/genomeNexus/styles/alphaMissenseTooltip.module.scss
  src/shared/components/annotation/genomeNexus/styles/alphaMissenseTooltip.module.scss.d.ts
  src/shared/components/mutationTable/MutationTable.tsx
  src/shared/components/mutationTable/column/FunctionalImpactColumnFormatter.tsx
  src/shared/components/mutationTable/column/alphaMissenseGoogleDeepmind.png
Labels: feature

#5028 Fix sample/study counter in VS description
  src/pages/studyView/virtualStudy/VirtualStudyModal.tsx
Labels: bug

#5016 Implement RFC85 Dynamic Virtual Study
  src/appShell/App/usageAgreements/StudyAgreement.tsx
  src/globalStyles/global.scss
  src/pages/studyView/StudyViewUtils.tsx
  src/pages/studyView/virtualStudy/VirtualStudy.tsx
  src/pages/studyView/virtualStudy/VirtualStudyModal.tsx
Labels: feature

#5053 add trigger for modified labels
  .github/workflows/release-management.yml
Labels: devops

#5056 eliminate code issues in jitpack github workflow
  .github/workflows/jitpack-build.yml
Labels: devops
