Repository cBioPortal/cbioportal-frontend, pull requests merged in 2024-04, with the labels that each got.

#4876 set showNA to false by default
  end-to-end-test/remote/screenshots/reference/check_for_survival_plots_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/filter_study_from_url_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/fusion_filter_filter_study_from_url_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/generic_assay_chart_should_be_added_in_the_summary_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/loads_a_virtual_study_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/loads_multiple_studies_with_treatments_tables_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/tcga_pancancer_atlas_page_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/the_msi_score_should_use_the_custom_bins,_then_the_msi_score_column_should_be_added_in_the_clinical_data_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/when_quickly_adding_charts,_each_chart_should_get_proper_data._element_chrome_1600x1000.png
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/charts/barChart/BarChart.tsx
Labels: enhancement, gsoc

#4794 Mutation pie chart and multi-selection table
  end-to-end-test/local/screenshots/reference/add_custom_data_tab_should_have_numerical_and_categorical_selector_element_chrome_1600x1000.png
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal.ts
  src/pages/studyView/StudyViewConfig.ts
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/StudyViewUtils.tsx
  src/pages/studyView/UserSelections.tsx
  src/pages/studyView/addChartButton/AddChartButton.tsx
  src/pages/studyView/addChartButton/geneLevelSelection/GeneLevelSelection.tsx
  src/pages/studyView/charts/ChartContainer.tsx
  src/pages/studyView/studyPageHeader/StudyPageHeader.tsx
  src/pages/studyView/table/MultiSelectionTable.tsx
  src/pages/studyView/tabs/SummaryTab.tsx
  src/shared/constants.ts
Labels: feature

#4887 Restore postLoadForMSKCIS function as NOOP
  src/appBootstrapper.tsx
Labels: bug, skip-changelog

#4888 Fixed png download for group comparison clinical data
  package.json
  packages/cbioportal-frontend-commons/src/components/downloadControls/DownloadControls.tsx
  yarn.lock
Labels: bug, gsoc

#4892 fixed menu stretch in long confirmation messages
  src/pages/studyView/addChartButton/AddChartButton.tsx
  src/pages/studyView/infoBanner/SuccessBanner.tsx
Labels: style tweak, gsoc

#4894 Remove feature flag for generic assay group comparison feature
  end-to-end-test/local/screenshots/reference/results_view_comparison_tab_alteration_enrichments_patient_mode_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/results_view_comparison_tab_alteration_enrichments_several_groups_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/results_view_comparison_tab_alteration_enrichments_two_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_microbiome_signature_tab_several_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_microbiome_signature_tab_two_groups_element_chrome_1600x1000.png
  src/shared/featureFlags.ts
  src/shared/lib/comparison/ComparisonStore.ts
Labels: feature
