Repository cBioPortal/cbioportal-frontend, pull requests merged in 2024-10, with the labels that each got.

#5018 Log study view filter endpoints go datadog
  package.json
  src/appBootstrapper.tsx
  yarn.lock
Labels: skip-changelog

#5015 API client update about Mutation Assessor v4 data and UI changes
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPI-docs.json
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPI.ts
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPIInternal-docs.json
  packages/genome-nexus-ts-api-client/src/generated/GenomeNexusAPIInternal.ts
  packages/react-variant-view/src/component/functionalPrediction/FunctionalPrediction.tsx
  packages/react-variant-view/src/component/functionalPrediction/MutationAssessor.tsx
  src/shared/components/annotation/genomeNexus/MutationAssessor.tsx
  src/shared/components/mutationTable/column/FunctionalImpactColumnFormatter.tsx
Labels: cl-package

#5020 Add datadog logging for genie
  src/appBootstrapper.tsx
Labels: skip-changelog

#5021 Validate axio
  api-e2e/clickhouse.js
  api-e2e/public.js
  api-e2e/run.js
  apiTests/specs/clinical-data-filters.json
  apiTests/specs/custom-data-bin-counts-filter.json
  apiTests/specs/custom-data-counts-filter.json
  apiTests/specs/generic-assay-data-bin-counts.json
  apiTests/specs/genie-public.json
  apiTests/specs/genomic-data-bin-counts.json
  apiTests/specs/mutation-data-counts.json
  apiTests/specs/sample-lists-counts-filter.json
  package.json
  src/pages/studyView/rfc80Tester.tsx
  src/shared/api/cbioportalInternalClientInstance.ts
  src/shared/api/validation.ts
  webpack.config.js
  yarn.lock
Labels: skip-changelog

#4994 Custom data Enhancements for Plots Tab
  src/pages/resultsView/ResultsViewPage.tsx
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/oncoprint/TracksMenu.tsx
  src/pages/studyView/StudyViewPage.tsx
  src/pages/studyView/StudyViewPageStore.ts
  src/shared/components/plots/PlotsTab.tsx
  src/shared/components/plots/PlotsTabUtils.tsx
Labels: enhancement

#5023 Fix mskcc study usage acknowledgement
  src/appShell/App/usageAgreements/StudyAgreement.tsx
  src/shared/components/UsageAgreement.tsx
Labels: skip-changelog

#5025 Update StudyAgreement.tsx text
  src/appShell/App/usageAgreements/StudyAgreement.tsx
Labels: skip-changelog

#5026 Remove errant period from study agreement language
  src/appShell/App/usageAgreements/StudyAgreement.tsx
Labels: skip-changelog

#5037 Add Mutation Assessor V4 available date on tooltip
  packages/react-variant-view/src/component/functionalPrediction/MutationAssessor.tsx
  src/shared/components/mutationTable/column/FunctionalImpactColumnFormatter.tsx
Labels: cl-style-tweak
