Repository cBioPortal/cbioportal-frontend, pull requests merged in 2025-06, with the labels that each got.

#5201 Remove Darwin (MSK Internal)
  src/pages/patientView/patientHeader/PatientHeader.tsx
Labels: skip-changelog

#5192 Add pie chart download options to table download options on study view
  packages/cbioportal-frontend-commons/src/components/downloadControls/DownloadControls.tsx
  src/pages/studyView/chartHeader/ChartHeader.tsx
  src/pages/studyView/charts/ChartContainer.tsx
  src/pages/studyView/tabs/SummaryTab.tsx
Labels: enhancement

#5193 Fix filter checked state when navigating back to home page
  src/shared/components/query/CancerStudySelector.tsx
  src/shared/components/query/DataTypeFilter.tsx
  src/shared/components/query/QueryStore.ts
  src/shared/components/query/QueryStoreUtils.ts
Labels: bug

#5222 Remove na=0 values which prevent validation
  src/shared/api/validation.ts
Labels: skip-changelog
