Repository cBioPortal/cbioportal-frontend, pull requests merged in 2025-01, with the labels that each got.

#5076 update screenshost after gene table update
  end-to-end-test/remote/screenshots/reference/coexpression_tab_coadread_tcga_pub_switch_profiles_+_regression_line_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/coexpression_tab_coadread_tcga_pub_switch_tabs_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/coexpression_tab_coadread_tcga_pub_with_user_defined_case_list_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/download_tab_-_msk_impact_2017_with_alk_and_sos1_-_sos1_should_be_not_sequenced_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/download_tab_-_nsclc_tcga_broad_2016_for_query_egfr:_mut=t790m_amp_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/download_tab_-_nsclc_tcga_broad_2016_with_cdkn2a_mdm2_and_merged_track_mdm4_tp53_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/download_tab_-_nsclc_tcga_broad_2016_with_overlapping_tp53_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/download_tab_-_nsclc_tcga_broad_2016_with_tp53_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/enrichments_tab_coadread_tcga_pub_mrna_profile_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_coexpression_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_comparison_tab_mrna_enrichments_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_data_download_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_mrna_enrichments_tab_two_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_mutations_tab_two_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_comparison_tab_mrna_enrichments_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_mutation_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/patient_page_valid_after_cohort_navigation_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_box_plot_color_by_tumor_type_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_box_plot_color_by_tumor_type_highlight_categories_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_one_box_clinical_vs_clinical_boxplot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_scatter_plot_color_by_tumor_type_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_scatter_plot_color_by_tumor_type_highlight_categories_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_waterfall_plot_color_by_tumor_type_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_waterfall_plot_color_by_tumor_type_highlight_categories_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_heatmap_with_two_mutations_selected_from_before_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_hover_a_mutation_with_heatmap_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/pvge_one_mutation_selected_with_heatmap_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_mrna_enrichments_tab_several_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_mrna_enrichments_tab_two_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_comparison_tab_mrna_enrichments_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_mutation_tab_element_chrome_1600x1000.png
Labels: test

#5079 Fix log scale breaking box plot in plots tab
  end-to-end-test/remote/screenshots/reference/enrichments_tab_coadread_tcga_pub_mrna_profile_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_comparison_tab_clinical_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_comparison_tab_mrna_enrichments_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_plots_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_clinical_tab_include_overlapping_samples_kruskal_wallis_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_clinical_tab_log_scale__kruskal_wallis_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_clinical_tab_swaped_axes_kruskal_wallis_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_methylation_enrichments_tab_several_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_methylation_enrichments_tab_two_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_mrna_enrichments_tab_several_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_mrna_enrichments_tab_two_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_protein_enrichments_tab_several_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_comparison_page_protein_enrichments_tab_two_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_comparison_tab_mrna_enrichments_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_plots_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_box_plot_color_by_mutation_count_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_box_plot_color_by_mutation_count_log_scale_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_box_plot_color_by_tumor_type_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_box_plot_color_by_tumor_type_highlight_categories_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_box_plot_log_scale_zero_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_boxplot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_molecular_boxplot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_molecular_vs_clinical_boxplot,_mutation_search_off_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutation_type_view_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_driver_mode_vs_clinical_boxplot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_profile_with_duplicates_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_vs_clinical_boxplot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_wild_type_mode_vs_clinical_boxplot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_one_box_clinical_vs_clinical_boxplot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_search_case_id_in_clinical_vs_clinical_boxplot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_with_structural_variant_coloring_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_include_overlapping_samples_kruskal_wallis_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_log_scale__kruskal_wallis_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_clinical_tab_swaped_axes_kruskal_wallis_test_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_methylation_enrichments_tab_several_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_mrna_enrichments_tab_several_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_mrna_enrichments_tab_two_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_protein_enrichments_tab_several_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/results_view_comparison_tab_protein_enrichments_tab_two_groups_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_comparison_tab_mrna_enrichments_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_plots_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/plots.screenshot.spec.js
  src/shared/components/plots/BoxScatterPlot.tsx
Labels: bug

#5082 Update api client
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal.ts
  src/pages/studyView/StudyViewPageStore.ts
Labels: chore

#5019 Reduce api calls for generic assay meta in study view page
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/addChartButton/AddChartButton.tsx
  src/shared/lib/GenericAssayUtils/GenericAssayCommonUtils.ts
Labels: performance

#5084 Update function logScalePossible for generic assay negative data
  src/shared/components/plots/PlotsTabUtils.spec.ts
  src/shared/components/plots/PlotsTabUtils.tsx
Labels: bug

#4990 Add truncation of timeline label
  packages/cbioportal-clinical-timeline/src/TrackHeader.tsx
  packages/cbioportal-clinical-timeline/src/timeline.scss
Labels: enhancement

#5046 On Study View sort structural variant table by sample count
  src/pages/studyView/charts/ChartContainer.tsx
Labels: bug

#5045 Fix sv tab genome nexus client
  src/pages/resultsView/ResultsViewPageStore.ts
  src/pages/resultsView/structuralVariant/ResultsViewStructuralVariantMapperStore.ts
Labels: bug

#4953 Improve Homepage Search: Automatically Hide Dropdown on Typing
  src/shared/components/query/StudySearch.tsx
Labels: enhancement, public contribution

#5093 epic warning banner for MSK portals
  src/shared/components/userMessager/UserMessage.tsx
Labels: skip-changelog

#4960 Add Stacked Bar Chart and sorting to Plots Tab
  end-to-end-test/local/screenshots/reference/show_binary_vs_os_status_plot_element_chrome_1600x1000.png
  end-to-end-test/local/screenshots/reference/show_category_vs_os_status_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_horizontal_grouped_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_horizontal_grouped_bar_plot_sort_by_category_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_horizontal_grouped_bar_plot_sort_by_number_of_samples_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_horizontal_percentage_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_horizontal_percentage_stacked_bar_plot_sort_by_category_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_horizontal_percentage_stacked_bar_plot_sort_by_number_of_samples_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_horizontal_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_horizontal_stacked_bar_plot_sort_by_category_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_horizontal_stacked_bar_plot_sort_by_number_of_samples_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_percentage_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_percentage_stacked_bar_plot_sort_by_category_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_percentage_stacked_bar_plot_sort_by_number_of_samples_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_stacked_bar_plot_sort_by_category_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_clinical_vs_clinical_stacked_bar_plot_sort_by_number_of_samples_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_copy_number_vs_clinical_horizontal_percentage_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_copy_number_vs_clinical_horizontal_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_copy_number_vs_clinical_percentage_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_copy_number_vs_clinical_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_multiple_studies_with_data_availability_alert_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_vs_clinical_horizontal_percentage_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_vs_clinical_horizontal_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_vs_clinical_percentage_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_vs_clinical_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_wildtype_mode_vs_clinical_horizontal_percentage_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_wildtype_mode_vs_clinical_horizontal_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_wildtype_mode_vs_clinical_percentage_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/plots_tab_mutations_wildtype_mode_vs_clinical_stacked_bar_plot_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/plots.screenshot.spec.js
  src/pages/groupComparison/CategoryPlot.tsx
  src/pages/resultsView/enrichments/EnrichmentsUtil.tsx
  src/pages/resultsView/enrichments/GeneBarPlot.tsx
  src/pages/resultsView/enrichments/GenericAssayBarPlot.tsx
  src/shared/components/plots/BoxScatterPlot.tsx
  src/shared/components/plots/MultipleCategoryBarPlot.tsx
  src/shared/components/plots/MultipleCategoryBarPlotUtils.spec.ts
  src/shared/components/plots/MultipleCategoryBarPlotUtils.ts
  src/shared/components/plots/PlotsTab.tsx
Labels: ready to review, feature, gsoc

#5097 Fix compare button for treatment tables on study view
  end-to-end-test/remote/specs/core/studyview.spec.js
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/charts/ChartContainer.tsx
Labels: bug
