Repository cBioPortal/cbioportal-frontend, pull requests merged in 2025-07, with the labels that each got.

#5230 Fx07014
  end-to-end-test/remote/screenshots/reference/can_filter_a_study_by_patient_treatments_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/can_filter_a_study_by_sample_treatments_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/check_for_survival_plots_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/download_tab_-_msk_impact_2017_with_alk_and_sos1_-_sos1_should_be_not_sequenced_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/download_tab_-_nsclc_tcga_broad_2016_for_query_egfr:_mut=t790m_amp_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/download_tab_-_nsclc_tcga_broad_2016_with_cdkn2a_mdm2_and_merged_track_mdm4_tp53_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/download_tab_-_nsclc_tcga_broad_2016_with_overlapping_tp53_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/download_tab_-_nsclc_tcga_broad_2016_with_tp53_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_data_download_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/loads_a_virtual_study_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_data_download_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/non_cancer_gene_should_show_up_when_the_cancer_gene_filter_is_disabled_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/profiled_in_tracks_in_multiple_study_with_sos1_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_data_download_tab_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/shows_mutation_frequencies_correctly_for_called_but_unprofiled_mutations_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/tcga_pancancer_atlas_page_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/the_cancer_gene_filter_should_remove_non_cancer_gene_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/when_adding_chart_with_categories_more_than_the_pie2table_threshold,_the_pie_chart_should_be_converted_to_table_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/when_quickly_adding_charts,_each_chart_should_get_proper_data._element_chrome_1600x1000.png
Labels: chore

#5185 Rfc95 study download
  src/config/IAppConfig.ts
  src/config/serverConfigDefaults.ts
  src/pages/staticPages/datasetView/DatasetList.tsx
  src/pages/studyView/studyPageHeader/studySummary/StudySummary.tsx
  src/shared/api/urls.ts
  src/shared/components/StudyDataDownloadLink/StudyDataDownloadLink.tsx
Labels: feature

#5234 Fix comparison alterations tab and breadcrumbs localdb tests
  end-to-end-test/local/screenshots/reference/breadcrumbs_are_editable_for_mutation_count_chart_element_chrome_1600x1000.png
  end-to-end-test/local/specs/core/comparison-alterations-tab.spec.js
Labels: test

#5241 Update citation link in "Visualize Your Data" page
  src/pages/staticPages/visualize/Visualize.tsx
Labels: cl-style-tweak

#5243 Increase selected info wait timeout to stabilize study view tests
  end-to-end-test/shared/specUtils_Async.js
Labels: test

#5118 RFC93: Custom variant annotation filter in study view page
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPI-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPI.ts
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal-docs.json
  packages/cbioportal-ts-api-client/src/generated/CBioPortalAPIInternal.ts
  packages/cbioportal-ts-api-client/src/index.tsx
  src/pages/studyView/StudyViewComparisonUtils.ts
  src/pages/studyView/StudyViewConfig.ts
  src/pages/studyView/StudyViewPage.tsx
  src/pages/studyView/StudyViewPageStore.ts
  src/pages/studyView/StudyViewUtils.tsx
  src/pages/studyView/TableUtils.tsx
  src/pages/studyView/UserSelections.tsx
  src/pages/studyView/addChartButton/AddChartButton.tsx
  src/pages/studyView/chartHeader/ChartHeader.tsx
  src/pages/studyView/charts/ChartContainer.tsx
  src/pages/studyView/studyPageHeader/StudyPageHeader.tsx
  src/pages/studyView/table/MultiSelectionTable.tsx
  src/pages/studyView/tabs/SummaryTab.tsx
Labels: feature

#5245 Update screenshots for download tab alteration table ordering
  end-to-end-test/remote/screenshots/reference/download_tab_-_nsclc_tcga_broad_2016_for_query_egfr:_mut=t790m_amp_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/download_tab_-_nsclc_tcga_broad_2016_with_cdkn2a_mdm2_and_merged_track_mdm4_tp53_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/download_tab_-_nsclc_tcga_broad_2016_with_overlapping_tp53_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/download_tab_-_nsclc_tcga_broad_2016_with_tp53_element_chrome_1600x1000.png
Labels: test
