Repository cBioPortal/cbioportal-frontend, pull requests merged in 2025-03, with the labels that each got.

#5119 Fix flaky e2e remote tests
  end-to-end-test/remote/screenshots/reference/patient_page_valid_after_cohort_navigation_element_chrome_1600x1000.png
  end-to-end-test/remote/specs/core/genomicEvolution.screenshot.spec.js
  end-to-end-test/remote/specs/core/home.spec.js
  end-to-end-test/remote/specs/core/resultsOncoprintColorConfig.spec.js
  end-to-end-test/remote/specs/core/screenshot.spec.js
Labels: test

#5110 Add sample and patient counts toggle for cancer summary chart tooltip
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_cancer_type_summary_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_by_detailed_type_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/handles_change_to_absolute_value_yaxis_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/handles_change_to_sample_total_threshold_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/handles_change_to_sort_of_xaxis_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_cancer_type_summary_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_cancer_type_summary_element_chrome_1600x1000.png
  src/pages/resultsView/cancerSummary/CancerSummaryChart.spec.tsx
  src/pages/resultsView/cancerSummary/CancerSummaryChart.tsx
  src/pages/resultsView/cancerSummary/CancerSummaryContainer.tsx
  src/pages/resultsView/cancerSummary/CancerSummaryContent.spec.tsx
  src/pages/resultsView/cancerSummary/CancerSummaryContent.tsx
  src/shared/lib/alterationCountHelpers.spec.ts
  src/shared/lib/alterationCountHelpers.ts
Labels: enhancement

#5121 Fix e2e localdb results comparison alteration tests
  end-to-end-test/local/specs/annotation-filter-menu.spec.js
Labels: test

#5127 Fix screenshot tracking in circleci localdb tests
  .circleci/config.yml
Labels: test

#5139 Fix broken studyview e2e remote tests
  end-to-end-test/remote/screenshots/reference/check_for_survival_plots_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/fusion_filter_filter_study_from_url_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/loads_a_virtual_study_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/loads_multiple_studies_with_treatments_tables_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/tcga_pancancer_atlas_page_element_chrome_1600x1000.png
Labels: test

#5128 Replace Jitpack with Github Packages
  .github/workflows/github-package-build.yml
  .github/workflows/jitpack-build.yml
  pom.xml
Labels: devops

#5133 Improve layout of cancer summary page
  end-to-end-test/remote/screenshots/reference/excluding_unprofiled_samples_cancer_type_summary_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/group_by_detailed_type_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/handles_change_to_absolute_value_yaxis_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/handles_change_to_sample_total_threshold_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/handles_change_to_sort_of_xaxis_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/no_session_cancer_type_summary_element_chrome_1600x1000.png
  end-to-end-test/remote/screenshots/reference/session_cancer_type_summary_element_chrome_1600x1000.png
  src/pages/resultsView/cancerSummary/CancerSummaryChart.tsx
  src/pages/resultsView/cancerSummary/CancerSummaryContent.tsx
  src/pages/resultsView/cancerSummary/styles.scss
Labels: enhancement
